// addConnections18.js - Expand short descriptions for US entries (68 entries)
const fs = require('fs');
const path = require('path');
const jewishFile = path.join(__dirname, '..', 'data', 'jewish.json');
const data = JSON.parse(fs.readFileSync(jewishFile, 'utf8'));
const entryIndex = {};
for (const country in data.countries) { for (const entry of data.countries[country]) { entryIndex[entry.id] = { entry, country }; } }
function updDesc(id, d) { if (entryIndex[id]) entryIndex[id].entry.description = d; }

// === US ADVOCACY & EDUCATION ===
updDesc('j-street', 'Pro-Israel, pro-peace advocacy organization founded in 2007 by Jeremy Ben-Ami. J Street lobbies the U.S. government on behalf of a two-state solution to the Israeli-Palestinian conflict and has become a major counterweight to AIPAC within the American Jewish political landscape. The organization maintains a PAC (J Street PAC) that is one of the largest pro-Israel PACs in the country, endorsing and funding congressional candidates who support diplomatic solutions. J Street has faced controversy from both the right, which considers it insufficiently supportive of Israeli policies, and parts of the left who find it too centrist. It has strong ties to the Democratic Party and has been endorsed by numerous Jewish communal leaders.');

updDesc('standwithus', 'International Israel education organization founded in 2001 by Roz and Jerry Rothstein in Los Angeles. StandWithUs combats antisemitism and delegitimization of Israel through campus advocacy, educational programs, and media campaigns across 19 offices worldwide. The organization runs the Emerson Fellowship, training college students as Israel advocates, and has been at the center of campus battles over BDS (Boycott, Divestment, Sanctions) movements. StandWithUs works closely with the Israeli government, receiving funding from the Ministry of Strategic Affairs, and partners with major Jewish organizations including Hillel and the Jewish Federations of North America.');

updDesc('yeshiva-university', 'Private Orthodox Jewish university in New York City, founded in 1886, and the oldest Jewish university in the United States. Yeshiva University combines secular academic programs with intensive Torah study, operating the prestigious Benjamin N. Cardozo School of Law and the Albert Einstein College of Medicine until its sale to Montefiore in 2019. The university has produced generations of Modern Orthodox rabbinical and lay leaders, and its rabbinical seminary (RIETS) ordains more Orthodox rabbis than any institution in America. Notable alumni include Senator Joe Lieberman, novelist Chaim Potok, and Rabbi Joseph Soloveitchik, one of the most influential Orthodox thinkers of the 20th century. YU has been at the center of debates about the intersection of Orthodoxy and modernity, including recent Supreme Court cases regarding LGBTQ student groups.');

updDesc('hillel-international', 'Foundation for Jewish campus life, engaging college students at more than 550 campuses worldwide. Founded in 1923 at the University of Illinois by Rabbi Benjamin Frankel, Hillel is the largest Jewish campus organization in the world. Named after the ancient Jewish sage Hillel the Elder, the organization provides religious, cultural, social, and Israel-related programming. Hillel\'s engagement model reaches hundreds of thousands of students annually. The organization has faced debates about its Israel guidelines, which restrict partnerships with groups that support BDS. Major funders include the Charles and Lynn Schusterman Family Philanthropies, the Jim Joseph Foundation, and billionaire philanthropist Lynn Schusterman. Edgar Bronfman Sr. served as a transformative board chair.');

updDesc('the-jewish-museum-new-york', 'Art and cultural museum located on Manhattan\'s Museum Mile at the former Warburg mansion on Fifth Avenue, exploring 4,000 years of art and Jewish culture. Founded in 1904 with a gift of 26 ceremonial objects to the Jewish Theological Seminary, it has grown into one of the world\'s preeminent Jewish museums with a collection of nearly 30,000 objects. The museum\'s exhibitions range from ancient archaeological artifacts to contemporary art, and have featured major retrospectives of artists like Marc Chagall, Amedeo Modigliani, and Modigliani. Its permanent collection includes works by leading 20th-century artists with Jewish connections. The museum occupies the Felix M. Warburg House, a 1908 Gothic Revival mansion donated by Frieda Schiff Warburg, connecting it to two of the most prominent Jewish banking dynasties in American history.');

// === US FINANCE & BUSINESS ===
updDesc('goldman-sachs', 'Major global investment bank and financial services company, founded in 1869 by Marcus Goldman, a German-Jewish immigrant, and later joined by his son-in-law Samuel Sachs. Goldman Sachs has been one of the most powerful financial institutions in the world, with enormous influence on global markets, government economic policy, and corporate finance. The firm has produced multiple U.S. Treasury Secretaries, including Robert Rubin, Hank Paulson, and Steven Mnuchin. CEO Lloyd Blankfein (2006–2018) and current CEO David Solomon are both Jewish. The firm manages over $2.5 trillion in assets and has been central to virtually every major financial event of the modern era, from IPOs of tech giants to the 2008 financial crisis. Goldman\'s culture of alumni in government has earned it the nickname "Government Sachs."');

updDesc('warner-bros-discovery', 'Global media and entertainment conglomerate formed by the 2022 merger of Warner Bros. and Discovery, Inc. Warner Bros. was originally founded in 1923 by four Jewish brothers—Harry, Albert, Sam, and Jack Warner—who were sons of Polish-Jewish immigrants. The studio was a pioneer of the "talkie" era, producing The Jazz Singer (1927), the first feature-length talking picture. Today the company encompasses HBO, CNN, DC Comics, Warner Bros. Pictures, Discovery Channel, and numerous other media properties. David Zaslav, the CEO, oversees a media empire that reaches billions of people worldwide. The company\'s Jewish founding and ongoing leadership connections make it a cornerstone of Jewish involvement in the entertainment industry.');

updDesc('starbucks', 'Global coffeehouse chain and coffee company founded in 1971 in Seattle. While not founded by Jewish individuals, Starbucks was transformed into a global phenomenon by Howard Schultz, a Jewish American businessman who joined the company in 1982 and served as CEO (1986–2000, 2008–2017, 2022–2023). Schultz, the son of a World War II veteran who grew up in a Brooklyn housing project, built Starbucks from 11 stores to over 35,000 locations in 80 countries. He introduced the Italian espresso bar concept and pioneered employee benefits including health coverage for part-time workers and stock options. Schultz has been a prominent Jewish-American business leader, briefly exploring a presidential run in 2019, and has been a supporter of Israel and Jewish causes.');

updDesc('citadel-llc', 'Multinational hedge fund and financial services company founded in 1990 by Kenneth C. Griffin. While Griffin himself is not Jewish, the firm has significant Jewish connections in its leadership, investor base, and operations within the heavily Jewish-influenced hedge fund industry. Citadel is one of the largest and most successful hedge funds in history, managing approximately $60 billion in assets. The firm\'s market-making arm, Citadel Securities, handles roughly 25% of all U.S. equity trading volume. Citadel has been at the center of major market events, including the 2021 GameStop short squeeze controversy, and Griffin is one of the largest political donors in the United States.');

updDesc('wachtell-lipton-rosen-katz', 'Elite New York law firm founded in 1965 by Herbert Wachtell, Martin Lipton, Leonard Rosen, and George Katz—all Jewish attorneys. Wachtell Lipton is consistently ranked as the most prestigious and highest-grossing law firm per lawyer in the world, with partners earning multi-million dollar annual compensation. Martin Lipton invented the "poison pill" corporate defense mechanism in 1982, fundamentally changing the landscape of mergers and acquisitions law. The firm exclusively handles the largest and most complex corporate transactions, advising on deals worth trillions of dollars. Despite having only about 270 lawyers (compared to thousands at other major firms), Wachtell commands extraordinary influence in corporate America and has shaped modern takeover law.');

updDesc('fried-frank-harris-shriver-jacobson', 'International law firm based in New York, founded in 1971, with a distinguished history in corporate law, real estate, and government regulatory work. The firm traces its roots to Jewish attorneys who built a practice serving the financial sector. Fried Frank has been involved in many of the largest real estate transactions in New York City\'s history and has a long tradition of public service, with partners serving in government positions including the Watergate Special Prosecution Force. The firm maintains offices in New York, Washington D.C., London, Paris, and Frankfurt, and has been particularly influential in cross-border transactions between the U.S. and Europe.');

updDesc('greenberg-traurig', 'Global law firm founded in 1967 in Miami by Mel Greenberg, Larry Hoffman, and Robert Traurig, all of Jewish background. With over 2,750 attorneys across 47 offices worldwide, it is one of the largest law firms in the world. The firm has become a major force in U.S. politics through its lobbying arm, with deep connections to both political parties. Jack Abramoff, the notorious lobbyist convicted of fraud, was a former Greenberg Traurig attorney. The firm represents major corporations, real estate developers, and government entities, and has been at the forefront of international business law, particularly in Latin America and the Middle East.');

updDesc('proskauer-rose', 'International law firm headquartered in New York, founded in 1875 by William Rose and later joined by Joseph Proskauer, a prominent Jewish attorney and civic leader who served as a justice of the New York Supreme Court and president of the American Jewish Committee (1943–1949). Judge Proskauer was instrumental in advocating for the creation of the State of Israel at the United Nations. The firm has grown into a global practice with approximately 725 lawyers specializing in sports law, labor and employment, private equity, and healthcare. Proskauer is considered the preeminent sports law firm in the world, representing the NFL, NBA, NHL, and Major League Baseball.');

updDesc('brookfield-asset-management', 'Global alternative asset management company managing over $900 billion in assets across real estate, infrastructure, renewable power, and private equity. While a Canadian-headquartered company, its operations are deeply connected to the Jewish business community. Bruce Flatt, the CEO since 2002, has built Brookfield into one of the largest alternative asset managers in the world. The firm owns iconic properties including Brookfield Place in Manhattan and Canary Wharf in London, and has significant holdings in renewable energy infrastructure worldwide.');

updDesc('vornado-realty-trust', 'One of the largest owners and managers of commercial real estate in the United States, founded and led by Steven Roth, a prominent Jewish-American real estate executive. Vornado owns premier office and retail properties in New York City and other major markets, including a significant stake in 1290 Avenue of the Americas and properties around Penn Station. Roth has been a close associate of the Kushner family and served as an advisor to President Trump on infrastructure. Vornado\'s portfolio is valued at tens of billions of dollars, making it one of the most influential REITs in the country.');

updDesc('tishman-speyer', 'Global real estate developer, owner, and operator founded by the Tishman family, one of New York City\'s most prominent Jewish real estate dynasties. The firm, now led by Rob Speyer, has built and managed some of the world\'s most iconic properties including Rockefeller Center, the MetLife Building (former Pan Am Building), and the Spiral in Hudson Yards. Jerry Speyer, Rob\'s father who married into the Tishman family, expanded the company internationally to include assets in Europe, Latin America, and Asia. The Speyer family has been major philanthropists in Jewish causes and arts institutions, including the Museum of Modern Art where Jerry served as chairman.');

updDesc('bain-capital', 'Private investment firm founded in 1984 by Mitt Romney, T. Coleman Andrews III, and Eric Kriss, among others. While Romney is not Jewish, several of Bain\'s most prominent partners and co-founders are, including Joshua Bekenstein (co-chairman) and Marc Wolpow. The firm manages approximately $180 billion in assets across private equity, ventures, public equity, credit, real estate, and other strategies. Bain Capital has invested in major companies including Domino\'s Pizza, Staples, Burlington Coat Factory, and Clear Channel (now iHeartMedia). The firm became politically prominent during Romney\'s 2012 presidential campaign, sparking national debates about private equity\'s role in the economy.');

updDesc('cerberus-capital-management', 'Private equity firm managing over $60 billion in assets, founded in 1992 by Steve Feinberg, a Jewish-American financier known for his extreme privacy. The firm is named after the three-headed dog that guards the gates of Hades in Greek mythology. Cerberus has made major acquisitions including Chrysler (2007), Albertsons grocery stores, and the firearms manufacturer Remington Arms, which drew significant controversy. Feinberg served as chairman of the President\'s Intelligence Advisory Board under Donald Trump. The firm\'s investments span distressed securities, private lending, real estate, and corporate turnarounds.');

updDesc('tiger-global-management', 'Investment firm founded in 2001 by Chase Coleman III, focused on both public and private technology companies. While Coleman himself is not Jewish, the firm has deep connections to the Jewish-influenced tech investment ecosystem and has been a major investor in Israeli tech companies. Tiger Global has made over 350 venture investments in companies like Facebook, LinkedIn, Spotify, and numerous Israeli startups. The firm emerged from Julian Robertson\'s Tiger Management and became one of the most prolific tech investors of the 2010s and 2020s, at one point managing over $100 billion in assets.');

// === US SPORTS ===
updDesc('new-york-giants-tisch-mara', 'NFL franchise co-owned by the Tisch family, one of America\'s most prominent Jewish business dynasties. Steve Tisch, co-owner and chairman of the New York Giants, is a billionaire film producer (Forrest Gump, Risky Business) and son of the late Bob Tisch, former U.S. Postmaster General. The Tisch family also controls Loews Corporation and has been among the most generous philanthropists in Jewish and general causes. Steve Tisch became the first person in history to win both a Super Bowl ring and an Academy Award. The Giants are one of the NFL\'s most storied franchises, founded in 1925.');

updDesc('washington-commanders-josh-harris', 'NFL franchise purchased in 2023 by a group led by Josh Harris, a Jewish-American billionaire who co-founded Apollo Global Management, one of the world\'s largest private equity firms. Harris\'s group paid a record $6.05 billion for the team. Harris also owns the Philadelphia 76ers (NBA) and the New Jersey Devils (NHL). The acquisition ended Dan Snyder\'s controversial 24-year ownership. Harris has been a major philanthropist, donating to Penn\'s Wharton School and various Jewish causes.');

updDesc('philadelphia-76ers-harris-blitzer', 'NBA franchise owned by Josh Harris and David Blitzer, both Jewish-American billionaires from the private equity world. Harris co-founded Apollo Global Management and Blitzer is a senior executive at Blackstone Group. They purchased the team in 2011 and have overseen the controversial "Trust the Process" era. Harris and Blitzer also co-own the New Jersey Devils (NHL) and have significant sports holdings in Europe. The 76ers are one of the NBA\'s most historic franchises, with championship legacies tied to Wilt Chamberlain, Julius Erving, and Allen Iverson.');

updDesc('golden-state-warriors-joe-lacob', 'NBA franchise owned by Joe Lacob, a Jewish-American venture capitalist and former partner at Kleiner Perkins. Lacob purchased the Warriors in 2010 for $450 million, and under his ownership, the team became one of the most dominant dynasties in NBA history, winning four championships (2015, 2017, 2018, 2022). The franchise is now valued at over $7 billion, making Lacob\'s investment one of the most successful in sports history. Lacob brought Silicon Valley management principles to professional sports and built the privately funded Chase Center arena in San Francisco. His co-owner Peter Guber is also Jewish.');

updDesc('cleveland-guardians-larry-dolan', 'MLB franchise owned by the Dolan family since 2000 when Larry Dolan, a Jewish-American attorney, purchased the team for $323 million. The Dolan family also owns the Cleveland Cavaliers (NBA). In 2022, the team changed its name from the Cleveland Indians to the Cleveland Guardians. Larry\'s brother Charles Dolan founded Cablevision and HBO, and his nephew James Dolan owns the New York Knicks and Madison Square Garden, making the Dolans one of the most powerful families in American sports and media.');

updDesc('new-york-mets-steve-cohen', 'MLB franchise purchased by Steve Cohen in 2020 for $2.4 billion, then a record for a U.S. sports team. Cohen is a Jewish-American billionaire hedge fund manager who founded Point72 Asset Management (formerly SAC Capital Advisors). He is one of the wealthiest team owners in professional sports with a net worth exceeding $17 billion. Cohen has dramatically increased the Mets\' payroll, making them one of baseball\'s highest spenders. His previous firm SAC Capital paid $1.8 billion in fines for insider trading violations. Cohen is a major art collector and philanthropist.');

// === US THINK TANKS ===
updDesc('brookings-institution', 'Prominent American research and policy institution founded in 1916, one of Washington\'s most influential think tanks. Brookings has had extensive Jewish leadership, including presidents Strobe Talbott and current president Cecilia Rouse. The institution\'s Saban Center for Middle East Policy, founded with a $13 million gift from Israeli-American media mogul Haim Saban, was a major center for Middle East policy research before merging into the Foreign Policy program. Martin Indyk, former U.S. Ambassador to Israel and a key figure in Israeli-American diplomacy, directed the Saban Center. Brookings researchers have been highly influential in shaping U.S. foreign policy toward Israel and the Middle East.');

updDesc('washington-institute-for-near-east-policy-winep', 'Policy research institute focused on U.S. Middle East policy, founded in 1985 by Martin Indyk with the support of AIPAC. WINEP has been one of the most influential think tanks shaping American policy toward Israel and the broader Middle East. Its founders and fellows include many prominent figures who have moved between the institute and senior government positions, including Dennis Ross, David Makovsky, and Robert Satloff (executive director since 1993). The institute has been both praised for its scholarly rigor and criticized by those who see it as advancing a pro-Israel agenda. WINEP regularly hosts Israeli and Arab officials and produces detailed policy analyses.');

updDesc('council-on-foreign-relations', 'Non-partisan think tank and publisher founded in 1921, one of the most influential foreign policy organizations in the United States. While not a Jewish organization, CFR has had significant Jewish leadership and membership. Richard Haass (Jewish) served as president from 2003 to 2023. The council publishes Foreign Affairs, the preeminent journal of international relations. CFR\'s membership has included nearly every Secretary of State, CIA Director, and senior foreign policy official. The organization has been a key venue for debate on U.S.-Israel relations, Middle East policy, and global affairs, with members including prominent Jewish diplomats, academics, and business leaders.');

updDesc('american-enterprise-institute-aei', 'Conservative think tank founded in 1938, focused on government, politics, economics, and social welfare. AEI has had significant Jewish intellectual leadership, including prominent neoconservative scholars who were instrumental in shaping post-9/11 U.S. foreign policy. Key Jewish figures have included Irving Kristol (the "godfather of neoconservatism"), his wife Gertrude Himmelfarb, Michael Ledeen, Joshua Muravchik, David Frum (who coined "Axis of Evil"), and current scholars like Frederick Kagan. AEI has been strongly supportive of Israel and has advocated for aggressive U.S. policy in the Middle East. The think tank receives funding from major conservative and Jewish philanthropists.');

updDesc('foundation-for-defense-of-democracies-fdd', 'Non-partisan policy institute founded in 2001 by Clifford May, focusing on national security and foreign policy. FDD has been one of the most hawkish think tanks on Iran and a strong advocate for U.S.-Israel security cooperation. Key Jewish figures include executive director Mark Dubowitz, who has been instrumental in designing Iran sanctions, and board members including Jewish-American philanthropists and former government officials. FDD has been influential in shaping the Trump administration\'s "maximum pressure" campaign against Iran and opposition to the JCPOA nuclear deal. Critics characterize it as a pro-Israel advocacy group, while supporters credit it with rigorous security analysis.');

updDesc('jewish-institute-for-national-security-of-america-jinsa', 'Non-partisan think tank founded in 1976, focusing on strengthening the U.S.-Israel security relationship and broader American defense policy. JINSA runs programs bringing retired U.S. military generals and admirals to Israel, creating a network of senior military voices supportive of the bilateral relationship. The organization has been led by prominent figures including Michael Makovsky (CEO) and has a board including former senior U.S. military and intelligence officials. JINSA\'s Gemunder Center publishes analyses on Middle East security, Iran, and U.S. defense policy. The institute\'s programs have been credited with deepening U.S.-Israel military-to-military ties.');

updDesc('middle-east-forum', 'Think tank founded in 1994 by Daniel Pipes, a prominent Jewish-American Middle East scholar and commentator. The Forum promotes American interests in the Middle East through research, advocacy, and public education. Pipes has been a controversial figure, criticized by some as Islamophobic and praised by others as a clear-eyed analyst of radical Islam. The Forum publishes the Middle East Quarterly journal, runs Campus Watch (monitoring Middle East studies programs), and operates the Legal Project defending free speech about Islam. The organization has been influential in conservative and neoconservative Middle East policy circles and maintains close ties to pro-Israel advocacy networks.');

// === US FASHION & ENTERTAINMENT ===
updDesc('calvin-klein-pvh-corp', 'Global fashion house known for its minimalist aesthetic, founded in 1968 by Calvin Klein, a Jewish-American designer from the Bronx. Klein revolutionized American fashion with his clean lines and provocative advertising campaigns, including iconic jeans ads featuring Brooke Shields and Mark Wahlberg. The brand, now part of PVH Corp (led by Jewish CEO Stefan Larsson until 2021), generates billions in annual revenue across fashion, fragrance, and home products. Calvin Klein\'s innovations in designer jeans, underwear, and fragrance marketing transformed the fashion industry and established the model for modern lifestyle branding.');

updDesc('donna-karan-dkny', 'Iconic American fashion brand founded in 1984 by Donna Karan (née Faske), a Jewish-American designer from Queens, New York. Karan revolutionized women\'s professional fashion with her "Seven Easy Pieces" system of interchangeable basics. She launched the more affordable DKNY line in 1989, bringing high fashion sensibility to a broader market. Karan\'s designs dressed multiple First Ladies and defined the power-dressing era of the 1980s and 1990s. She sold her company to LVMH in 2001, and the brand is now owned by G-III Apparel Group. Karan has been a major philanthropist, founding the Urban Zen Foundation focused on wellness, education, and preserving cultures.');

updDesc('uber-technologies', 'Ride-hailing and food delivery technology company co-founded in 2009 by Travis Kalanick and Garrett Camp. While neither founder is Jewish, the company has significant Jewish connections through its investors and leadership. Major early investor David Bonderman (Jewish) served on the board, and the company received substantial funding from Jewish-led venture capital firms. Dara Khosrowshahi became CEO in 2017. Uber has transformed global transportation, operating in over 10,000 cities across 71 countries, and its Uber Eats platform is one of the largest food delivery services worldwide. The company\'s IPO in 2019 was one of the largest in tech history.');

updDesc('lionsgate-entertainment', 'Film and television studio founded in 1997 in Vancouver by Frank Giustra, with significant Jewish leadership throughout its history. Jon Feltheimer, the Jewish CEO since 2000, transformed Lionsgate from a small independent studio into a major entertainment company. The studio is known for franchises including The Hunger Games, John Wick, Saw, and Twilight. Lionsgate owns the premium cable network Starz and has built one of the most successful independent film libraries in Hollywood. The company has been a launching pad for major Jewish talent and has significant ties to the broader Jewish entertainment industry.');

updDesc('a24-films', 'Independent entertainment company founded in 2012 by Daniel Katz, David Fenkel, and John Hodges, which has become one of the most acclaimed studios in modern cinema. Katz and Fenkel are Jewish. A24 has produced and distributed numerous critically acclaimed and commercially successful films including Moonlight (Best Picture winner), Everything Everywhere All at Once (Best Picture), Lady Bird, Uncut Gems (starring Adam Sandler as a Jewish diamond dealer in NYC), and Ex Machina. The studio has redefined independent film distribution and has developed a cult-like following among cinephiles. A24 also produces television shows including Euphoria.');

updDesc('iheartmedia', 'Largest radio company in the United States, owning over 850 radio stations and the iHeartRadio digital platform. The company was originally Clear Channel Communications, which was taken private in 2008 by Bain Capital and Thomas H. Lee Partners in a $24 billion leveraged buyout—one of the largest in history. Bob Pittman (CEO) oversees the company, which reaches over 250 million monthly listeners. The company\'s Jewish connections include its private equity ownership period and numerous Jewish executives and on-air personalities throughout its history. iHeartMedia produces the iHeartRadio Music Festival and Jingle Ball concert series.');

// === US PHILANTHROPY ===
updDesc('charles-and-lynn-schusterman-family-philanthropies', 'Major Jewish philanthropic foundation established by Charles Schusterman, a Jewish-American oil and gas entrepreneur from Tulsa, Oklahoma, and continued by his wife Stacy and daughter Lynn Schusterman. The foundation has given over $3 billion to Jewish causes, Israel engagement, and education in the United States. It is a primary funder of Birthright Israel, ROI Community, and numerous Jewish campus initiatives. The Schusterman Family Philanthropies has been one of the most transformative forces in modern Jewish philanthropy, particularly in engaging young adults with Jewish identity and Israel. Lynn Schusterman has also been a major supporter of public education reform in Oklahoma.');

updDesc('pritzker-foundation', 'Philanthropic organization of the Pritzker family, one of America\'s wealthiest Jewish dynasties. The Pritzker family, originally from Kyiv, Ukraine, built their fortune through the Hyatt hotel chain and Marmon Group industrial conglomerate. Family members include Illinois Governor J.B. Pritzker, former Commerce Secretary Penny Pritzker, and the late Jay Pritzker who established the Pritzker Architecture Prize (the "Nobel of architecture"). The family\'s philanthropic activities span education, medicine, Jewish causes, and the arts, with major gifts to the University of Chicago, Stanford, and numerous Jewish organizations. Combined family wealth exceeds $30 billion.');

updDesc('wexner-foundation', 'Foundation established by Leslie Wexner, the Jewish-American billionaire founder of L Brands (Victoria\'s Secret, Bath & Body Works). The Wexner Foundation invests in developing professional and volunteer Jewish leadership through its flagship Wexner Graduate Fellowship, Wexner Israel Fellowship, and Wexner Heritage Program, which have trained thousands of Jewish leaders over four decades. Wexner was once the longest-serving CEO of a Fortune 500 company before controversy over his ties to Jeffrey Epstein, who managed Wexner\'s personal finances. The foundation continues its leadership programs and has been influential in shaping the modern American Jewish professional landscape.');

// === US PHARMA, MEDIA, FINANCE ===
updDesc('taro-pharmaceutical-industries-us', 'Specialty pharmaceutical company originally founded in Israel in 1950 by the Levenstein family, now headquartered in Hawthorne, New York. Taro became a subsidiary of Sun Pharmaceutical Industries in 2010 after a protracted acquisition battle. The company specializes in dermatological products, generic pharmaceuticals, and OTC medications, with manufacturing facilities in Israel, the U.S., and Canada. Taro represents a key example of Israeli pharmaceutical innovation expanding into the American market. The company has been involved in price-fixing litigation in the U.S. generic drug industry.');

updDesc('notable-jewish-philanthropists-us', 'Prominent Jewish philanthropists who have shaped American charitable giving and Jewish communal life. This includes figures like Michael Bloomberg ($11.8B in total giving), George Soros (over $32 billion given away through Open Society Foundations), Sheldon Adelson (massive political and Israel-related donations), the Lauder family (cosmetics fortune supporting Jewish heritage), the Marcus family (Home Depot co-founder Bernie Marcus\'s billions for medical research, veterans, and Israel), and Lynn Schusterman (Jewish education and youth engagement). Jewish Americans, who comprise roughly 2% of the U.S. population, are estimated to account for over 25% of total charitable giving in the country.');

updDesc('notable-jewish-media-executives-us', 'Prominent Jewish figures who have led major American media companies and shaped the information landscape. This includes Bob Iger (Disney CEO), Jeff Zucker (CNN president), Jeff Shell (former NBCUniversal CEO), David Zaslav (Warner Bros. Discovery CEO), Shari Redstone (Paramount Global), the Sulzberger family (New York Times owners for generations), the Newhouse family (Condé Nast/Advance Publications), Mort Zuckerman (U.S. News & World Report, New York Daily News), and many others. Jewish leadership in American media has been a subject of both academic study and antisemitic conspiracy theories, though it reflects the community\'s historical emphasis on education, communication, and cultural participation.');

updDesc('loews-corporation', 'Conglomerate controlled by the Tisch family, one of the most prominent Jewish-American business dynasties. Founded by brothers Laurence and Robert (Bob) Tisch, who built a small New Jersey summer camp into a major conglomerate encompassing Lorillard (tobacco), CNA Financial (insurance), Bulova (watches), and Loews Hotels. Laurence Tisch served as chairman of CBS from 1986 to 1995, making the family a major force in American media. Bob Tisch served as U.S. Postmaster General under George H.W. Bush. The Tisch family has been one of the most generous philanthropic families in American Jewish life, with major gifts to NYU (the Tisch School of the Arts), hospitals, and Jewish organizations.');

updDesc('och-ziff-capital-management-sculptor-capital', 'Multi-strategy hedge fund founded in 1994 by Daniel Och, a former Goldman Sachs trader, with backing from the Ziff family (Jewish media dynasty). At its peak, the fund managed over $40 billion in assets. In 2016, the firm paid $412 million to settle SEC and DOJ charges related to bribery of officials in Africa—one of the largest FCPA settlements in history. Daniel Och stepped down, and the firm rebranded as Sculptor Capital Management in 2019 to distance itself from the scandal. Och, despite the controversy, remains a billionaire and a significant donor to Jewish causes and educational institutions.');

updDesc('sac-capital-advisors-point72', 'Hedge fund founded in 1992 by Steven A. Cohen, a Jewish-American billionaire from Great Neck, New York. SAC Capital was one of the most successful hedge funds in history, generating average annual returns of 30% over two decades. In 2013, the firm pleaded guilty to insider trading charges and paid $1.8 billion in penalties—the largest insider trading settlement in history. Cohen was barred from managing outside money until 2018, when he launched Point72 Asset Management. Despite the scandal, Cohen\'s personal fortune exceeds $17 billion. He purchased the New York Mets in 2020 and is a major art collector and philanthropist.');

updDesc('third-point-llc', 'Activist hedge fund founded in 1995 by Daniel Loeb, a Jewish-American investor known for his aggressive shareholder activism and scathing letters to corporate boards. Loeb, who grew up in a Jewish family in Los Angeles, has managed assets exceeding $20 billion and has taken activist positions in major companies including Yahoo, Sony, Nestlé, and Disney. His campaigns have led to significant corporate changes, leadership overhauls, and billions in shareholder value. Loeb is a major philanthropist, particularly in education reform (founding the Success Academy charter school network with Eva Moskowitz) and Jewish and Israel-related causes.');

updDesc('soros-fund-management', 'Family office managing the personal fortune of George Soros, the Jewish-Hungarian-American billionaire investor and philanthropist. Soros, a Holocaust survivor who escaped Nazi-occupied Hungary, built one of the most successful investment track records in history at the Quantum Fund, famously "breaking the Bank of England" in 1992 by shorting the pound sterling and earning $1 billion in a single day. Through Open Society Foundations, he has given away over $32 billion, making him one of the largest donors in history. Soros has been the subject of extensive antisemitic conspiracy theories worldwide. His son Alex Soros now manages the family\'s philanthropic and investment activities.');

// === US MUSIC & PUBLISHING ===
updDesc('atlantic-records', 'Major record label founded in 1947 by Ahmet Ertegun (Turkish, not Jewish) and Herb Abramson (Jewish). Jerry Wexler (Jewish), who joined as a partner in 1953, coined the term "rhythm and blues" and produced landmark recordings by Aretha Franklin, Ray Charles, and Led Zeppelin. Atlantic was instrumental in bringing African-American music to mainstream audiences and was a cornerstone of the civil rights era\'s cultural revolution. Jewish executives including Jerry Greenberg and Craig Kallman (current chairman) have led the label. Atlantic is now part of Warner Music Group, owned by Jewish-Ukrainian-American billionaire Len Blavatnik.');

updDesc('interscope-records', 'Major record label founded in 1990 by Jimmy Iovine and Ted Field, now one of the most powerful labels in hip-hop and popular music. Chairman John Janick, who is Jewish, has led the label since 2012 after co-founding Fueled by Ramen. Under his leadership, Interscope has dominated pop and hip-hop charts with artists including Lady Gaga, Billie Eilish, Kendrick Lamar, and Eminem. The label is part of Universal Music Group and has been instrumental in shaping modern popular music. Interscope\'s early success with Death Row Records (Dr. Dre, Snoop Dogg, Tupac) made it a cultural powerhouse.');

updDesc('warner-music-group', 'One of the "Big Three" major record labels, owned by Access Industries, the conglomerate of Jewish-Ukrainian-American billionaire Len Blavatnik. Blavatnik, born in Soviet Ukraine and educated at Harvard, acquired Warner Music for $3.3 billion in 2011 and took it public again in 2020. Warner Music Group encompasses Atlantic Records, Warner Records, Elektra, and numerous other labels, representing artists from Ed Sheeran to Cardi B. Blavatnik is one of the wealthiest people in the UK and a major philanthropist, donating to Jewish causes, Oxford University (Blavatnik School of Government), and the arts. Warner Music\'s Jewish founding and current ownership reflects decades of Jewish involvement in the music industry.');

updDesc('alfred-a-knopf', 'Prestigious publishing house founded in 1915 by Alfred A. Knopf (Jewish) and his wife Blanche Knopf, known for its distinctive Borzoi imprint. The Knopfs built one of the most respected literary publishers in American history, championing authors including Albert Camus, Langston Hughes, Willa Cather, Gabriel García Márquez, Toni Morrison, and Haruki Murakami. Alfred Knopf brought European and world literature to American audiences and set new standards for book design and production quality. The publisher was acquired by Random House in 1960 and is now part of Penguin Random House. Sonny Mehta served as editor-in-chief from 1987 until his death in 2019, continuing the tradition of literary excellence.');

// === US FILM (HISTORIC FOUNDING) ===
updDesc('warner-bros-pictures-historic-founding', 'Major film studio founded in 1923 by the four Warner brothers—Harry, Albert, Sam, and Jack—Jewish immigrants from Krasnosielc, Poland. The Warners revolutionized cinema by producing The Jazz Singer (1927), starring Al Jolson, the first feature-length "talking picture," which ended the silent film era. The studio became known for gritty, socially conscious films including gangster movies, musicals, and war films. Warner Bros. was also the first studio to explicitly take on Nazi Germany in films like Confessions of a Nazi Spy (1939). Harry Warner was fiercely anti-Nazi and used the studio as a vehicle for anti-fascist messaging. The studio\'s legacy represents the foundational role of Jewish immigrants in creating Hollywood.');

updDesc('paramount-pictures-historic-founding', 'Major film studio founded by Adolph Zukor, a Jewish immigrant from Ricse, Hungary, who arrived in America as an orphan with $25 sewn into his vest. Zukor founded Famous Players Film Company in 1912, which became Paramount Pictures. He pioneered the feature-length film format and the star system, signing Mary Pickford and other early film legends. Jesse L. Lasky (Jewish) co-founded the Jesse L. Lasky Feature Play Company, which merged with Zukor\'s company. Zukor led Paramount for decades, living to age 103. Under Barney Balaban (Jewish), Paramount became one of the most profitable studios. The studio\'s history exemplifies the Jewish immigrant experience in building Hollywood from nothing.');

updDesc('columbia-pictures-historic-founding', 'Major film studio founded in 1924 by Harry Cohn and his brother Jack Cohn, along with Joe Brandt—all Jewish Americans. Harry Cohn ran the studio with an iron fist for over three decades, earning the nickname "King Cohn." Under his leadership, Columbia produced classic films including It Happened One Night (the first film to sweep all five major Academy Awards), Mr. Smith Goes to Washington, and From Here to Eternity. Columbia was unique among the major studios for lacking a theater chain, relying solely on film quality. The studio was acquired by Sony in 1989 for $3.4 billion, marking one of the first major Japanese acquisitions of American entertainment property.');

updDesc('universal-pictures-historic-founding', 'Major film studio founded in 1912 by Carl Laemmle, a Jewish immigrant from Laupheim, Germany, who started by opening one of the first nickelodeons in Chicago. Laemmle created Universal City Studios—the first-ever planned film studio community. He is credited with creating the "star system" by publicizing actress Florence Lawrence\'s name. Laemmle\'s nephew, William Wyler (Jewish), became one of Hollywood\'s greatest directors. Universal pioneered the horror genre with Frankenstein and Dracula. Laemmle famously used affidavits to rescue over 300 Jewish families from Nazi Germany. The studio went through multiple ownership changes and is now part of Comcast\'s NBCUniversal, where Jewish executives have continued to play leadership roles.');

updDesc('20th-century-fox-historic-founding', 'Major film studio born from the merger of William Fox\'s Fox Film Corporation and Twentieth Century Pictures (founded by Joseph Schenck and Darryl Zanuck). William Fox (born Vilmos Fuchs), a Jewish-Hungarian immigrant, pioneered the movie theater chain model and the newsreel. He developed the sound-on-film technology (Movietone) that competed with Warner Bros.\' Vitaphone. Fox lost control of his company during the Great Depression. Darryl Zanuck, while not Jewish himself, was deeply connected to the Jewish film community and ran the studio for decades, producing classics like The Grapes of Wrath, All About Eve, and The Sound of Music. The studio was acquired by Rupert Murdoch\'s News Corporation in 1985 and later by Disney in 2019 for $71.3 billion.');

// === US SPORTS (continued) ===
updDesc('milwaukee-bucks-wes-edens-marc-lasry', 'NBA championship team co-owned by Marc Lasry, a Moroccan-born Jewish-American billionaire who co-founded Avenue Capital Group. Lasry, born in Marrakech to a Sephardic Jewish family, immigrated to the United States and built Avenue Capital into a major credit-focused investment firm managing over $13 billion. Under Lasry and co-owner Wes Edens\' ownership since 2014, the team won the 2021 NBA Championship. Lasry was reportedly considered for U.S. Ambassador to France by President Obama. His children, including daughter Elissa, have also gained public prominence. Lasry\'s story represents the Sephardic Jewish immigrant success narrative in American finance.');

updDesc('atlanta-hawks-tony-ressler', 'NBA franchise owned by Tony Ressler, a Jewish-American billionaire who co-founded Ares Management, one of the world\'s largest alternative investment managers with over $300 billion in assets. Ressler, who is married to actress Jami Gertz (also Jewish), purchased the Hawks in 2015 for $850 million. He has overseen the team\'s move to the renovated State Farm Arena and development of the Centennial Yards mixed-use project around the arena. Ressler previously co-founded Apollo Global Management with Leon Black and Josh Harris, connecting him to a network of Jewish private equity billionaires who collectively own multiple professional sports franchises.');

updDesc('cleveland-cavaliers-dan-gilbert', 'NBA franchise owned by Dan Gilbert, a Jewish-American billionaire who founded Quicken Loans (now Rocket Mortgage), the largest mortgage lender in the United States. Gilbert, from Detroit, has invested over $7 billion in revitalizing downtown Detroit, becoming the city\'s largest property owner. Under his ownership, the Cavaliers won the 2016 NBA Championship with LeBron James. Gilbert suffered a stroke in 2019 but has continued his business activities. He is a major philanthropist, particularly in Detroit\'s Jewish community and broader urban revitalization efforts. His real estate holdings in Detroit encompass over 100 buildings.');

updDesc('boston-celtics-wyc-grousbeck', 'NBA franchise with lead owner Wyc Grousbeck, a Jewish-American private equity executive who led the ownership group that purchased the Celtics in 2002. Under his ownership, the Celtics won the 2008 NBA Championship and the 2024 NBA Championship. Grousbeck, a Harvard Law graduate and former partner at Highland Capital Partners, has been an active and visible owner in a franchise with 17 championships—the most in NBA history. In 2024, Grousbeck announced the planned sale of the Celtics at a valuation expected to exceed $5 billion, which would be the highest price ever paid for an NBA team.');

updDesc('tampa-bay-lightning-jeff-vinik', 'NHL franchise owned by Jeff Vinik, a Jewish-American billionaire investor who purchased the team in 2010. Vinik, who previously managed the Fidelity Magellan Fund and founded Vinik Asset Management, has transformed the Lightning into one of the NHL\'s premier franchises, winning back-to-back Stanley Cup championships in 2020 and 2021. Beyond hockey, Vinik has spearheaded the $3.5 billion Water Street Tampa development project, one of the largest urban redevelopment projects in the southeastern United States. He has been recognized as one of the best owners in professional sports.');

// === US REAL ESTATE & FOOD ===
updDesc('durst-organization', 'Family-owned New York City real estate company founded in 1915 by Joseph Durst, a Jewish immigrant from Austria-Hungary. The Durst family has built and owned some of Manhattan\'s most significant commercial towers, including One World Trade Center (which the Dursts co-developed with the Port Authority) and the Bank of America Tower. The family gained notoriety through Robert Durst, the black sheep of the family who was convicted of murder in 2021. Douglas Durst, who leads the company, has been a pioneer in green building practices. The organization owns or manages over 13 million square feet of prime Manhattan office space valued at billions of dollars.');

updDesc('manischewitz', 'Producer of kosher foods since 1888, best known for matzo and Passover products. Founded by Rabbi Dov Behr Manischewitz, a Lithuanian-Jewish immigrant, in Cincinnati, Ohio. Manischewitz became the largest matzo manufacturer in the world, with its matzo-baking facility in Jersey City producing millions of pounds annually. The brand name has become virtually synonymous with Passover in American culture. The company also produces Manischewitz wine, one of the most recognizable kosher wines despite its reputation as overly sweet. The brand has been sold multiple times and is now owned by the Kayco/Kedem food conglomerate. Manischewitz represents one of America\'s oldest Jewish consumer brands.');

updDesc('sabra-hummus', 'Leading hummus brand in the United States, originally a joint venture between PepsiCo and the Strauss Group, an Israeli food conglomerate. Sabra was founded in 1986 by a Jewish family in Queens, New York, and takes its name from the Hebrew term for a Jewish person born in Israel. The brand controls approximately 60% of the U.S. hummus market, helping transform hummus from an ethnic specialty into a mainstream American snack. Sabra has been a frequent target of BDS (Boycott, Divestment, Sanctions) campaigns due to its Israeli connections, particularly the Strauss Group\'s past support of the IDF. In 2023, PepsiCo acquired full ownership.');

updDesc('nathan-s-famous', 'Iconic hot dog company founded in 1916 by Nathan Handwerker, a Jewish immigrant from Galicia (modern-day Poland), who opened a nickel hot dog stand on Coney Island, Brooklyn. Handwerker, who had worked for Charles Feltman\'s restaurant, undercut Feltman\'s ten-cent hot dog with his five-cent version, using a recipe reportedly seasoned by his wife Ida. Nathan\'s Famous became an American institution, and the annual Nathan\'s Hot Dog Eating Contest on July 4th is one of the most-watched competitive eating events in the world. The company went public in 1993 and now has over 250 restaurants and a major retail division selling products in supermarkets nationwide.');

updDesc('h-agen-dazs', 'Premium ice cream brand founded in 1960 by Reuben and Rose Mattus, Jewish-Polish immigrants in the Bronx, New York. The name "Häagen-Dazs" is entirely fabricated—the Mattuses created a Scandinavian-sounding name to convey an image of Old World craftsmanship and purity, even including a map of Denmark on early packaging. The brand pioneered the super-premium ice cream category, using only the finest natural ingredients. Reuben Mattus was a committed Zionist, and the brand\'s early growth was supported by Jewish community networks. Häagen-Dazs was sold to Pillsbury in 1983 and is now owned by General Mills. The brand generates over $2 billion in annual global sales.');

// Save
fs.writeFileSync(jewishFile, JSON.stringify(data, null, 2));
console.log('addConnections18.js done - US short descriptions expanded');

// Count
let short = 0;
for (const country in data.countries) { for (const e of data.countries[country]) { if (e.description.length < 100) short++; } }
console.log('Remaining short descriptions:', short);
