// addConnections19.js - Expand short descriptions for Israel entries (34) + remaining countries (11)
const fs = require('fs');
const path = require('path');
const jewishFile = path.join(__dirname, '..', 'data', 'jewish.json');
const data = JSON.parse(fs.readFileSync(jewishFile, 'utf8'));
const entryIndex = {};
for (const country in data.countries) { for (const entry of data.countries[country]) { entryIndex[entry.id] = { entry, country }; } }
function updDesc(id, d) { if (entryIndex[id]) entryIndex[id].entry.description = d; }

// === ISRAEL - UNIVERSITIES ===
updDesc('technion-israel-institute-of-technology', 'Israel\'s oldest university, founded in 1912 in Haifa during the Ottoman period, and the country\'s premier science and technology research institution. The Technion has produced three Nobel Prize laureates in chemistry and innumerable tech entrepreneurs. Often called "Israel\'s MIT," the Technion has been instrumental in creating Israel\'s reputation as the "Startup Nation," with alumni founding companies like Waze, Mobileye, and numerous defense technology firms. Albert Einstein was a strong advocate for the institution and served on its first Board of Governors. The campus spans 300 acres on Mount Carmel and maintains research partnerships with top universities worldwide. Technion graduates are estimated to lead over a quarter of Israel\'s high-tech companies and account for a large portion of the nation\'s engineering and scientific workforce.');

updDesc('tel-aviv-university', 'Israel\'s largest university and a major center of teaching and research, founded in 1956 in Tel Aviv. TAU encompasses nine faculties covering arts, sciences, engineering, medicine, and law, with over 30,000 students. The university\'s Blavatnik School of Computer Science and Sackler Faculty of Medicine are world-renowned. TAU has produced five Nobel laureates and numerous leaders in Israeli society, technology, and military. The campus features the Diaspora Museum (ANU), one of the world\'s most important Jewish cultural institutions. TAU has extensive research partnerships with institutions globally and is a leading center for Middle East studies, cybersecurity research, and biotechnology innovation. Its alumni include prominent Israeli politicians, military leaders, and tech entrepreneurs.');

updDesc('ben-gurion-university-of-the-negev', 'Research university in Beersheba founded in 1969, central to the development of Israel\'s Negev desert and its transformation into a thriving tech and scientific hub. Named after David Ben-Gurion, Israel\'s founding prime minister who championed Negev development, the university has become a global leader in desert research, water technology, solar energy, and cybersecurity. BGU\'s Cyber Security Research Center is at the heart of Beersheba\'s emerging "cyber capital" status, housing Israel\'s National Cyber Directorate and tech giants including Deutsche Telekom and PayPal. The university operates the Sede Boqer campus adjacent to Ben-Gurion\'s desert home and burial site, and has established an innovation district attracting multinational companies and military intelligence units.');

updDesc('bar-ilan-university', 'Public research university in Ramat Gan, Israel, founded in 1955 by the American Mizrachi movement to combine secular academic studies with Jewish identity and values. Named after Rabbi Meir Bar-Ilan (Berlin), a leader of Religious Zionism, the university has grown to become Israel\'s second-largest academic institution with over 26,000 students. Bar-Ilan is known for its Responsa Project, the world\'s largest electronic database of Jewish law, and strong programs in brain research (the Gonda Multidisciplinary Brain Research Center), nanotechnology, and criminology. The university has been associated with the religious-Zionist community and has campuses in Safed, Ashkelon, and the Jordan Valley, including a controversial campus in the Ariel settlement in the West Bank.');

// === ISRAEL - TECH ===
updDesc('wix-com', 'Cloud-based web development platform founded in 2006 in Israel by Avishai Abrahami, Nadav Abrahami, and Giora Kaplan. Wix allows users to create professional websites without coding knowledge and has grown to serve over 250 million registered users worldwide. The company went public on NASDAQ in 2013 and is headquartered in Tel Aviv. Wix\'s drag-and-drop website builder democratized web design and has made it one of Israel\'s most recognizable tech brands. The company employs thousands of people in offices across Israel, Ukraine, Lithuania, and other countries, and generates over $1.5 billion in annual revenue. Wix is a prominent example of Israel\'s consumer internet success stories.');

updDesc('cyberark', 'Information security company specializing in privileged access management (PAM), founded in 1999 in Petah Tikva, Israel, by Udi Mokady. CyberArk is a global leader in identity security, protecting organizations against cyber attacks that target privileged credentials. The company went public on NASDAQ in 2014 and has grown to a market capitalization exceeding $10 billion. CyberArk counts over half of the Fortune 500 as customers and has been at the forefront of defending against some of the most significant cyber attacks in history, including the SolarWinds breach. The company emerged from Israel\'s renowned cybersecurity ecosystem, with many employees having backgrounds in IDF intelligence units including Unit 8200.');

updDesc('elbit-systems', 'International defense electronics company headquartered in Haifa, Israel, and one of the world\'s largest defense technology companies. Elbit develops and supplies a broad portfolio of airborne, land, and naval systems and homeland security products including drones (UAVs), electro-optic systems, electronic warfare suites, signals intelligence, and military aircraft avionics. The company has been a key supplier to the Israel Defense Forces and exports to militaries worldwide, including the United States, where it operates through its subsidiary Elbit Systems of America. Elbit has been a frequent target of BDS campaigns and pro-Palestinian protests for its role in supplying surveillance and military technology used in the West Bank and Gaza. Revenue exceeds $5.5 billion annually.');

updDesc('rafael-advanced-defense-systems', 'Israeli defense technology company and developer of the Iron Dome missile defense system, one of the most successful military technologies in modern history. Founded in 1948 as part of the Israel Ministry of Defense, RAFAEL (originally an acronym for "Armament Development Authority") was corporatized in 2002. Iron Dome, developed with significant U.S. funding, has intercepted thousands of rockets fired at Israeli population centers. RAFAEL also produces the Trophy active protection system for tanks, Spike anti-tank missiles (exported to over 30 countries), and advanced guided munitions. The company employs over 8,000 people, primarily scientists and engineers, and generates over $3 billion in annual revenue. RAFAEL represents the cutting edge of Israeli defense innovation.');

updDesc('monday-com', 'Cloud-based work management platform founded in 2012 in Tel Aviv by Roy Mann and Eran Zinman. Originally called dapulse, Monday.com provides project management, workflow automation, and team collaboration tools used by over 186,000 organizations including Coca-Cola, NBC Universal, and Canva. The company went public on NASDAQ in 2021 at a valuation of over $7 billion. Monday.com represents Israel\'s growing success in enterprise SaaS (Software as a Service) and has become one of the country\'s most valuable tech companies. The platform competes with Asana, Trello, and Jira in the rapidly growing work management software market.');

updDesc('playtika', 'Mobile gaming entertainment company founded in 2010 in Israel by Robert Antokol and Uri Shahak. Playtika pioneered the use of data science and AI to optimize casual mobile gaming experiences, operating hit games including Slotomania, Bingo Blitz, and Caesars Slots. The company was acquired by a Chinese consortium led by Giant Interactive for $4.4 billion in 2016, one of the largest acquisitions of an Israeli company. Playtika went public on NASDAQ in 2021, valuing the company at over $11 billion. With over 4,000 employees in offices across Israel, Ukraine, Belarus, and other countries, Playtika is one of the largest gaming companies to emerge from Israel.');

updDesc('bank-hapoalim', 'Israel\'s largest bank by assets, founded in 1921 during the British Mandate period by the Histadrut labor federation. The name means "The Workers\' Bank" in Hebrew, reflecting its origins in the labor Zionist movement. Bank Hapoalim has been central to Israel\'s economic development from pre-state infrastructure building through modern high-tech growth. The bank operates over 200 branches in Israel and has international subsidiaries. In 2020, Bank Hapoalim paid $874 million to U.S. authorities to settle charges of helping American clients evade taxes,one of the largest such penalties ever. The bank manages assets exceeding $100 billion and is listed on the Tel Aviv Stock Exchange.');

updDesc('israel-discount-bank', 'Third largest banking group in Israel, founded in 1935 by Leon Recanati, a Sephardic Jewish banker from Thessaloniki, Greece. The Recanati family, prominent in Mediterranean Jewish banking circles, established the bank during the British Mandate to serve the growing Jewish community in Palestine. Israel Discount Bank operates over 150 branches in Israel and subsidiaries in the United States, United Kingdom, and Latin America. The bank has been at the center of Israeli financial life for nearly a century and has been involved in major national economic events, including the 1983 bank stocks crisis. The Recanati family\'s legacy extends beyond banking into philanthropy, art, and Israeli cultural life.');

// === ISRAEL - FOOD & MEDIA ===
updDesc('strauss-group', 'One of Israel\'s largest food and beverage companies, founded in 1933 by Richard and Hilda Strauss as a small dairy farm in Nahariya. The Strauss family built the company into a multinational conglomerate with revenues exceeding $2 billion, operating across Israel, Brazil, and other markets. Strauss owns major brands including Sabra Hummus (in partnership with PepsiCo), Elite coffee, and Obela dips. Ofra Strauss, granddaughter of the founders, chairs the company and is one of Israel\'s most prominent businesswomen. The Strauss Group has faced BDS boycott campaigns due to its past support of the IDF Golani Brigade, which it discontinued in 2014.');

updDesc('tnuva', 'Israel\'s largest food manufacturer and dairy company, controlling approximately 70% of the Israeli dairy market. Founded in 1926 as a cooperative by Jewish agricultural settlements during the British Mandate, Tnuva was the flagship enterprise of the kibbutz and moshav movements and became synonymous with Israeli food culture. The company was controversially privatized and sold to the Chinese Bright Food Group in 2014 for $2.5 billion, sparking a national debate about foreign ownership of strategic Israeli assets. Tnuva produces milk, cheese, yogurt, and other dairy and food products that are staples of the Israeli diet. The brand name has become a generic term for dairy products in Israeli Hebrew.');

updDesc('the-jerusalem-post', 'English-language Israeli newspaper founded in 1932 as the Palestine Post during the British Mandate. The paper covered the founding of the State of Israel and is one of the most widely read English-language sources for news about Israel and the Middle East. Originally centrist, the Jerusalem Post shifted to the right under the ownership of Hollinger International (Conrad Black) in the 1980s and the current ownership of Eli Azur. The paper\'s editors have included legendary figures like Gershon Agron and Ted Lurie. The Jerusalem Post has been a critical link connecting the English-speaking Jewish diaspora with events in Israel and has influenced international perceptions of the Israeli-Palestinian conflict for over nine decades.');

updDesc('yedioth-ahronoth', 'One of Israel\'s most widely read daily newspapers, founded in 1939, with the name meaning "Latest News" in Hebrew. Owned by the Moses family (Arnon "Noni" Mozes), Yedioth Ahronoth has been at the center of Israeli media and political life for decades. The paper\'s editorial stance is generally centrist to center-left, and its Ynet news website is one of Israel\'s most visited. The paper was central to the corruption trial of Prime Minister Benjamin Netanyahu, who was charged with media bribery,allegedly offering regulatory favors to Mozes in exchange for favorable coverage. Yedioth Ahronoth\'s rivalry with Israel Hayom (Sheldon Adelson\'s free daily) has shaped Israeli media dynamics in the 21st century.');

updDesc('i24news', 'International 24-hour multilingual news and current affairs television channel based in Tel Aviv and Jaffa, Israel. Founded in 2013 by French-Israeli businessman Patrick Drahi (a Sephardic Jew born in Morocco), i24NEWS broadcasts in English, French, and Arabic, aiming to present Israeli and Middle Eastern perspectives to a global audience. The channel is available in over 150 million households worldwide, including on major U.S. cable systems. Drahi, who also controls Altice (a global telecoms and media conglomerate), invested heavily in creating a CNN-style international news operation from Israel. The channel has been praised for providing diverse voices and criticized as a soft-power tool for the Israeli government.');

updDesc('israel-museum', 'Israel\'s national museum located in Jerusalem, housing the Dead Sea Scrolls in the iconic Shrine of the Book. Founded in 1965, the museum holds nearly 500,000 objects spanning 5,000 years of art and archaeology, from prehistoric artifacts to contemporary art. The Shrine of the Book, with its distinctive white dome, contains the oldest known biblical manuscripts. The museum\'s collections include Judaica, ethnography, Israeli art, and European masters. The campus features the Billy Rose Art Garden designed by Isamu Noguchi and a model of ancient Jerusalem. The Israel Museum is one of the leading archaeological and art museums in the world, attracting over 800,000 visitors annually and serving as a key institution in Israeli cultural identity.');

updDesc('habima-national-theatre', 'Israel\'s national theater, founded in 1917 in Moscow by Nahum Zemach as a Hebrew-language theater company during a time when Hebrew was barely a spoken language. Habima (meaning "The Stage" in Hebrew) operated under the patronage of the Moscow Art Theater\'s Stanislavsky before relocating to Palestine in 1928. The theater played a crucial role in the revival of the Hebrew language and Israeli cultural identity. Its 1922 production of The Dybbuk, directed by Yevgeny Vakhtangov, is considered one of the most important theatrical productions of the 20th century. Habima received national theater status in 1958 and performs in its modernist Tel Aviv home on Habima Square, one of the cultural hearts of the city.');

updDesc('jewish-agency-for-israel', 'Organization founded in 1929 responsible for facilitating Jewish immigration (aliyah) to Israel and supporting absorption of new immigrants. The Jewish Agency was instrumental in establishing the State of Israel, functioning as a quasi-governmental body in pre-state Palestine under the leadership of David Ben-Gurion and Chaim Weizmann. After 1948, the agency continued to manage global Jewish immigration, bringing millions of Jews from Europe, the Middle East, North Africa, Ethiopia, and the former Soviet Union to Israel. The organization operates in over 80 countries, running programs including Birthright Israel, Masa Israel Journey, and various educational initiatives. Recent chairman Isaac Herzog left to become Israel\'s 11th president in 2021.');

// === ISRAEL - TECH (continued) ===
updDesc('sentinelone', 'AI-powered cybersecurity company founded in 2013 in Israel by Tomer Weingarten and Almog Cohen. SentinelOne pioneered the use of artificial intelligence and machine learning for autonomous endpoint protection, replacing traditional antivirus with proactive threat detection and response. The company went public on NYSE in 2021 at a valuation exceeding $10 billion, one of the largest cybersecurity IPOs in history. SentinelOne counts Fortune 500 companies and government agencies among its customers and competes with CrowdStrike and traditional security vendors. The company exemplifies Israel\'s emergence as a global cybersecurity powerhouse, a sector in which Israel commands roughly 10% of the global market.');

updDesc('snyk', 'Developer security platform founded in 2015 in Israel by Guy Podjarny and was later headquartered in Boston, focusing on finding and fixing vulnerabilities in open-source code, containers, and infrastructure. Snyk has grown rapidly to become one of the most valued cybersecurity companies in the world, reaching a valuation of $8.5 billion in 2022. The platform is used by millions of developers at companies including Google, Salesforce, and ASOS. Snyk represents Israel\'s growing influence in DevSecOps (development security operations) and the shift-left security movement, which integrates security into the software development process rather than treating it as an afterthought.');

updDesc('jfrog', 'Software company founded in 2008 in Netanya, Israel, by Shlomi Ben Haim, Yoav Landman, and Frederic Simon, providing tools for DevOps and continuous software delivery. JFrog\'s Artifactory is one of the most widely used binary repository managers in the world, deployed by most Fortune 100 companies. The company went public on NASDAQ in 2020, achieving a market cap exceeding $6 billion. JFrog\'s platform manages the software supply chain from development through production, a critical function in modern software delivery. The company is a key player in Israel\'s enterprise software ecosystem and has expanded globally with offices in the U.S., Europe, and India.');

updDesc('payoneer', 'Financial services company founded in 2005 in Israel by Yuval Tal, providing online money transfer and digital payment services. Payoneer enables businesses and professionals worldwide to receive cross-border payments, serving over 5 million customers in 190 countries. The company went public through a SPAC merger on NASDAQ in 2021 at a valuation of $3.3 billion. Payoneer has been particularly important for freelancers and small businesses in developing countries, enabling them to participate in the global digital economy. The company competes with PayPal, Wise, and other fintech platforms, and is a prime example of Israeli fintech innovation.');

updDesc('taboola', 'Content discovery and native advertising platform founded in 2007 in Israel by Adam Singolda. Taboola\'s recommendation widgets ("You May Also Like" and "Recommended For You") appear on thousands of publisher websites worldwide, including NBC News, Bloomberg, and Business Insider, reaching approximately 500 million daily active users. The company went public on NASDAQ in 2021 through a SPAC merger. Taboola competes primarily with Outbrain (also Israeli-founded) and together they dominate the content recommendation market. The platform has been both praised for helping publishers monetize their content and criticized for sometimes surfacing clickbait and low-quality content.');

updDesc('outbrain', 'Web recommendation platform founded in 2006 in Israel by Yaron Galai and Ori Lahav. Outbrain powers content recommendations on premium publisher websites worldwide, helping media companies monetize their audiences through native advertising. The company went public on NASDAQ in 2021 and processes over 10 billion content recommendations daily across sites like CNN, Le Monde, Der Spiegel, and The Washington Post. Outbrain and Taboola (its Israeli-founded competitor) attempted a $250 million merger in 2019 that was ultimately abandoned. Galai, the CEO, previously co-founded Quigo (acquired by AOL), making Outbrain his second major ad-tech success. The company operates from offices in New York, Israel, and globally.');

updDesc('cellebrite', 'Provider of digital intelligence solutions for law enforcement and intelligence agencies, founded in 1999 in Petah Tikva, Israel. Cellebrite is best known for its Universal Forensic Extraction Device (UFED), which can extract data from locked mobile phones,a capability that has made it both essential to criminal investigations and controversial for civil liberties implications. The FBI reportedly used Cellebrite technology to unlock the San Bernardino shooter\'s iPhone in 2016. The company sells to law enforcement in over 150 countries, raising concerns about use by authoritarian regimes. Cellebrite went public on NASDAQ in 2021 through a SPAC merger. The company represents Israel\'s complex position at the intersection of security technology and human rights debates.');

updDesc('nice-systems', 'Cloud and on-premises enterprise software solutions company founded in 1986 in Ra\'anana, Israel. NICE (originally an acronym for Neptune Intelligence Computer Engineering) has grown from a provider of telephone recording systems into a global leader in customer engagement, financial crime compliance, and public safety software. The company\'s cloud platform, CXone, is one of the leading contact center solutions worldwide. NICE\'s compliance solutions are used by major financial institutions to detect fraud and money laundering. The company has over 8,000 employees and generates revenue exceeding $2 billion annually. NICE has made numerous acquisitions, including inContact and Nexidia, to build its cloud and analytics capabilities.');

updDesc('amdocs', 'Software and services provider founded in 1982 originally as Aurec Information and Technology, supporting the Israeli telephone directory. Amdocs has grown into a global IT company serving communications, media, and financial services providers, with over 30,000 employees worldwide. The company designs, builds, and manages the business support systems for major telecom operators including AT&T, T-Mobile, and Vodafone. Amdocs has been at the center of conspiracy theories alleging Israeli surveillance of U.S. telecommunications,claims that have been investigated and found unsubstantiated. The company generates over $4.5 billion in annual revenue and is listed on NASDAQ. Amdocs is a prime example of Israeli enterprise technology scaling globally.');

updDesc('unit-8200', 'Israel Defense Forces\' premier signals intelligence (SIGINT) unit, equivalent to the U.S. National Security Agency (NSA). Unit 8200 is known as the world\'s most prolific tech startup incubator, with alumni founding companies including Check Point, Waze, NSO Group, CyberArk, and hundreds of other firms. The unit recruits Israel\'s most talented young people (ages 18-21) at conscription and trains them in advanced cybersecurity, data analysis, and intelligence gathering. Unit 8200\'s surveillance capabilities against Palestinian communications have made it controversial, with 43 veterans signing a public refusal letter in 2014 citing moral concerns. The unit\'s influence on Israel\'s $20+ billion tech sector is so significant that "8200 alumni" has become a shorthand for tech talent in the Israeli innovation ecosystem.');

// === ISRAEL - BUSINESS ===
updDesc('delek-group', 'Israeli conglomerate with major interests in energy, infrastructure, and financial services, controlled by the Tshuva family. Yitzhak Tshuva, a Libyan-born Jewish-Israeli billionaire, built Delek from a small gas station business into an empire. The group was instrumental in developing Israel\'s Leviathan and Tamar offshore natural gas fields,transformative discoveries that have made Israel energy-independent and a gas exporter. These fields, holding hundreds of billions of cubic meters of gas, have reshaped Israel\'s economy and geopolitical position, enabling energy diplomacy with Egypt, Jordan, and potentially Europe. The Tshuva family also owns significant real estate in New York City and Israel.');

updDesc('azrieli-group', 'Major Israeli real estate and holding company, one of the country\'s largest, founded by David Azrieli, a Polish-born Holocaust survivor who emigrated to Canada before building his business empire in Israel. Azrieli\'s signature developments include the Azrieli Center towers in Tel Aviv,three iconic skyscrapers that have become symbols of Israel\'s modern economy. The Azrieli Group\'s portfolio spans shopping malls, office towers, residential projects, and senior housing throughout Israel. After Azrieli\'s death in 2014, the company is managed by his daughter Danna Azrieli. The Azrieli Foundation is one of the largest philanthropic organizations in Canada and Israel, supporting education, architecture, and scientific research.');

updDesc('africa-israel-investments', 'Israeli conglomerate with real estate, construction, and infrastructure interests, controlled by Lev Leviev, a Bukharan-Jewish billionaire born in Tashkent, Uzbekistan. Leviev, known as the "King of Diamonds," built a diamond empire that challenged De Beers\' monopoly and expanded into massive real estate developments in Israel, the U.S., Russia, and Africa. Africa-Israel developed large-scale projects including the New York Times Building in Manhattan. Leviev has been controversial for his companies\' construction in Israeli settlements in the West Bank, leading to international boycott campaigns. His Chabad background and philanthropy have made him a prominent figure in the global Jewish community, particularly among Bukharan Jews.');

updDesc('solaredge-technologies', 'Israeli smart energy technology company founded in 2006, pioneering the development of DC-optimized inverter systems for solar photovoltaic installations. SolarEdge went public on NASDAQ in 2015 and grew to become one of the world\'s leading solar energy companies with a market capitalization that peaked at over $18 billion. The company\'s technology optimizes the power output of individual solar panels and provides monitoring and safety features. SolarEdge has expanded into energy storage, EV charging, and smart energy management. Founded by Israeli engineers Guy Sella (who passed away in 2020), Lior Handelsman, and Yoav Galin, SolarEdge represents Israel\'s significant contributions to renewable energy technology.');

// === UNITED KINGDOM (3) ===
updDesc('board-of-deputies-of-british-jews', 'The main representative organization of British Jews, founded in 1760, making it one of the oldest Jewish communal organizations in the world. The Board of Deputies represents over 300 synagogues and communal organizations across the UK and serves as the primary interface between the Jewish community and the British government. The organization has played a role in nearly every major event in British Jewish history, from the Aliens Act of 1905 to combating modern antisemitism. Recent presidents including Marie van der Zyl have been vocal on issues ranging from Labour Party antisemitism to the Israel-Palestine conflict. The Board traces its origins to the Sephardic community that settled in England after Oliver Cromwell readmitted Jews in 1656.');

updDesc('community-security-trust-cst', 'Charity providing security, advice, and assistance to the British Jewish community and monitoring antisemitism in the UK. Founded in 1994, CST is unique globally as a Jewish communal security organization that works closely with police and government while being independently run by volunteers and professionals. CST provides trained volunteer security guards for synagogues, Jewish schools, and communal events across the UK. The organization publishes annual antisemitic incident reports that are the authoritative measure of anti-Jewish hate in Britain, recording over 4,000 incidents in 2023,the highest-ever figure. CST has become a model for Jewish community security worldwide and collaborates with international partners including the ADL and Israeli security services.');

updDesc('marks-spencer', 'Major British multinational retailer founded in 1884 by Michael Marks, a Polish-Jewish immigrant from Slonim (modern-day Belarus), who began with a market stall in Leeds using the slogan "Don\'t Ask the Price, It\'s a Penny." Tom Spencer, his partner, was not Jewish, but the company\'s Jewish heritage has defined its identity. Marcus Sieff and other members of the founding family led the company for decades and were deeply involved in the Zionist movement,Sieff was president of the World Zionist Organization. M&S became a quintessentially British institution, known for quality food and clothing, with over 1,000 stores worldwide. The company has been targeted by BDS boycotts due to the founding family\'s Zionist connections, despite being a publicly traded company.');

// === FRANCE (2) ===
updDesc('publicis-groupe', 'Third-largest communications group worldwide, founded in 1926 by Marcel Bleustein-Blanchet, a French Jew who is considered the father of French advertising. Bleustein-Blanchet, who fought in the French Resistance during World War II, built Publicis from a single agency into a global empire now led by his granddaughter\'s husband Arthur Sadoun. The group, headquartered in Paris, encompasses agencies including Saatchi & Saatchi, Leo Burnett, Sapient, and Epsilon, employing over 100,000 people in 100+ countries. Under Maurice Lévy (Jewish), who served as CEO for over 30 years, Publicis became a digital-first conglomerate and one of the most powerful forces in global advertising. The company generates over €13 billion in annual revenue.');

updDesc('grand-synagogue-of-paris-la-victoire', 'Largest synagogue in France, located on Rue de la Victoire in the 9th arrondissement of Paris, built in 1874 in a grand Romanesque Revival style. The synagogue, officially the Synagogue de la Victoire, seats over 1,800 worshippers and serves as the seat of the Chief Rabbi of Paris. It is the flagship of the Consistoire Israélite de Paris, the official body governing Jewish religious life in France since Napoleon\'s establishment of the Consistorial system in 1808. The synagogue has witnessed key moments in French Jewish history, including communal gatherings after the Dreyfus Affair, wartime resistance activities during the Holocaust, and memorials for victims of French antisemitic attacks. The building is an architectural landmark that symbolizes the integration and prominence of Jews in French society since emancipation.');

// === CANADA (2) ===
updDesc('indigo-books-music', 'Largest bookstore chain in Canada, founded in 1996 by Heather Reisman, a prominent Jewish-Canadian businesswoman and philanthropist. Reisman, who is married to Gerry Schwartz (CEO of Onex Corporation and one of Canada\'s wealthiest businesspeople), built Indigo into the dominant book retailer in Canada after acquiring rival Chapters in 2001. The company operates over 160 stores across Canada. Reisman is also a co-founder of HESEG Foundation, which provides scholarships to lone soldiers (immigrants without family) who serve in the Israel Defense Forces. This philanthropic activity has made Indigo the target of BDS campaigns in Canada. The Reisman-Schwartz family is one of the most influential Jewish couples in Canadian business and philanthropy.');

updDesc('onex-corporation', 'Canadian private equity firm founded in 1984 by Gerry Schwartz, one of the most prominent Jewish-Canadian businessmen. Schwartz, who studied at the Harvard Business School and worked at Bear Stearns, built Onex into one of the largest private equity firms in Canada with over $50 billion in assets under management. Onex has made major acquisitions across industries including healthcare, electronics manufacturing (Celestica), food services (WestJet Airlines), and financial services. Schwartz has been a significant political donor and is married to Heather Reisman (founder of Indigo Books). The couple is among the most prominent Jewish philanthropists in Canada, supporting Israel, education, and cultural causes. Schwartz retired as CEO in 2023 after nearly four decades.');

// === RUSSIA (1) ===
updDesc('letterone-mikhail-fridman', 'International investment business founded by Mikhail Fridman, a Jewish-Ukrainian-born billionaire who became one of Russia\'s most powerful oligarchs. Fridman co-founded Alfa Group, one of the largest privately owned financial-industrial conglomerates in Russia, encompassing Alfa-Bank (Russia\'s largest private bank), telecommunications (VimpelCom/Veon), and oil (TNK-BP, which was sold to Rosneft for $28 billion in 2013). Fridman established LetterOne in Luxembourg in 2013 to manage international investments after the TNK-BP sale. Following Russia\'s invasion of Ukraine in 2022, Fridman was sanctioned by the EU and UK, freezing billions in assets. Fridman has been a significant figure in the Jewish community, supporting Jewish causes and the Genesis Prize Foundation.');

// === SOUTH AFRICA (1) ===
updDesc('naspers', 'South African multinational conglomerate and one of the largest technology investors in the world. Founded in 1915 by the Afrikaner establishment, Naspers transformed into a global tech investment powerhouse under the leadership of Koos Bekker, who made the legendary $34 million investment in Tencent in 2001,now worth over $100 billion, making it one of the most successful venture investments in history. While not a Jewish-founded company, Naspers has significant Jewish connections through its executive leadership and investor base in South Africa\'s historically Jewish-influenced business community. The company spun off its international assets into Prosus in 2019 and has invested in companies across Africa, India, Eastern Europe, and Latin America.');

// === SWITZERLAND (1) ===
updDesc('world-health-organization-israeli-connections', 'Israel\'s significant contributions to global health through partnerships with the World Health Organization and international health institutions. Israeli medical innovations adopted by WHO include emergency trauma protocols developed from treating conflict casualties, mobile field hospital expertise (IDF field hospitals were deployed in Haiti, Nepal, and other disaster zones), and pharmaceutical breakthroughs. Israeli researchers have contributed to global disease eradication efforts, cancer research, and medical technology that saves lives worldwide. The Hadassah Medical Center in Jerusalem and Sheba Medical Center in Tel Hashomer regularly collaborate with WHO on pandemic preparedness, infectious disease research, and medical training for developing nations. Israel was among the first countries to sequence COVID-19 variants during the pandemic.');

// === TURKEY (1) ===
updDesc('turkish-jewish-community', 'Sephardic Jewish community descended primarily from Jews expelled from Spain and Portugal in 1492, who were welcomed into the Ottoman Empire by Sultan Bayezid II. The community once numbered over 100,000 and played a significant role in Ottoman commerce, diplomacy, and culture. Istanbul\'s Neve Shalom Synagogue, which has been the target of multiple terrorist attacks (1986, 2003), serves as the community\'s main house of worship. Turkish Jews preserved Ladino (Judeo-Spanish) for centuries, maintaining a unique linguistic and cultural heritage. Today approximately 15,000-20,000 Jews remain, centered in Istanbul and Izmir. Despite Turkey\'s increasingly strained relations with Israel under President Erdogan, the community has maintained a delicate balance between Turkish patriotism and Jewish identity. The Quincentennial Foundation celebrated the community\'s 500th anniversary in 1992.');

// Save
fs.writeFileSync(jewishFile, JSON.stringify(data, null, 2));
console.log('addConnections19.js done - Israel + remaining short descriptions expanded');

// Count
let short = 0;
for (const country in data.countries) { for (const e of data.countries[country]) { if (e.description.length < 100) short++; } }
console.log('Remaining short descriptions:', short);
