/**
 * addWebsites2.js , More comprehensive website enrichment.
 * Uses known mappings + pattern-based generation for remaining entries.
 * Run: node scripts/addWebsites2.js
 */
const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'data', 'jewish.json');
const jd = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const knownWebsites = {
  'urj-camp-newman-camp-george': 'https://www.urjcamps.org',
  'forest-city-realty-brookfield': 'https://www.brookfield.com',
  'museum-jewish-heritage': 'https://mjhnyc.org',
  'national-museum-american-jewish-history': 'https://www.nmajh.org',
  'zionist-organization-america': 'https://zoa.org',
  'orthodox-union': 'https://www.ou.org',
  'reconstructionist-movement': 'https://www.reconstructingjudaism.org',
  'discount-investment-corporation': 'https://www.dic.co.il',
  'idb-holdings': 'https://www.idb.co.il',
  'candiru-saito-tech': 'https://en.wikipedia.org/wiki/Candiru_(spyware_company)',
  'israel-military-industries-imi-systems': 'https://www.imisystems.com',
  'mossad-institute-for-intelligence-and-special-operations': 'https://www.mossad.gov.il',
  'shin-bet-israel-security-agency': 'https://www.shabak.gov.il',
  'talpiot-program': 'https://en.wikipedia.org/wiki/Talpiot_program',
  'unit-8200': 'https://en.wikipedia.org/wiki/Unit_8200',
  'galei-zahal-idf-radio': 'https://www.glz.co.il',
  'israel-airports-authority': 'https://www.iaa.gov.il',
  'israel-lands-authority': 'https://land.gov.il',
  'israel-tax-authority': 'https://www.gov.il/en/departments/israel_tax_authority',
  'masada-national-park': 'https://www.parks.org.il',
  'start-up-nation-ecosystem': 'https://www.startupnationcentral.org',
  'startup-nation-central': 'https://www.startupnationcentral.org',
  'habana-labs-intel': 'https://www.habana.ai',
  'mellanox-technologies-nvidia': 'https://www.nvidia.com/en-us/networking/',
  'orbotech-kla': 'https://www.kla.com',
  'knesset': 'https://www.knesset.gov.il',
  'israel-supreme-court': 'https://supreme.court.gov.il',
  'kindertransport-association-uk': 'https://www.kindertransport.org',
  'arcadia-group-topshop-philip-green': 'https://en.wikipedia.org/wiki/Arcadia_Group',
  'keren-hayesod-france': 'https://www.kerenhayesod.fr',
  'grand-synagogue-of-paris-la-victoire': 'https://www.lavictoire.org',
  'synagogue-de-la-victoire-paris': 'https://www.lavictoire.org',
  'bronfman-family-seagram-company': 'https://en.wikipedia.org/wiki/Seagram',
  'reichmann-family-olympia-york': 'https://en.wikipedia.org/wiki/Olympia_%26_York',
  'sachsenhausen-memorial': 'https://www.sachsenhausen-sbg.de',
  'neue-synagoge-berlin': 'https://www.centrumjudaicum.de',
  'leo-baeck-institute-germany': 'https://www.lbi.org',
  'moses-mendelssohn-center-for-european-jewish-studies': 'https://www.mmz-potsdam.de',
  'russian-jewish-congress': 'https://www.rjc.ru',
  'federation-of-jewish-communities-of-russia-fjcr': 'https://www.fjc.ru',
  'moscow-choral-synagogue': 'https://en.wikipedia.org/wiki/Moscow_Choral_Synagogue',
  'grand-choral-synagogue-st-petersburg': 'https://en.wikipedia.org/wiki/Grand_Choral_Synagogue',
  'buenos-aires-jewish-museum': 'https://www.museojudio.org.ar',
  'seminario-rab-nico-latinoamericano': 'https://www.seminariorabinico.org',
  'museu-judaico-de-s-o-paulo': 'https://www.museujudaico.org.br',
  'congrega-o-israelita-paulista-cip': 'https://www.cfrj.com.br',
  'doh-ny-street-synagogue-budapest': 'https://www.dohanyutcaizsinagoga.hu',
  'federation-of-hungarian-jewish-communities-mazsihisz': 'https://www.mazsihisz.hu',
  'stadttempel-vienna-city-temple': 'https://www.ikg-wien.at',
  'antwerp-diamond-district': 'https://www.awdc.be',
  'museum-of-the-history-of-polish-jews-polin-additional-programs': 'https://www.polin.pl',
  'treblinka-memorial': 'https://www.treblinka-muzeum.eu',
  'warsaw-ghetto-memorial': 'https://www.polin.pl/en/warsaw-ghetto-museum',
  'old-jewish-cemetery-prague': 'https://www.jewishmuseum.cz',
  'pinkas-synagogue-prague-holocaust-memorial': 'https://www.jewishmuseum.cz',
  'federation-of-jewish-communities-in-the-czech-republic': 'https://www.fzo.cz',
  'menorah-center-dnipro': 'https://www.menorah.com.ua',
  'united-jewish-community-of-ukraine': 'https://www.vaadua.org',
  'jewish-confederation-of-ukraine': 'https://www.vaadua.org',
  'neve-shalom-synagogue-istanbul': 'https://en.wikipedia.org/wiki/Neve_Shalom_Synagogue',
  'museum-of-moroccan-judaism-casablanca': 'https://en.wikipedia.org/wiki/Museum_of_Moroccan_Judaism',
  'council-of-jewish-communities-of-morocco': 'https://www.ccm.org.ma',
  'ohel-rachel-synagogue-shanghai': 'https://en.wikipedia.org/wiki/Ohel_Rachel_Synagogue',
  'shanghai-jewish-refugees-museum': 'https://www.shanghaijews.org.cn',
  'sugihara-museum-yaotsu': 'https://www.sugihara-museum.jp',
  'great-synagogue-of-stockholm': 'https://www.stockholmssynagoga.se',
  'official-council-of-swedish-jewish-communities': 'https://www.judiskaforsamlingen.se',
  'danish-jewish-museum-copenhagen': 'https://www.jewmus.dk',
  'great-synagogue-of-copenhagen': 'https://en.wikipedia.org/wiki/Great_Synagogue_(Copenhagen)',
  'jewish-museum-of-greece': 'https://www.jewishmuseum.gr',
  'jewish-museum-of-thessaloniki': 'https://www.jmth.gr',
  'central-board-of-jewish-communities-in-greece': 'https://www.kis.gr',
  'federation-of-jewish-communities-in-romania': 'https://www.fcer.ro',
  'ohel-leah-synagogue': 'https://www.oheleahsynagogue.org',
  'mikv-israel-emanuel-synagogue': 'https://www.snoa.com',
  'abrahamic-family-house-abu-dhabi': 'https://www.forhumanfraternity.org',
  'museu-judaico-de-belmonte': 'https://www.museujudaicobelmonte.org',
  'el-ghriba-synagogue-djerba': 'https://en.wikipedia.org/wiki/El_Ghriba_synagogue',
  'international-march-of-the-living': 'https://www.motl.org',
  'ben-ezra-synagogue-cairo': 'https://en.wikipedia.org/wiki/Ben_Ezra_Synagogue',
  'musmeah-yeshua-synagogue-yangon': 'https://en.wikipedia.org/wiki/Musmeah_Yeshua_Synagogue',
  'paradesi-synagogue-kochi': 'https://en.wikipedia.org/wiki/Paradesi_Synagogue',
  'knesset-eliyahoo-synagogue-mumbai': 'https://en.wikipedia.org/wiki/Knesset_Eliyahoo',
  'venice-ghetto': 'https://en.wikipedia.org/wiki/Venetian_Ghetto',
  'great-synagogue-of-rome': 'https://www.museoebraico.roma.it',
  'c-rdoba-synagogue': 'https://en.wikipedia.org/wiki/Synagogue_of_C%C3%B3rdoba',
  'shoes-on-the-danube-bank': 'https://en.wikipedia.org/wiki/Shoes_on_the_Danube_Bank',
  'raoul-wallenberg-memorial': 'https://www.raoulwallenberg.net',
  'jewish-community-of-gibraltar': 'https://en.wikipedia.org/wiki/History_of_the_Jews_in_Gibraltar',
  'jewish-community-of-taipei': 'https://www.jewish.org.tw',
  'jewish-community-of-taiwan': 'https://www.jewish.org.tw',
  'new-zealand-jewish-council': 'https://www.nzjc.nz',
  'shoah-foundation': 'https://sfi.usc.edu',
  'biontech-pfizer-israel-partnership': 'https://www.biontech.com',
  'israelitische-kultusgemeinde-wien': 'https://www.ikg-wien.at',
  'world-ort': 'https://www.ort.org',
  'jewish-museum-of-australia': 'https://www.jewishmuseum.com.au',
  'executive-council-of-australian-jewry': 'https://www.ecaj.org.au',
  'zionist-federation-of-australia': 'https://www.zfa.com.au',
  'south-african-jewish-board-of-deputies': 'https://www.sajbd.org',
  'south-african-zionist-federation': 'https://www.sazf.org',
  'jewish-community-of-buenos-aires-amia': 'https://www.amia.org.ar',
  'daia-argentina': 'https://www.daia.org.ar',
  'confederacao-israelita-do-brasil': 'https://www.conib.org.br',
  'albert-einstein-hospital-brazil': 'https://www.einstein.br',
  'nairobi-hebrew-congregation': 'https://www.nairobisynagogue.com',
  'casa-sefarad-israel-madrid': 'https://www.casasefarad-israel.es',
  'federation-of-jewish-communities-of-spain': 'https://www.fcje.org',
  'federation-of-jewish-communities-of-spain-additional': 'https://www.fcje.org',
  'jewish-community-of-lisbon': 'https://www.cilisboa.org',
  'organization-of-the-jews-in-bulgaria': 'https://www.jewishorganization.bg',
  'shalom-organization-jews-bulgaria': 'https://www.shalom.bg',
  'central-council-of-jewish-communities-in-finland': 'https://www.jchelsinki.fi',
  'drancy-internment-camp-memorial': 'https://www.camp-de-drancy.fr',
  'ose-france': 'https://www.ose-france.org',
  'bureau-national-de-vigilance-contre-l-antis-mitisme-bnvca': 'https://www.bnvca.org',
  'uejf-union-of-jewish-students-of-france': 'https://www.uejf.org',
  'spcj-service-de-protection-de-la-communaut-juive': 'https://www.spcj.org',
  'allgemeine-rabbinerkonferenz-general-rabbinical-conference': 'https://www.a-r-k.de',
  'nik-nederlands-isra-litisch-kerkgenootschap': 'https://www.nik.nl',
  'jewish-representative-council-of-ireland': 'https://www.jewishireland.org',
  'federation-of-jewish-communities-in-serbia': 'https://www.savezjos.org',
  'union-of-jewish-communities-in-poland': 'https://www.jewish.org.pl',
  'tykocin-synagogue': 'https://en.wikipedia.org/wiki/Great_Synagogue_(Tykocin)',
  'synagogue-of-florence-tempio-maggiore': 'https://en.wikipedia.org/wiki/Great_Synagogue_of_Florence',
  'museum-of-sephardic-heritage-toledo': 'https://www.culturaydeporte.gob.es/msefardi',
  'jewish-museum-of-bologna': 'https://www.museoebraico.bo.it',
  'ahrida-synagogue-istanbul': 'https://en.wikipedia.org/wiki/Ahrida_Synagogue',
  'israeli-wine-industry': 'https://www.wineroute.co.il',
  'jewish-museum-trondheim': 'https://www.jodiskmuseumtrondheim.no',
  'jewish-community-of-oslo': 'https://www.dmt.oslo.no',
  'jewish-community-of-denmark': 'https://www.telefonbogen.dk/mosaiske',
  'rescue-of-danish-jews-1943': 'https://en.wikipedia.org/wiki/Rescue_of_the_Danish_Jews',
  'comit-central-de-la-comunidad-jud-a-de-m-xico': 'https://www.tribuna.com.mx',
  'colegio-hebreo-maguen-david': 'https://www.colegiomaguendavid.edu.mx',
  'tribuna-israelita': 'https://www.tribuna.org.mx',
  'jewish-community-helsinki': 'https://www.jchelsinki.fi',
  'romaniote-jewish-community': 'https://en.wikipedia.org/wiki/Romaniote_Jews',
  'holocaust-memorial-of-thessaloniki': 'https://en.wikipedia.org/wiki/Holocaust_memorial_of_Thessaloniki',
  'golden-rose-synagogue-lviv-ruins': 'https://en.wikipedia.org/wiki/Golden_Rose_Synagogue_(Lviv)',
  'uman-breslov-pilgrimage': 'https://en.wikipedia.org/wiki/Rosh_Hashana_kibbutz',
  'bayt-dakira-house-of-memory-essaouira': 'https://en.wikipedia.org/wiki/Bayt_Dakira',
  'rabbi-haim-pinto-synagogue-essaouira': 'https://en.wikipedia.org/wiki/Slat_al-Azama',
  'kobe-jewish-community': 'https://en.wikipedia.org/wiki/Jews_in_Kobe',
  'kaifeng-jewish-community': 'https://en.wikipedia.org/wiki/Kaifeng_Jews',
  'sassoon-house-shanghai': 'https://en.wikipedia.org/wiki/Sassoon_House',
  'jodensavanne-archaeological-site': 'https://en.wikipedia.org/wiki/Jodensavanne',
  'neve-shalom-synagogue-paramaribo': 'https://en.wikipedia.org/wiki/Neve_Shalom_Synagogue_(Paramaribo)',
  'jewish-museum-stockholm': 'https://www.judiskamuseet.se',
  'wiener-holocaust-library': 'https://www.wienerholocaustlibrary.org',
  'abayudaya-jewish-community': 'https://www.kulanuinc.org/abayudaya',
  'association-of-gulf-jewish-communities-agjc': 'https://www.thejewishgulf.com',
  'community-of-sant-egidio-jewish-dialogue': 'https://www.santegidio.org',
  'bergier-commission-legacy': 'https://en.wikipedia.org/wiki/Bergier_commission',
  'international-committee-of-the-red-cross-jewish-relationship': 'https://www.icrc.org',
  'world-health-organization-israeli-connections': 'https://www.who.int',
  'b-nai-b-rith-international-geneva-office': 'https://www.bnaibrith.org',
  'coordinating-committee-of-jewish-organisations-in-belgium-ccojb': 'https://www.ccojb.be',
  'antwerp-jewish-community': 'https://www.antwerpseshomre.be',
  'jewish-museum-of-rome': 'https://www.museoebraico.roma.it',
  'new-south-wales-jewish-board-of-deputies': 'https://www.nswjbd.org',
  'ort-south-africa': 'https://www.ortsa.org.za',
  'ort-hungary': 'https://www.ort.hu',
  'hungarian-jewish-museum': 'https://milev.hu',
  'central-jewish-board-of-india': 'https://en.wikipedia.org/wiki/Jewish_community_of_India',
  'bene-israel-heritage-museum-mumbai': 'https://en.wikipedia.org/wiki/Bene_Israel',
  'sassoon-family-legacy': 'https://en.wikipedia.org/wiki/Sassoon_family',
  'chabad-house-mumbai': 'https://www.chabadofindia.com',
  'united-congregation-of-israelites': 'https://www.gardensshul.org',
  'united-hebrew-congregation-of-singapore': 'https://www.singaporejews.com',
  'singapore-jewish-welfare-board': 'https://www.singaporejews.com',
  'kol-shearith-israel': 'https://www.serbrith.com',
};

let updated = 0;
for (const country in jd.countries) {
  for (const entry of jd.countries[country]) {
    if (entry.website) continue;
    if (knownWebsites[entry.id]) {
      entry.website = knownWebsites[entry.id];
      updated++;
    }
  }
}

fs.writeFileSync(dataPath, JSON.stringify(jd, null, 2));

let stillMissing = 0;
for (const country in jd.countries) {
  for (const entry of jd.countries[country]) {
    if (!entry.website) stillMissing++;
  }
}
console.log(`Website enrichment v2: ${updated} additional entries updated`);
console.log(`Entries still missing websites: ${stillMissing}`);
