// expandData33.js - WAVE 6: Remaining thin entries bulk enrichment
const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '..', 'data', 'jewish.json');
const peoplePath = path.join(__dirname, '..', 'data', 'people.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const peopleData = JSON.parse(fs.readFileSync(peoplePath, 'utf8'));

function slug(s) { return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function addPerson(id, name, bio) { if (!peopleData.people[id]) peopleData.people[id] = { name, bio, notes: '', affiliations: [] }; }
function updateDescription(entryId, newDesc) { for (const c in data.countries) for (const e of data.countries[c]) if (e.id === entryId) { e.description = newDesc; return true; } return false; }
function addIndividualToEntry(entryId, ind) { for (const c in data.countries) for (const e of data.countries[c]) if (e.id === entryId) { if (!e.individuals) e.individuals = []; if (!e.individuals.some(i => i.id === ind.id)) e.individuals.push(ind); return; } }
function addConnectionToEntry(entryId, conn) { for (const c in data.countries) for (const e of data.countries[c]) if (e.id === entryId) { if (!e.connections) e.connections = []; if (!e.connections.some(x => x.name === conn.name && x.type === conn.type)) e.connections.push(conn); return; } }

console.log('Wave 6: Enriching remaining entries...');
let enriched = 0;

const enrichments = {
  'colegio-instituto-alberto-einstein': {
    description: 'Colegio Instituto Alberto Einstein is a Jewish day school in Panama City, named after the famous Jewish-German physicist. The school serves Panama\'s Jewish community of approximately 15,000 people, one of the most prosperous and well-organized Jewish communities in Latin America relative to its size. Panama\'s Jews are primarily of Sephardic origin, with families from Syria, Lebanon, and the former Ottoman Empire arriving in the early 20th century. The school provides bilingual education (Spanish and Hebrew) with strong Judaic studies and has produced leaders of Panama\'s Jewish community and broader Panamanian society. Panama\'s Jewish community has been disproportionately influential in Panamanian business, especially in the Colón Free Trade Zone, real estate, and banking. The school represents the community\'s commitment to maintaining Jewish identity in a small Central American nation.'
  },
  'fondation-france-isra-l': {
    description: 'Fondation France-Israël is a French foundation dedicated to strengthening the relationship between France and Israel through cultural, scientific, and educational exchanges. The foundation was created to deepen bilateral ties between the two countries, which have a complex relationship shaped by France\'s large Jewish community (the third-largest in the world), France\'s historical role in the Middle East, and shifting French foreign policy toward Israel. The foundation organizes cultural events, academic partnerships, and business networking between French and Israeli institutions. France-Israel relations have been marked by periods of closeness (France was Israel\'s primary arms supplier in the 1950s-60s) and tension (de Gaulle\'s 1967 arms embargo). The foundation navigates this complexity while promoting people-to-people connections.'
  },
  'auckland-hebrew-congregation': {
    description: 'The Auckland Hebrew Congregation is the oldest and largest Jewish congregation in New Zealand, founded in 1840 - the same year New Zealand became a British colony under the Treaty of Waitangi. This makes it one of the oldest Jewish congregations in the Southern Hemisphere. The congregation serves Auckland\'s Jewish community of approximately 3,000-4,000 people. New Zealand\'s Jewish history is notable: Jews were among the earliest European settlers, and the country\'s second mayor of Wellington (Abraham Hort) was Jewish. The congregation operates a synagogue, cemetery, community center, and educational programs. New Zealand-Israel relations have been complex, with New Zealand voting in favor of UN Resolution 2334 condemning Israeli settlements in 2016, causing a diplomatic rift. The AHC community includes descendants of early settlers, Holocaust survivors, South African immigrants, and Israeli expatriates.'
  },
  'essilor-dassault-connection': {
    description: 'The Essilor-Dassault connection refers to the corporate and historical overlaps between Essilor International (now part of EssilorLuxottica) and the Dassault Group through French corporate networks. The Dassault family, led by Serge Dassault and now by his descendants, controls Dassault Aviation (Rafale fighter jets, Falcon business jets), Dassault Systèmes (3D design software), and Le Figaro (France\'s oldest national newspaper). Serge Dassault (born Serge Bloch, 1925-2018) was the son of Marcel Dassault (born Marcel Bloch), a French Jewish aviation pioneer who survived the Buchenwald concentration camp. Marcel changed the family name to Dassault and converted to Catholicism after the war. Despite the conversion, the family\'s Jewish origins are well-documented. The Dassault Group is one of France\'s most important defense contractors with revenues exceeding €25 billion. Controversies include Serge Dassault\'s conviction for vote-buying and allegations of tax evasion that were dropped due to parliamentary immunity.',
    individuals: [
      { id: slug('Marcel Dassault'), name: 'Marcel Dassault', role: 'Family Patriarch', bio: 'French-Jewish aviation pioneer (born Marcel Bloch, 1892-1986) who survived Buchenwald concentration camp, changed his name to Dassault, and built one of France\'s most important aerospace companies. Father of the Rafale fighter jet dynasty.' }
    ],
    connections: [
      { name: 'Buchenwald survival', type: 'Holocaust history', description: 'Marcel Dassault survived Buchenwald concentration camp during WWII.' },
      { name: 'Dassault Aviation', type: 'family company', description: 'Manufacturer of Rafale fighter jets and Falcon business jets.' },
      { name: 'Le Figaro', type: 'family media', description: 'The Dassault family owns Le Figaro, France\'s oldest national newspaper.' }
    ]
  },
  'arsa-asociaci-n-de-recaudaci-n-sionista-argentina': {
    description: 'ARSA (Asociación de Recaudación Sionista Argentina / Argentine Zionist Fundraising Association) is one of the primary Zionist fundraising organizations in Argentina, working to support Israel through financial contributions from Argentina\'s Jewish community - the largest in Latin America (approximately 180,000-250,000). ARSA raises funds for Israel, promotes Zionist education, and facilitates aliyah (Jewish immigration to Israel). The organization is part of the broader network of Argentine Jewish institutions that make Buenos Aires sometimes called the "Jerusalem of South America." Argentine Zionism has been shaped by the country\'s tumultuous history including the military dictatorship (1976-1983) during which an estimated 1,500-3,000 Jewish Argentines were "disappeared" - a disproportionate number compared to Jews\' percentage of the population. ARSA also works within the context of the AMIA bombing (1994, 85 killed) and the Israeli Embassy bombing (1992, 29 killed), the worst antisemitic attacks in Latin American history.'
  },
  'chabad-of-phnom-penh': {
    description: 'Chabad of Phnom Penh is the Chabad-Lubavitch center in Cambodia\'s capital, serving Israeli tourists, Jewish expatriates, and travelers. Cambodia has become one of the most popular destinations for young Israelis traveling after their mandatory military service, creating a significant seasonal Jewish population. The Chabad House in Phnom Penh hosts Shabbat dinners attracting hundreds of Israeli backpackers, provides kosher food, and serves as a community center. The Jewish presence in Cambodia connects to the country\'s complex history: Cambodia was devastated by the Khmer Rouge genocide (1975-1979) under Pol Pot, which killed nearly 2 million people. Jewish visitors have drawn parallels between the Cambodian genocide and the Holocaust, and Israeli organizations have been involved in supporting the Tuol Sleng genocide museum. The Chabad presence in Cambodia is part of Chabad\'s global network of over 5,000 centers in 100+ countries.'
  },
  'association-culturelle-isra-lite-de-monaco': {
    description: 'The Association Culturelle Israélite de Monaco is the official Jewish community organization of the Principality of Monaco, serving the small but affluent Jewish population of this Mediterranean city-state. Monaco\'s Jewish community numbers approximately 500-1,000 people, many of whom are ultra-high-net-worth individuals attracted by Monaco\'s zero income tax policy and luxurious lifestyle. The community maintains a synagogue and organizes religious services and cultural events. Monaco\'s Jewish history includes the deportation of Jews during the Vichy period (World War II) despite Monaco being nominally independent. In 2015, Prince Albert II of Monaco officially apologized for Monaco\'s role in deporting Jews during WWII. The Jewish community includes prominent business figures in finance, luxury goods, and real estate. Israeli billionaires and businesspeople are among Monaco\'s most notable Jewish residents.'
  },
  'wizo-germany': {
    description: 'WIZO Germany is the German branch of the Women\'s International Zionist Organization (WIZO), one of the largest women\'s Zionist movements in the world. WIZO was founded in 1920 in London by Rebecca Sieff and Vera Weizmann (wife of Chaim Weizmann, Israel\'s first president). The German branch operates in a country with enormous significance for Jewish history - Germany was the heartland of the Shoah that killed six million Jews. WIZO Germany raises funds for women\'s shelters, day care centers, and educational programs in Israel. The organization\'s existence in Germany is itself remarkable, representing the revival of Jewish communal life in the country that perpetrated the Holocaust. Germany\'s Jewish community has grown significantly since reunification (1990), particularly through immigration from the former Soviet Union, reaching approximately 120,000-200,000 members.'
  },
  'tribunal-tarbut': {
    description: 'Tribunal Tarbut is a cultural and educational institution serving Mexico\'s Jewish community, which numbers approximately 40,000-50,000 members concentrated mainly in Mexico City. The name "Tarbut" comes from the Hebrew word for "culture," reflecting the institution\'s focus on Jewish cultural education and programming. Mexico\'s Jewish community is one of the most organized and cohesive in Latin America, with an extensive network of schools, cultural centers, and communal organizations. The community includes Ashkenazi, Sephardic, and Syrian Jewish subgroups, each with their own institutions. Tribunal Tarbut contributes to this rich tapestry of Jewish communal life through cultural programming, educational initiatives, and community engagement. Mexico\'s Jews have been disproportionately influential in Mexican business, including families like the Salinas de Gortari connections and various banking and retail families.'
  },
  'instituto-brasil-israel-ibi': {
    description: 'The Instituto Brasil-Israel (IBI) is a Brazilian organization dedicated to promoting cultural, economic, and diplomatic relations between Brazil and Israel. Brazil has the ninth-largest Jewish community in the world (approximately 90,000-120,000 members), concentrated in São Paulo and Rio de Janeiro. IBI organizes cultural events, business conferences, educational programs, and diplomatic engagement to strengthen the Brazil-Israel relationship. Brazil was historically supportive of Israel - it was the president of the UN General Assembly session that voted for the 1947 Partition Plan, and Oswaldo Aranha (the Brazilian president of that session) is honored in Israel with streets named after him. However, Brazilian-Israeli relations have fluctuated with different governments, with left-leaning administrations (under Lula) being more critical of Israel and right-leaning ones (under Bolsonaro) being extremely pro-Israel. IBI navigates these political shifts while maintaining people-to-people connections.'
  },
  'south-african-holocaust-and-genocide-foundation': {
    description: 'The South African Holocaust & Genocide Foundation (SAHGF) operates Holocaust and genocide centers in Cape Town, Johannesburg, and Durban, connecting the lessons of the Holocaust to South Africa\'s own history of racial oppression under apartheid. Founded to educate South Africans about the Holocaust while drawing parallels to local experiences of racism and discrimination, the foundation is one of the most innovative Holocaust education organizations in the world. Given South Africa\'s own history of systemic racism, the SAHGF\'s programming resonates deeply, using the Holocaust as a lens to examine prejudice, human rights, and the responsibilities of citizenship. The foundation\'s centers host thousands of students annually. Nelson Mandela himself drew explicit connections between the Nazi persecution of Jews and apartheid, and many Jewish South Africans were prominent anti-apartheid activists. The SAHGF has been involved in debates about whether the Israeli-Palestinian conflict should be included in its genocide education.'
  },
  'museo-del-holocausto-de-buenos-aires': {
    description: 'The Museo del Holocausto de Buenos Aires (Buenos Aires Holocaust Museum) is one of the most important Holocaust museums in South America, serving as a memorial and educational center in the capital of the country with the largest Jewish community in Latin America. Opened in 2000, the museum documents the Holocaust through exhibits, archives, survivor testimonies, and educational programs. Buenos Aires has particular significance in Holocaust history: Argentina became a notorious haven for Nazi war criminals, including Adolf Eichmann (who was captured by Mossad agents in Buenos Aires in 1960 in one of the most dramatic intelligence operations in history), Josef Mengele, and Erich Priebke. The museum addresses this dark chapter of Argentine history. It also memorializes the approximately 1,500-3,000 Jewish Argentines disappeared during the military dictatorship (1976-1983) and the AMIA bombing victims (1994, 85 killed).'
  },
  'j-disches-museum-m-nchen': {
    description: 'The Jüdisches Museum München (Jewish Museum Munich) is a prominent Jewish museum in Munich, Germany, located in the heart of the city at Sankt-Jakobs-Platz alongside the Ohel Jakob Synagogue and the Jewish Community Center. Opened in 2007, the museum presents Jewish culture and history in Munich and Bavaria. Munich holds particular significance in Jewish history and the history of antisemitism: it was the birthplace of the Nazi Party, where Adolf Hitler rose to power. The Beer Hall Putsch of 1923 took place in Munich, and the city was the location of the 1938 Munich Agreement. The museum addresses this painful history while celebrating the vibrant Jewish cultural life that existed before and has been rebuilt since the Holocaust. Munich\'s pre-war Jewish community included prominent intellectuals, artists, and business leaders. The modern community includes immigrants from the former Soviet Union and Israel.'
  },
  'communaut-juive-de-lubumbashi': {
    description: 'The Communauté Juive de Lubumbashi (Jewish Community of Lubumbashi) is one of the few organized Jewish communities in the Democratic Republic of Congo, located in the country\'s second-largest city and mining capital. The Jewish presence in Lubumbashi (formerly Elisabethville during Belgian colonial rule) dates to the Belgian Congo era, when Jewish traders, mining entrepreneurs, and professionals settled in the Katanga region attracted by its enormous mineral wealth, particularly copper and cobalt. The Jewish community played a notable role in developing the region\'s mining industry. During the Belgian colonial period, there were several hundred Jews in the Congo, with synagogues in both Kinshasa and Lubumbashi. Most Jews left during the political upheavals following independence in 1960, but a small community persists. The DRC\'s vast mineral resources continue to attract Israeli business interests, particularly in diamond and mineral trading.'
  },
  'chabad-of-vientiane': {
    description: 'Chabad of Vientiane is the Chabad-Lubavitch center in the capital of Laos, one of the most remote Chabad outposts in the world. The center serves Israeli tourists and backpackers who visit Laos as part of their post-military service travels through Southeast Asia. Laos has become a popular destination for young Israelis drawn to its natural beauty, low costs, and adventurous atmosphere. The Chabad House provides Shabbat dinners, kosher food, and a community gathering point for Jewish travelers. Laos has a minimal historical Jewish presence, but the Israeli tourist community has created a seasonal Jewish population. Chabad\'s presence in Laos is part of its remarkable global network of over 5,000 centers, reaching some of the most unlikely corners of the world. The center exemplifies the Chabad movement\'s philosophy of serving every Jew regardless of location.'
  },
  'coral-temple': {
    description: 'The Coral Temple (Templul Coral) is the main synagogue of Bucharest, Romania, and one of the most important Jewish landmarks in Eastern Europe. Built in 1866 in Moorish Revival style, the synagogue stands as a testament to the once-thriving Jewish community of Romania, which numbered over 750,000 before World War II. During the Holocaust, Romania participated in the mass murder of approximately 280,000-380,000 Jews under the regime of Ion Antonescu, one of the worst atrocities in the Holocaust outside of direct Nazi control. The Coral Temple survived the war and continued to serve as the spiritual center of Bucharest\'s Jewish community. Today, Romania\'s Jewish population has dwindled to approximately 3,000-5,000 members due to the Holocaust, Communist-era emigration to Israel, and post-1989 emigration. The synagogue is a poignant symbol of a devastated community that once made Romania home to the third-largest Jewish population in Europe.',
    individuals: [],
    connections: [
      { name: 'Romanian Holocaust', type: 'historical context', description: 'Romania under Ion Antonescu participated in the murder of 280,000-380,000 Jews.' },
      { name: 'Romanian Jewish community decline', type: 'demographic history', description: 'Romania\'s Jewish population went from 750,000 before WWII to approximately 3,000-5,000 today.' }
    ]
  },
  'ronald-s-lauder-foundation-germany': {
    description: 'The Ronald S. Lauder Foundation Germany is the German branch of the philanthropic foundation established by Ronald S. Lauder, the Jewish-American billionaire, heir to the Estée Lauder fortune, and president of the World Jewish Congress. The German branch is dedicated to revitalizing Jewish life in Germany, the country that perpetrated the Holocaust. The foundation funds Jewish schools, kindergartens, summer camps, and community-building programs specifically designed to rebuild Jewish communal life in Germany. This work is particularly significant because Germany\'s Jewish community, virtually destroyed in the Holocaust, has experienced a remarkable revival since reunification in 1990, growing from approximately 30,000 to over 120,000 through immigration from the former Soviet Union. Lauder\'s foundation plays a crucial role in providing Jewish education and identity formation for this new community, many of whom arrived with limited Jewish knowledge after decades of Soviet suppression of religion.'
  },
  'acad-mie-hillel': {
    description: 'Académie Hillel is a Jewish educational institution in France, named after the great Jewish sage Hillel the Elder. Operating within France\'s extensive Jewish educational network, Académie Hillel serves the country\'s large Jewish community (the third-largest in the world, approximately 450,000-500,000). France has one of the most developed Jewish school systems outside of Israel, with dozens of Jewish day schools across the country. Jewish education in France has become increasingly important as the community faces rising antisemitism, with many families choosing Jewish schools for both educational quality and physical security after a series of attacks including the 2012 Toulouse Jewish school shooting that killed a rabbi and three children (including two of his own). The French Jewish educational system produces students who are fluent in French, Hebrew, and often English, with strong connections to both French and Israeli culture.'
  },
  'jcall-european-jewish-call-for-reason': {
    description: 'JCall (European Jewish Call for Reason) is a European Jewish advocacy organization that promotes a two-state solution to the Israeli-Palestinian conflict. Founded in 2010 by European Jewish intellectuals including Belgian philosopher and psychoanalyst Daniel Bentolila, JCall was created as a European counterpart to J Street in the United States and Americans for Peace Now. The organization launched with a petition signed by nearly 8,000 European Jews calling on Israel to negotiate peace and halt settlement expansion. JCall represents the "liberal Zionist" perspective in Europe - supporters of Israel who are critical of the occupation and settlement enterprise. The organization has been controversial within European Jewish communities, with hawkish groups accusing it of undermining Israeli security, while peace advocates praise it as an essential moderate voice. JCall has organized missions to Israel and the Palestinian territories for European Jewish leaders.'
  },
  'the-israel-project': {
    description: 'The Israel Project (TIP) was an American nonprofit advocacy organization dedicated to providing factual information about Israel and the Middle East to the press and public. Founded in 2002 by Jennifer Laszlo Mizrahi, a Jewish-American communications professional, TIP became one of the most active pro-Israel media advocacy organizations, producing press releases, fact sheets, and briefings for journalists covering Israel. The organization used sophisticated polling and messaging techniques, employing Republican strategist Frank Luntz to develop messaging guides for pro-Israel advocates. TIP\'s "Global Language Dictionary" (leaked in 2009) became controversial as it appeared to be a playbook for how to spin media coverage of Israel. The organization was also criticized for its hawkish positions, including opposition to the Iran nuclear deal. TIP shut down in 2019, reportedly due to funding challenges and internal governance issues. Its legacy represents the professionalization of pro-Israel advocacy in American media.'
  },
  'maccabi-germany': {
    description: 'Maccabi Germany (TuS Maccabi Deutschland) is the German branch of the global Maccabi sports movement, organizing Jewish sports activities across Germany. The existence of Maccabi in Germany carries profound significance given the country\'s history - the original German Maccabi movement, founded in the early 20th century, was destroyed by the Nazis. Many Maccabi athletes were murdered in the Holocaust. The revival of Maccabi Germany after World War II represents the broader rebuilding of Jewish life in Germany. Today, Maccabi Germany fields teams in various sports and sends athletes to the European Maccabi Games and the Maccabiah Games in Israel. The organization serves Germany\'s growing Jewish community (approximately 120,000-200,000 members, boosted by immigration from the former Soviet Union after 1990). Maccabi Germany\'s story embodies resilience - Jewish athletes competing under the Maccabi name in the land where Maccabi athletes were once murdered.'
  },
  'sinagoga-de-tomar': {
    description: 'The Sinagoga de Tomar (Synagogue of Tomar) is a 15th-century synagogue in the Portuguese city of Tomar, one of the oldest and best-preserved medieval synagogues on the Iberian Peninsula. Built between 1430 and 1460, the synagogue was used by the Jewish community until the forced conversion and expulsion of Jews from Portugal in 1496-1497 under King Manuel I. After the expulsion, the building was successively used as a prison, chapel, hay barn, and warehouse. It was rediscovered as a synagogue in 1920 and has been classified as a National Monument. Today it houses the Abraão Zacuto Luso-Hebraic Museum, named after the famous Jewish astronomer and mathematician who served the Portuguese crown. The synagogue is a powerful symbol of the once-flourishing Jewish community of Portugal (the Sephardim), which was destroyed by forced conversion and the Inquisition but whose cultural legacy has been increasingly recognized by modern Portugal, including through its 2015 law granting citizenship to descendants of expelled Sephardim.'
  },
  'mus-e-juif-de-belgique': {
    description: 'The Musée Juif de Belgique (Jewish Museum of Belgium) in Brussels is a museum documenting Jewish history and culture in Belgium. The museum gained tragic prominence on May 24, 2014, when a gunman opened fire at the museum, killing four people in one of the worst antisemitic attacks in Western Europe in decades. The perpetrator, Mehdi Nemmouche, was a French-Algerian jihadist who had fought with ISIS in Syria. The attack sent shockwaves through the European Jewish community and highlighted the growing threat of Islamist antisemitic terrorism in Europe. The museum covers Belgian Jewish history including the prosperous pre-war Antwerp diamond community (largely Jewish), the Holocaust in Belgium (over 25,000 Belgian Jews were deported, mostly to Auschwitz), and contemporary Jewish life. Belgium\'s Jewish community numbers approximately 30,000-40,000, concentrated in Brussels and Antwerp (which has a large Orthodox and Hasidic community centered around the diamond industry).'
  },
  'comit-de-coordination-des-organisations-juives-de-belgique-ccojb': {
    description: 'The Comité de Coordination des Organisations Juives de Belgique (CCOJB) is the umbrella organization representing the Jewish community of Belgium, coordinating between various Jewish organizations, institutions, and denominations in the country. Belgium\'s Jewish community of approximately 30,000-40,000 is concentrated in Brussels and Antwerp. The Antwerp Jewish community is renowned worldwide as the center of the global diamond trade, with the Diamond District (Diamantwijk) dominated by Orthodox and Hasidic Jews for over a century. CCOJB advocates for the community on political and security issues, combats antisemitism, and maintains relationships with the Belgian government. The organization has dealt with significant challenges including the 2014 Jewish Museum shooting, the rise of antisemitism in Belgium, and the regional ban on halal and kosher slaughter in Flanders and Wallonia - a law that Jewish and Muslim communities have challenged as an infringement on religious freedom.'
  },
  'federa-ia-comunit-ilor-evreie-ti-din-rom-nia-fcer': {
    description: 'The Federația Comunităților Evreiești din România (FCER - Federation of Jewish Communities in Romania) is the umbrella organization of the Jewish community in Romania. The FCER represents one of the most dramatic demographic declines in Jewish history: Romania had approximately 750,000 Jews before World War II (the third-largest Jewish population in Europe), but today numbers only about 3,000-5,000. This decline resulted from the Romanian Holocaust (in which 280,000-380,000 Jews were murdered under Ion Antonescu\'s regime), mass emigration to Israel (over 300,000 Romanian Jews made aliyah between 1948-1989), and the general post-1989 emigration. The FCER maintains synagogues, cemeteries, schools, and cultural institutions, and advocates for Holocaust remembrance and restitution. The organization operates the Elie Wiesel National Institute for the Study of the Holocaust in Romania, named after the Nobel laureate who was born in Sighetu Marmației, Romania.'
  },
  'windhoek-hebrew-congregation': {
    description: 'The Windhoek Hebrew Congregation is the primary Jewish community organization in Namibia\'s capital, serving a small community of approximately 50-100 Jews. Namibia\'s Jewish history is connected to South Africa\'s - Jewish settlers, mostly Lithuanian Jews (Litvaks) from South Africa, established a small community in what was then South West Africa during the early 20th century. The congregation maintains a synagogue and cemetery in Windhoek. Namibia\'s small Jewish community has been shaped by the country\'s transition from South African administration to independence in 1990. Many community members were involved in business, particularly in the diamond, karakul wool, and fishing industries. The tiny community maintains connections to the much larger South African Jewish community. Namibia has maintained relatively neutral relations with Israel, though it has expressed support for Palestinian statehood.'
  },
  'jewish-holocaust-centre-melbourne': {
    description: 'The Jewish Holocaust Centre in Melbourne, Australia is a museum and educational institution dedicated to Holocaust remembrance, founded by Holocaust survivors who settled in Australia after World War II. Melbourne is home to the largest community of Holocaust survivors outside of Israel per capita, giving this museum particular authenticity and emotional power. The center houses testimonies, artifacts, and exhibits documenting the Holocaust, and offers educational programs for schools and the public. Australia\'s Jewish community (approximately 120,000, concentrated in Melbourne and Sydney) received thousands of Holocaust survivors during and after the war. The Melbourne Jewish community, heavily Ashkenazi with strong Central and Eastern European roots, has maintained one of the most vibrant Jewish communal lives in the diaspora. The centre draws connections between the Holocaust and contemporary issues of racism, discrimination, and genocide, including Australia\'s own treatment of Aboriginal and Torres Strait Islander peoples.'
  },
  'jewish-community-centre-hong-kong': {
    description: 'The Jewish Community Centre Hong Kong serves Hong Kong\'s Jewish community of approximately 5,000-10,000 members, one of the most prominent Jewish communities in East Asia. The JCC provides social, cultural, and recreational programming and serves as a gathering place for the diverse community, which includes Sephardic Jews (particularly from the Kadoorie and Sassoon families who built Hong Kong\'s early economy), Ashkenazi Jews, Israeli expatriates, and American Jews. The Kadoorie family (Jewish-Sephardic from Baghdad) built the Peninsula Hotel and contributed enormously to Hong Kong\'s development. The Sassoon family (also Baghdadi Jews) were key figures in the China trade. The Hong Kong Jewish community has navigated the 1997 handover to China and the 2019-2020 protests. Ohel Leah Synagogue, built by the Sassoon family in 1902, is a Hong Kong heritage site.'
  },
  'comunidad-israelita-del-uruguay': {
    description: 'The Comunidad Israelita del Uruguay (CIU) is the primary organization of Uruguay\'s Jewish community, which numbers approximately 12,000-18,000 members, mostly in Montevideo. Uruguay\'s Jewish community is the third-largest in South America (after Argentina and Brazil) and has been disproportionately influential in Uruguayan society, politics, and culture. The community is predominantly Ashkenazi, with roots in Eastern European immigration during the early 20th century. Uruguay has been notably welcoming to Jews: it was one of the first nations to vote for Israel\'s creation at the UN in 1947, and it has never had significant organized antisemitism. The CIU maintains synagogues, schools, cultural centers, and a Jewish newspaper. Notable Uruguayan Jews include writer Eduardo Galeano (of partial Jewish heritage) and numerous political figures. The community has faced challenges from assimilation and emigration.'
  },
  'delegaci-n-de-asociaciones-israelitas-argentinas-daia': {
    description: 'The Delegación de Asociaciones Israelitas Argentinas (DAIA) is the political representative body of the Argentine Jewish community, the largest in Latin America (approximately 180,000-250,000 members). Founded in 1935 in response to rising antisemitism, DAIA has been at the center of Argentine Jewish political advocacy for nearly 90 years. The organization was deeply affected by the two worst antisemitic terror attacks in Latin American history: the 1992 Israeli Embassy bombing (29 killed) and the 1994 AMIA Jewish Community Center bombing (85 killed). DAIA has been relentless in demanding justice for these attacks, which have been attributed to Iran and Hezbollah but remain largely unpunished due to Argentine government corruption and cover-ups. Prosecutor Alberto Nisman, who investigated the AMIA case, was found dead under suspicious circumstances in 2015 hours before he was to present evidence of a government cover-up. DAIA has also fought antisemitism in Argentine culture and politics.',
    individuals: [],
    connections: [
      { name: 'AMIA bombing', type: 'central concern', description: 'DAIA has demanded justice for the 1994 AMIA bombing that killed 85 people.' },
      { name: 'Alberto Nisman death', type: 'controversy', description: 'The AMIA case prosecutor was found dead under suspicious circumstances in 2015.' },
      { name: 'Iran/Hezbollah', type: 'accused perpetrators', description: 'The AMIA bombing has been attributed to Iran and Hezbollah.' }
    ]
  },
  'federation-of-jewish-communities-of-brazil-conib': {
    description: 'The Confederação Israelita do Brasil (CONIB - Confederation of Israelite [Jewish] Communities of Brazil) is the umbrella organization representing Brazil\'s Jewish community, the ninth-largest in the world with approximately 90,000-120,000 members. Founded in 1951, CONIB coordinates between Jewish organizations across Brazil, advocates for community interests, and maintains diplomatic relationships with the Brazilian government. Brazil\'s Jewish community is concentrated in São Paulo and Rio de Janeiro and has been remarkably successful in business, academia, and culture. CONIB navigates complex political waters: Brazilian-Israeli relations have fluctuated dramatically between the pro-Israel Bolsonaro administration (2019-2022) and the more Palestine-sympathetic Lula administration (2023-present). CONIB has dealt with rising antisemitism, including online hate speech and physical attacks. The organization works to preserve Holocaust memory in Brazil and maintains connections to Israel.'
  },
  'south-african-jewish-board-of-deputies': {
    description: 'The South African Jewish Board of Deputies (SAJBD) is the elected representative body of the South African Jewish community, serving approximately 50,000-60,000 Jews - one of the most well-organized Jewish communities in the diaspora. Founded in 1912, the SAJBD advocates for community interests, combats antisemitism, and engages with the South African government. South African Jews have a unique and complex history: overwhelmingly of Lithuanian (Litvak) origin, the community produced a disproportionate number of anti-apartheid activists (Joe Slovo, Ruth First, Helen Suzman, Arthur Goldreich), yet also included some who supported or were silent about apartheid. The SAJBD navigates the complex post-apartheid landscape where the ANC government has been increasingly critical of Israel, South Africa brought the ICJ genocide case against Israel in 2024, and BDS has strong institutional support. The community has experienced significant emigration to Israel, Australia, and North America.'
  },
  'central-council-of-jews-in-germany': {
    description: 'The Central Council of Jews in Germany (Zentralrat der Juden in Deutschland) is the umbrella organization representing the Jewish community in Germany, the country that perpetrated the Holocaust. The council was founded in 1950, just five years after the end of World War II, by Holocaust survivors who remained in or returned to Germany. It represents approximately 100,000-120,000 Jews in more than 100 Jewish communities across Germany. The community experienced dramatic growth after German reunification (1990) when Germany accepted approximately 200,000 Jewish immigrants from the former Soviet Union. The Central Council advises the German government on Jewish affairs and combats antisemitism, which has been rising in Germany from both far-right extremists and some immigrant communities. The council\'s existence is itself remarkable - the representative body of Jews living in the land of the perpetrators, navigating the complex moral and historical terrain of German-Jewish relations in the post-Holocaust era.',
    individuals: [
      { id: slug('Josef Schuster'), name: 'Josef Schuster', role: 'President', bio: 'President of the Central Council of Jews in Germany since 2014. German-Jewish physician and community leader who represents Jewish interests in contemporary Germany.' }
    ],
    connections: [
      { name: 'German government', type: 'advisory role', description: 'The Central Council advises the German government on Jewish affairs and antisemitism.' },
      { name: 'Soviet Jewish immigration', type: 'community growth', description: 'Germany accepted ~200,000 Jewish immigrants from the former Soviet Union after 1990.' },
      { name: 'Rising German antisemitism', type: 'ongoing challenge', description: 'The council combats growing antisemitism from far-right extremists and other sources.' }
    ]
  },
  'jewish-community-of-andorra': {
    description: 'The Jewish Community of Andorra is one of Europe\'s smallest Jewish communities, in the tiny Pyrenean principality between France and Spain. The community numbers only a few dozen families. Andorra\'s Jewish history is connected to the broader Sephardic experience on the Iberian Peninsula - after the Spanish and Portuguese expulsions of 1492 and 1496, some Conversos (Jews who converted to Christianity under duress) may have sought refuge in the remote Pyrenean valleys. In the modern era, Jewish residents are primarily businesspeople and professionals attracted by Andorra\'s tax advantages and mountain lifestyle. Andorra established diplomatic relations with Israel in 1995 and joined the United Nations in 1993. The community gathers informally for holidays and relies on neighboring Jewish communities in France and Spain for religious services and Jewish education.'
  },
  'jewish-community-of-kobe': {
    description: 'The Jewish Community of Kobe, Japan is a small but historically significant Jewish community. Kobe is famous in Jewish history as the city where approximately 4,500 Jewish refugees found temporary shelter during World War II, having been issued transit visas by Chiyune Sugihara, the Japanese vice-consul in Lithuania who defied orders to provide visas to Jews fleeing the Holocaust. These refugees, mostly Lithuanian yeshiva students including the entire Mir Yeshiva, traveled across the Trans-Siberian Railway to Japan and were sheltered in Kobe before most moved on to Shanghai or other destinations. Sugihara, honored as "Righteous Among the Nations" by Yad Vashem, saved an estimated 6,000-10,000 Jews. Today\'s Kobe Jewish community is small, consisting mainly of expatriates and business people. The community maintains the Ohel Shelomo Synagogue (built in 1970) and preserves the memory of the wartime Jewish refugee experience.'
  },
  'seoul-jewish-community': {
    description: 'The Seoul Jewish Community is the primary Jewish congregation in South Korea, numbering approximately 500-1,000 members, mostly American military personnel, diplomats, businesspeople, and their families. The community operates Chabad of Korea, which provides religious services, a Hebrew school, and kosher food. South Korea has a unique fascination with Judaism: Korean interest in the Talmud has become a cultural phenomenon, with Koreans believing that studying Talmud develops intelligence and business acumen. A Korean edition of the Talmud has become a bestseller, and some Korean families study it as part of education. This Talmud phenomenon is unprecedented in non-Jewish societies. South Korea-Israel relations are strong, with significant technology, defense, and trade partnerships. Korean companies like Samsung, Hyundai, and LG have invested in Israeli startups. The Seoul Jewish Community has benefited from this generally positive Korean attitude toward Jews and Israel.'
  },
  'jewish-community-of-dushanbe': {
    description: 'The Jewish Community of Dushanbe represents the remnant of what was once a significant Bukharian Jewish community in Tajikistan. Bukharian Jews, who spoke a Judeo-Persian dialect, had lived in Central Asia for over 2,000 years, with legends tracing their origin to the Babylonian exile. Before the Soviet era, Dushanbe and other Central Asian cities had vibrant Jewish communities. The Soviet period suppressed religious practice but preserved the communities. After the dissolution of the Soviet Union in 1991, and particularly during the Tajik Civil War (1992-1997), the vast majority of Tajikistan\'s Jews emigrated to Israel, the United States, and other countries. Today, only a few dozen to a few hundred Jews remain in Dushanbe. The community maintains a synagogue and is supported by Chabad. Tajikistan\'s Jewish community represents the decline of the ancient Bukharian Jewish civilization of Central Asia.'
  },
  'jewish-community-of-estonia': {
    description: 'The Jewish Community of Estonia (Eesti Juudi Kogukond) represents approximately 1,500-2,500 Jews in Estonia, a community with a tragic Holocaust history. Estonia was the first country declared "Judenfrei" (free of Jews) by the Nazis in January 1942, as the German occupation forces and local Estonian collaborators murdered nearly the entire Jewish population of approximately 1,000 Estonian Jews. Additionally, thousands of Jews from other countries were brought to Estonian concentration camps (including Klooga and Vaivara) and murdered. Today\'s Estonian Jewish community was largely rebuilt by Soviet-era immigrants, particularly from Russia and Ukraine. Since Estonian independence in 1991, the community has revived Jewish life, opening a Jewish school, community center, and cultural programs. The Estonian Jewish community is small but active, participating in Holocaust remembrance and combating historical revisionism regarding Estonian collaboration in the Holocaust.',
    individuals: [],
    connections: [
      { name: 'Holocaust in Estonia', type: 'historical tragedy', description: 'Estonia was the first country declared "Judenfrei" by the Nazis in 1942.' },
      { name: 'Estonian collaboration', type: 'historical controversy', description: 'Local Estonian collaborators participated in the murder of Jews during the Nazi occupation.' },
      { name: 'Klooga concentration camp', type: 'Holocaust site', description: 'Thousands of Jews were murdered at Klooga camp in Estonia.' }
    ]
  },
  'jewish-community-of-kazakhstan': {
    description: 'The Jewish Community of Kazakhstan represents approximately 3,000-5,000 Jews in Central Asia\'s largest country. Kazakhstan\'s Jewish history includes both ancient Bukharian Jewish trading communities along the Silk Road and a significant wave of Soviet-era Jews who were evacuated or deported to Kazakhstan during World War II. During the Holocaust, Kazakhstan served as a place of refuge for hundreds of thousands of Soviet Jews evacuated from Nazi-advancing areas, effectively saving their lives. In the post-Soviet era, most of Kazakhstan\'s Jews emigrated to Israel, Germany, or the United States. The remaining community, centered in Almaty and Nur-Sultan (Astana), is active and maintains synagogues and community centers. Kazakhstan under President Nazarbayev maintained positive relations with Israel while also engaging the broader Muslim world. The community is supported by Chabad and the Alexander Baron Jewish Community Center of Kazakhstan.'
  },
  'jewish-community-of-thailand': {
    description: 'The Jewish Community of Thailand is based primarily in Bangkok, numbering approximately 1,000-2,000 permanent residents, but swelling significantly during tourist season as Thailand is one of the most popular destinations for Israeli travelers. The community maintains the Beth Elisheva Synagogue in Bangkok (the Soi 22 Ashkenazi synagogue) and a Chabad center that hosts massive Shabbat and holiday events for Israeli tourists and backpackers, sometimes serving over 1,000 people for a single Shabbat dinner. Thailand has a warm relationship with the Jewish community and with Israel - diplomatic relations were established in 1954. The Thai royal family has expressed interest in Jewish culture. Thailand\'s Chabad operations are among the most active in Southeast Asia, providing kosher food, religious services, and a community hub for the large seasonal Israeli population. Thai-Israeli trade relationships are significant, particularly in agriculture and technology.'
  },
  'jewish-community-of-bulgaria': {
    description: 'The Jewish Community of Bulgaria (Organization of Jews in Bulgaria "Shalom") represents approximately 2,000-6,000 Jews in Bulgaria, a community celebrated for one of the most remarkable rescue stories of the Holocaust. In 1943, Bulgarian civil society, politicians, and the Orthodox Church successfully prevented the deportation of approximately 48,000 Bulgarian Jews to Nazi extermination camps. This act of collective rescue was led by figures including Deputy Speaker Dimitar Peshev, Metropolitan Kiril of Plovdiv, and Metropolitan Stefan of Sofia. However, Bulgaria\'s record is not unblemished: the government did allow the deportation of approximately 11,343 Jews from Bulgarian-occupied territories in Macedonia and Thrace, who were murdered at Treblinka. Today\'s community is small, as the vast majority of Bulgarian Jews (approximately 45,000) emigrated to Israel after 1948. The community maintains the Sofia Synagogue, the largest Sephardic synagogue in Europe.',
    individuals: [],
    connections: [
      { name: 'Rescue of Bulgarian Jews', type: 'Holocaust history', description: 'Bulgarian civil society prevented the deportation of 48,000 Jews in 1943.' },
      { name: 'Bulgarian-occupied territories', type: 'dark chapter', description: 'Bulgaria allowed deportation of 11,343 Jews from occupied Macedonia and Thrace.' },
      { name: 'Sofia Synagogue', type: 'landmark', description: 'The largest Sephardic synagogue in Europe, built in 1909.' }
    ]
  },
  'babi-yar-holocaust-memorial-center': {
    description: 'The Babi Yar Holocaust Memorial Center is a memorial and museum site in Kyiv, Ukraine, commemorating one of the most horrific massacres of the Holocaust. On September 29-30, 1941, Nazi German Einsatzgruppen and their local collaborators murdered 33,771 Jewish men, women, and children at the Babi Yar ravine on the outskirts of Kyiv - the largest single mass shooting of the Holocaust. Over the subsequent months, an estimated 100,000-150,000 additional Jews, Roma, Soviet POWs, and others were killed at the site. Despite the massive scale of the atrocity, the Soviet Union suppressed the specifically Jewish nature of the massacre for decades, turning the site into a Soviet generic war memorial. The modern memorial center, which broke ground in 2021 with renewed international attention (funded in part by Ukrainian-Jewish oligarchs), aims to create a world-class memorial and educational center. The project has been complicated by Russia\'s 2022 invasion of Ukraine and by controversies over governance and historical narratives.'
  },
  'galicia-jewish-museum': {
    description: 'The Galicia Jewish Museum is a museum in the Kazimierz district of Kraków, Poland, dedicated to commemorating Jewish culture and history in the former Austro-Hungarian region of Galicia and challenging stereotypes about Jewish life in Poland. Founded in 2004 by British photographer Chris Schwarz (who died before its opening) and Jewish-British historian Jonathan Webber, the museum uses photography and multimedia to document Jewish heritage sites across Galicia. The Kazimierz district was Kraków\'s historic Jewish quarter and is now a center of Jewish heritage tourism. The museum focuses on showing not just the destruction of the Holocaust but the vibrancy of Jewish life before the war and the traces that remain. Kraków was home to approximately 65,000 Jews before WWII, most of whom were murdered in the Holocaust. The museum also covers the story of Oscar Schindler, whose enamel factory in Kraków was the setting for Schindler\'s List.'
  },
  'jewish-quarter-of-prague-josefov': {
    description: 'The Jewish Quarter of Prague (Josefov) is one of the best-preserved Jewish heritage sites in Europe and a UNESCO-recognized historical area in the heart of Prague. Named after Emperor Joseph II, who granted Jews civil rights in the 18th century, Josefov preserves six historic synagogues, the Old Jewish Cemetery (one of the oldest surviving Jewish cemeteries in Europe, dating to the 15th century), and the Jewish Museum in Prague (one of the world\'s oldest Jewish museums, founded in 1906). The quarter is associated with legends of Rabbi Judah Loew ben Bezalel (the Maharal of Prague), who according to legend created the Golem - a clay figure brought to life to protect the Jewish community. During the Holocaust, the Nazis ironically preserved much of Prague\'s Jewish heritage with the perverse intention of creating a "museum of an extinct race." The Czech-Jewish community, which numbered approximately 120,000 before WWII, was nearly annihilated - approximately 80,000 Czech Jews were murdered. Today approximately 3,000-4,000 Jews live in the Czech Republic.'
  },
  'joods-historisch-museum': {
    description: 'The Joods Historisch Museum (Jewish Historical Museum) in Amsterdam is the main museum dedicated to Jewish history and culture in the Netherlands. Located in a complex of four former Ashkenazi synagogues dating to the 17th-18th centuries in Amsterdam\'s historic Jewish Quarter, the museum presents the history of Jews in the Netherlands from 1600 to the present. Amsterdam was once known as the "Jerusalem of the West" due to its enormous Jewish community - at its peak, Jews constituted about 13% of the city\'s population. The museum covers the Golden Age when Jews fleeing the Iberian Inquisition found refuge in tolerant Amsterdam, the devastating Holocaust (75% of Dutch Jews were murdered - the highest percentage in Western Europe), and the rebuilding of Jewish life after the war. The museum complex includes the Portuguese Synagogue (built in 1675), one of the most beautiful synagogues in the world, and the National Holocaust Memorial of Names (inaugurated in 2021, listing all 102,000 Dutch Holocaust victims).'
  },
  'jewish-museum-and-tolerance-center': {
    description: 'The Jewish Museum and Tolerance Center in Moscow is the largest Jewish museum in Russia and one of the most technologically advanced Jewish museums in the world. Opened in 2012 in a historic constructivist building, the museum presents Russian-Jewish history from the 18th century Pale of Settlement through the Russian Revolution, the Soviet era, and the present. The museum was built with significant funding from Russian-Jewish oligarchs and was endorsed by President Vladimir Putin, who donated a month of his salary. Russia has a complex relationship with its Jewish population: it was home to the largest Jewish community in the world before the Revolution, but Jews faced centuries of pogroms, the Pale of Settlement, blood libels, and ultimately the Soviet suppression of Jewish culture. Many of Russia\'s Jews played prominent roles in the Bolshevik Revolution (Trotsky, Zinoviev, Kamenev) before Stalin\'s purges targeted Jewish intellectuals. Today approximately 150,000-200,000 Jews remain in Russia.'
  },
  'dreamworks-animation': {
    description: 'DreamWorks Animation is a major American animation studio, originally part of DreamWorks SKG founded in 1994 by Steven Spielberg, Jeffrey Katzenberg, and David Geffen - three of the most powerful Jewish entertainment executives in Hollywood history. The "SKG" in the original name stands for their initials. DreamWorks Animation produced blockbuster franchises including Shrek, Kung Fu Panda, How to Train Your Dragon, Madagascar, and Trolls. The studio was spun off as a separate company in 2004 and acquired by NBCUniversal (Comcast) in 2016 for $3.8 billion. Steven Spielberg is the most successful filmmaker in history and a prominent supporter of Holocaust education (founding the Shoah Foundation). Jeffrey Katzenberg built the animation studio after his controversial departure from Disney. David Geffen is one of the wealthiest self-made individuals in entertainment history.'
  },
  'nestl': {
    description: 'Nestlé S.A. is the world\'s largest food and beverage company by revenue, headquartered in Vevey, Switzerland. Founded in 1866 by Henri Nestlé, a German pharmacist of Swiss nationality. Though Nestlé himself was not Jewish, the company\'s Jewish connections are extensive: its controversial WWII history (production continued in Nazi Germany, and the company used slave labor during the war), its acquisition of the Israeli food company Osem in 2016 for $950 million, its ongoing operations in Israel, and investment from Jewish-led financial institutions. The company has been one of the most protested corporations in history - the Nestlé boycott over infant formula marketing in developing countries (accused of causing infant deaths by discouraging breastfeeding) has run since the 1970s. Additional controversies include child labor in cocoa supply chains, water privatization (particularly in drought-affected regions), and environmental impact of its packaging. Nestlé has been targeted by BDS for its Israeli operations, though the company maintains its business activities in the country.',
    individuals: [],
    connections: [
      { name: 'Osem', type: 'subsidiary', description: 'Nestlé owns Israeli food company Osem, acquired for $950 million.' },
      { name: 'WWII slave labor', type: 'historical controversy', description: 'Nestlé used slave labor during WWII and its German operations continued under Nazi rule.' },
      { name: 'Infant formula controversy', type: 'ongoing boycott', description: 'Nestlé has been boycotted since the 1970s over infant formula marketing in developing countries.' },
      { name: 'BDS targeting', type: 'boycott', description: 'Nestlé has been targeted by BDS for its Israeli operations through Osem.' }
    ]
  }
};

for (const entryId in enrichments) {
  const e = enrichments[entryId];
  if (e.description) {
    const found = updateDescription(entryId, e.description);
    if (found) enriched++;
    else console.log(`  Warning: Entry not found: ${entryId}`);
  }
  if (e.individuals) {
    for (const ind of e.individuals) {
      addIndividualToEntry(entryId, ind);
      addPerson(ind.id, ind.name, ind.bio);
    }
  }
  if (e.connections) {
    for (const conn of e.connections) {
      addConnectionToEntry(entryId, conn);
    }
  }
}
console.log(`  Enriched ${enriched} entries`);

// Re-sort and rebuild affiliations
console.log('Re-sorting entries...');
for (const country in data.countries) {
  data.countries[country].sort((a, b) => {
    const scoreA = (a.description || '').length + ((a.connections || []).length * 50) + ((a.individuals || []).length * 30);
    const scoreB = (b.description || '').length + ((b.connections || []).length * 50) + ((b.individuals || []).length * 30);
    return scoreB - scoreA;
  });
}

console.log('Rebuilding affiliations...');
const affMap = {};
for (const country in data.countries) {
  for (const entry of data.countries[country]) {
    for (const ind of (entry.individuals || [])) {
      if (!affMap[ind.id]) affMap[ind.id] = [];
      affMap[ind.id].push({ organization: entry.name, role: ind.role || 'Associated', entryId: entry.id, country });
    }
  }
}
let affCount = 0;
for (const pid in peopleData.people) {
  if (!peopleData.people[pid].affiliations) peopleData.people[pid].affiliations = [];
  if (affMap[pid]) {
    for (const aff of affMap[pid]) {
      if (!peopleData.people[pid].affiliations.some(a => a.entryId === aff.entryId)) {
        peopleData.people[pid].affiliations.push(aff);
        affCount++;
      }
    }
  }
}
console.log(`  Updated ${affCount} affiliations`);

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
fs.writeFileSync(peoplePath, JSON.stringify(peopleData, null, 2));

let totalEntries = 0, totalPeople = Object.keys(peopleData.people).length;
let shortDescs = 0, noIndividuals = 0;
for (const c in data.countries) for (const e of data.countries[c]) {
  totalEntries++;
  if ((e.description || '').length < 200) shortDescs++;
  if (!e.individuals || e.individuals.length === 0) noIndividuals++;
}
console.log(`\n=== STATS ===`);
console.log(`Entries: ${totalEntries}`);
console.log(`People: ${totalPeople}`);
console.log(`Still thin (<200): ${shortDescs}`);
console.log(`Still no individuals: ${noIndividuals}`);
console.log('Done!');
