// expandData23.js - MASSIVE US expansion: hundreds of new organizations
const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'data', 'jewish.json');
const peoplePath = path.join(__dirname, '..', 'data', 'people.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const peopleData = JSON.parse(fs.readFileSync(peoplePath, 'utf8'));

function slug(s) { return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function addPerson(id, name, bio) {
  if (!peopleData.people[id]) peopleData.people[id] = { name, bio, notes: '', affiliations: [] };
}
function addEntry(country, entry) {
  if (!data.countries[country]) data.countries[country] = [];
  if (data.countries[country].some(e => e.id === entry.id)) return false;
  data.countries[country].push(entry);
  return true;
}
function addConnectionToEntry(entryId, connection) {
  for (const country in data.countries) {
    for (const entry of data.countries[country]) {
      if (entry.id === entryId) {
        if (!entry.connections) entry.connections = [];
        if (entry.connections.some(c => c.name === connection.name && c.type === connection.type)) return;
        entry.connections.push(connection);
        return;
      }
    }
  }
}

let added = 0;
function ae(country, e) {
  if (!e.individuals) e.individuals = [];
  if (!e.connections) e.connections = [];
  if (addEntry(country, e)) { added++; }
  for (const ind of e.individuals) addPerson(ind.id, ind.name, ind.bio);
}

console.log('Adding massive US expansion...');

// ===== BANKING & FINANCIAL SERVICES =====
ae('United States', { name: 'Lazard', id: slug('Lazard'), type: 'investment bank', category: 'Banking & Financial Services', description: 'Lazard is a global financial advisory and asset management firm founded in 1848 by three Lazard brothers from France. One of the oldest and most prestigious investment banks in the world, Lazard advises on mergers, acquisitions, restructurings, and capital markets. It manages over $230 billion in assets.', website: 'https://www.lazard.com', founded: 1848, individuals: [{ id: slug('Peter Orszag'), name: 'Peter Orszag', role: 'CEO', bio: 'CEO of Lazard. Former Director of the Office of Management and Budget under President Obama.' }], connections: [{ name: 'Goldman Sachs', type: 'industry peer', description: 'Both are leading investment banking firms.' }] });
ae('United States', { name: 'Guggenheim Partners', id: slug('Guggenheim Partners'), type: 'investment firm', category: 'Investment & Private Equity', description: 'Guggenheim Partners is a global investment and advisory firm with over $310 billion in assets under management. Founded in 1999, it provides services across investment banking, capital markets, insurance, and investment management. The firm is named after the Guggenheim family.', website: 'https://www.guggenheimpartners.com', founded: 1999, individuals: [{ id: slug('Mark Walter'), name: 'Mark Walter', role: 'CEO', bio: 'Co-founder and CEO of Guggenheim Partners. Part-owner of the Los Angeles Dodgers.' }], connections: [] });
ae('United States', { name: 'Jefferies Financial Group', id: slug('Jefferies Financial Group'), type: 'investment bank', category: 'Banking & Financial Services', description: 'Jefferies Financial Group is a global full-service investment banking and capital markets firm. Founded in 1962, it is one of the largest independent investment banks in the world, offering equity, fixed income, asset management, and wealth management services.', website: 'https://www.jefferies.com', founded: 1962, individuals: [{ id: slug('Rich Handler'), name: 'Rich Handler', role: 'CEO', bio: 'CEO of Jefferies Financial Group since 2001. Known for his active social media presence and leadership style.' }], connections: [{ name: 'Cantor Fitzgerald', type: 'industry peer', description: 'Both are major independent financial services firms.' }] });
ae('United States', { name: 'Moelis & Company', id: slug('Moelis & Company'), type: 'investment bank', category: 'Banking & Financial Services', description: 'Moelis & Company is a global independent investment bank providing financial advisory services on mergers and acquisitions, recapitalizations, restructurings, and other corporate transactions. Founded in 2007 by Ken Moelis, it rapidly grew to become one of the premier independent advisory firms.', website: 'https://www.moelis.com', founded: 2007, individuals: [{ id: slug('Ken Moelis'), name: 'Ken Moelis', role: 'Chairman & CEO', bio: 'Founder, Chairman and CEO of Moelis & Company. Former head of UBS Investment Bank.' }], connections: [] });
ae('United States', { name: 'Evercore', id: slug('Evercore'), type: 'investment bank', category: 'Banking & Financial Services', description: 'Evercore is an independent investment banking advisory firm founded in 1995 by Roger Altman. It is the largest independent investment banking advisory firm in the world by revenue, advising on mergers, acquisitions, restructurings, and other strategic transactions.', website: 'https://www.evercore.com', founded: 1995, individuals: [{ id: slug('Roger Altman'), name: 'Roger Altman', role: 'Founder & Senior Chairman', bio: 'Founder and Senior Chairman of Evercore. Former Deputy Secretary of the US Treasury under President Clinton.' }, { id: slug('John Weinberg Evercore'), name: 'John Weinberg', role: 'Chairman & CEO', bio: 'Chairman and CEO of Evercore. Son of former Goldman Sachs senior partner.' }], connections: [{ name: 'Lazard', type: 'industry peer', description: 'Both are leading independent investment advisory firms.' }] });
ae('United States', { name: 'Warburg Pincus', id: slug('Warburg Pincus'), type: 'private equity', category: 'Investment & Private Equity', description: 'Warburg Pincus is a global private equity firm focused on growth investing. Founded in 1966 with roots in the Warburg banking dynasty, the firm has invested more than $100 billion in over 1,000 companies across the globe. It focuses on sectors including technology, healthcare, financial services, and consumer.', website: 'https://www.warburgpincus.com', founded: 1966, individuals: [{ id: slug('Chip Kaye'), name: 'Chip Kaye', role: 'CEO', bio: 'CEO of Warburg Pincus, leading one of the world\'s premier growth equity firms.' }], connections: [{ name: 'KKR', type: 'industry peer', description: 'Both are major private equity firms.' }] });
ae('United States', { name: 'Apollo Global Management', id: slug('Apollo Global Management'), type: 'alternative asset management', category: 'Investment & Private Equity', description: 'Apollo Global Management is one of the world\'s largest alternative asset managers with approximately $650 billion in assets under management. Founded in 1990 by Leon Black, Josh Harris, and Marc Rowan, Apollo invests across credit, private equity, and real assets strategies. The firm manages the retirement savings of millions through its insurance subsidiary Athene.', website: 'https://www.apollo.com', founded: 1990, individuals: [{ id: slug('Marc Rowan'), name: 'Marc Rowan', role: 'CEO', bio: 'CEO of Apollo Global Management. Co-founder and billionaire investor.' }, { id: slug('Leon Black'), name: 'Leon Black', role: 'Co-Founder', bio: 'Co-founder of Apollo Global Management. Former CEO and Chairman. Stepped down in 2021.' }, { id: slug('Josh Harris Apollo'), name: 'Josh Harris', role: 'Co-Founder', bio: 'Co-founder of Apollo Global Management. Owner of the Washington Commanders NFL team.' }], connections: [{ name: 'Blackstone', type: 'industry peer', description: 'Both are major alternative asset management firms.' }] });
ae('United States', { name: 'Ares Management', id: slug('Ares Management'), type: 'alternative asset management', category: 'Investment & Private Equity', description: 'Ares Management Corporation is a global alternative investment manager with approximately $400 billion in assets under management. Founded in 1997, Ares operates across credit, private equity, real estate, and infrastructure strategies. It is one of the largest direct lenders in the US.', website: 'https://www.aresmgmt.com', founded: 1997, individuals: [{ id: slug('Michael Arougheti'), name: 'Michael Arougheti', role: 'CEO & President', bio: 'Co-founder, CEO and President of Ares Management. Leading figure in alternative credit markets.' }], connections: [] });
ae('United States', { name: 'Sculptor Capital Management', id: slug('Sculptor Capital Management'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Sculptor Capital Management (formerly Och-Ziff Capital Management) is a global multi-strategy alternative asset management firm. Founded in 1994 by Daniel Och, the firm manages investments across multi-strategy, credit, and real estate.', website: 'https://www.sculptorcapital.com', founded: 1994, individuals: [{ id: slug('Daniel Och'), name: 'Daniel Och', role: 'Founder', bio: 'Founder of Sculptor Capital Management (formerly Och-Ziff). Former Goldman Sachs partner.' }], connections: [] });
ae('United States', { name: 'Icahn Enterprises', id: slug('Icahn Enterprises'), type: 'conglomerate', category: 'Conglomerates & Holding Companies', description: 'Icahn Enterprises is a diversified conglomerate holding company controlled by billionaire investor Carl Icahn. The company has interests in investment, energy, automotive, food packaging, metals, real estate, and home fashion. Icahn is known as one of the most prominent activist investors in Wall Street history.', website: 'https://www.ielp.com', founded: 1987, individuals: [{ id: slug('Carl Icahn'), name: 'Carl Icahn', role: 'Chairman', bio: 'Billionaire investor and chairman of Icahn Enterprises. One of the most famous activist investors in history.' }], connections: [] });
ae('United States', { name: 'Renaissance Technologies', id: slug('Renaissance Technologies'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Renaissance Technologies is a quantitative hedge fund management company founded in 1982 by mathematician James Simons. Its Medallion Fund is considered the most successful hedge fund ever, generating average annual returns of 66% before fees from 1988 to 2018. The firm pioneered the use of mathematical models and algorithms in trading.', website: 'https://www.rentec.com', founded: 1982, individuals: [{ id: slug('James Simons'), name: 'James Simons', role: 'Founder', bio: 'Mathematician, philanthropist, and founder of Renaissance Technologies. Died in 2024. His Medallion Fund was the most successful hedge fund in history.' }, { id: slug('Peter Brown RenTech'), name: 'Peter Brown', role: 'CEO', bio: 'CEO of Renaissance Technologies, continuing the quantitative trading legacy.' }], connections: [{ name: 'D.E. Shaw', type: 'quant peer', description: 'Both are pioneering quantitative hedge funds.' }] });
ae('United States', { name: 'D.E. Shaw', id: slug('D.E. Shaw'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'D.E. Shaw & Co. is a multinational investment management firm founded in 1988 by David E. Shaw, a former Columbia University computer science professor. The firm uses computational technology and quantitative techniques across its investment strategies. It manages approximately $60 billion in assets.', website: 'https://www.deshaw.com', founded: 1988, individuals: [{ id: slug('David E. Shaw'), name: 'David E. Shaw', role: 'Founder', bio: 'Founder of D.E. Shaw. Computational scientist turned hedge fund pioneer. Jeff Bezos worked at D.E. Shaw before founding Amazon.' }], connections: [{ name: 'Renaissance Technologies', type: 'quant peer', description: 'Both are pioneering quantitative hedge funds.' }] });
ae('United States', { name: 'Citadel', id: slug('Citadel'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Citadel LLC is a multinational hedge fund and financial institution founded in 1990 by Kenneth Griffin. With over $60 billion in assets under management, Citadel is one of the largest and most successful hedge funds in the world. Its market-making arm, Citadel Securities, handles approximately 25% of US equity trading volume.', website: 'https://www.citadel.com', founded: 1990, individuals: [{ id: slug('Kenneth Griffin'), name: 'Kenneth Griffin', role: 'Founder & CEO', bio: 'Founder and CEO of Citadel. Billionaire investor and major political donor. Moved Citadel headquarters from Chicago to Miami.' }], connections: [] });
ae('United States', { name: 'Point72 Asset Management', id: slug('Point72 Asset Management'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Point72 Asset Management is a hedge fund management firm founded by Steven A. Cohen. It evolved from SAC Capital Advisors and manages approximately $35 billion in assets. The firm employs fundamental and systematic investment strategies across global equities and macro.', website: 'https://www.point72.com', founded: 2014, individuals: [{ id: slug('Steven A. Cohen'), name: 'Steven A. Cohen', role: 'Founder & Chairman', bio: 'Founder of Point72 and owner of the New York Mets. Billionaire investor and art collector.' }], connections: [] });
ae('United States', { name: 'Elliott Management', id: slug('Elliott Management'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Elliott Management Corporation is one of the largest and most influential activist hedge funds in the world, founded in 1977 by Paul Singer. With approximately $65 billion in assets under management, Elliott is known for its aggressive activist campaigns against companies and even sovereign governments.', website: 'https://www.elliottmgmt.com', founded: 1977, individuals: [{ id: slug('Paul Singer Elliott'), name: 'Paul Singer', role: 'Founder & Co-CEO', bio: 'Founder of Elliott Management. Major Republican donor and influential political figure.' }], connections: [{ name: 'Start-Up Nation Central', type: 'founder connection', description: 'Paul Singer also founded Start-Up Nation Central to promote Israeli innovation.' }] });
ae('United States', { name: 'Two Sigma', id: slug('Two Sigma'), type: 'hedge fund', category: 'Investment & Private Equity', description: 'Two Sigma Investments is a quantitative hedge fund that uses artificial intelligence, machine learning, and distributed computing to find value in the world\'s data. Founded in 2001, it manages over $60 billion in assets. The firm employs over 1,800 people, many of whom are scientists and engineers.', website: 'https://www.twosigma.com', founded: 2001, individuals: [{ id: slug('David Siegel TwoSigma'), name: 'David Siegel', role: 'Co-Founder & Co-Chairman', bio: 'Co-founder and Co-Chairman of Two Sigma. Computer scientist and entrepreneur.' }, { id: slug('John Overdeck'), name: 'John Overdeck', role: 'Co-Founder & Co-Chairman', bio: 'Co-founder and Co-Chairman of Two Sigma. Former D.E. Shaw executive.' }], connections: [{ name: 'D.E. Shaw', type: 'personnel connection', description: 'Co-founder John Overdeck previously worked at D.E. Shaw.' }] });

// ===== ENTERTAINMENT & MEDIA =====
ae('United States', { name: 'Lionsgate', id: slug('Lionsgate'), type: 'entertainment company', category: 'Entertainment & Media', description: 'Lionsgate is a global entertainment company known for producing and distributing motion pictures, television programming, and digital content. Known for franchises like The Hunger Games, John Wick, and Twilight. Originally Canadian, it is now headquartered in Santa Monica, California.', website: 'https://www.lionsgate.com', founded: 1997, individuals: [{ id: slug('Jon Feltheimer'), name: 'Jon Feltheimer', role: 'CEO', bio: 'CEO of Lionsgate since 2000, guiding the company from indie studio to major entertainment player.' }], connections: [{ name: 'Starz', type: 'subsidiary', description: 'Lionsgate acquired the Starz premium cable network.' }] });
ae('United States', { name: 'IAC', id: slug('IAC'), type: 'internet & media holding', category: 'Entertainment & Media', description: 'IAC (InterActiveCorp) is a media and internet holding company led by Barry Diller. IAC has launched and spun off numerous major internet brands including Match Group, Expedia, Vimeo, and Dotdash Meredith. The company continues to build and acquire internet and media businesses.', website: 'https://www.iac.com', founded: 1995, individuals: [{ id: slug('Barry Diller'), name: 'Barry Diller', role: 'Chairman & Senior Executive', bio: 'Media mogul who has led Paramount Pictures, Fox Broadcasting, and USA Networks. Chairman of IAC and Expedia Group.' }, { id: slug('Joey Levin'), name: 'Joey Levin', role: 'CEO', bio: 'CEO of IAC since 2015. Previously led IAC\'s search and applications business.' }], connections: [{ name: 'Match Group', type: 'spinoff', description: 'IAC spun off Match Group as a publicly traded company.' }] });
ae('United States', { name: 'DreamWorks Animation', id: slug('DreamWorks Animation'), type: 'animation studio', category: 'Entertainment & Media', description: 'DreamWorks Animation is an animation studio known for franchises like Shrek, Madagascar, Kung Fu Panda, and How to Train Your Dragon. Originally part of DreamWorks SKG co-founded by Steven Spielberg, Jeffrey Katzenberg, and David Geffen. Now owned by NBCUniversal/Comcast.', website: 'https://www.dreamworks.com', founded: 1994, individuals: [{ id: slug('Jeffrey Katzenberg'), name: 'Jeffrey Katzenberg', role: 'Co-Founder', bio: 'Co-founder of DreamWorks SKG. Former chairman of Walt Disney Studios. Pioneered modern animation industry.' }, { id: slug('David Geffen'), name: 'David Geffen', role: 'Co-Founder', bio: 'Co-founder of DreamWorks SKG. Music and film mogul. Founded Geffen Records and Asylum Records. Billionaire philanthropist.' }], connections: [{ name: 'NBCUniversal', type: 'parent company', description: 'DreamWorks Animation was acquired by NBCUniversal/Comcast in 2016.' }] });
ae('United States', { name: 'Warner Bros. Discovery', id: slug('Warner Bros. Discovery'), type: 'media conglomerate', category: 'Entertainment & Media', description: 'Warner Bros. Discovery is a global media and entertainment company formed from the 2022 merger of WarnerMedia and Discovery Inc. It operates Warner Bros. film and TV studios, HBO, CNN, Discovery Channel, and other networks. The company is a major force in streaming through Max (formerly HBO Max).', website: 'https://www.wbd.com', founded: 2022, individuals: [{ id: slug('David Zaslav'), name: 'David Zaslav', role: 'President & CEO', bio: 'President and CEO of Warner Bros. Discovery. Former president of cable and domestic television at NBCUniversal.' }], connections: [{ name: 'NBCUniversal', type: 'industry peer', description: 'Both are major media and entertainment conglomerates.' }] });
ae('United States', { name: 'Paramount Global', id: slug('Paramount Global'), type: 'media conglomerate', category: 'Entertainment & Media', description: 'Paramount Global (formerly ViacomCBS) is a global media and entertainment company owning Paramount Pictures, CBS, Showtime, MTV, Nickelodeon, Comedy Central, and the Paramount+ streaming service. The Redstone family has been the controlling shareholder through National Amusements.', website: 'https://www.paramount.com', founded: 1994, individuals: [{ id: slug('Shari Redstone'), name: 'Shari Redstone', role: 'Chair', bio: 'Chair of Paramount Global and president of National Amusements. Daughter of Sumner Redstone, she has been the controlling force behind Paramount.' }], connections: [{ name: 'Warner Bros. Discovery', type: 'industry peer', description: 'Both are major media and entertainment conglomerates.' }] });
ae('United States', { name: 'Endeavor Group Holdings', id: slug('Endeavor Group Holdings'), type: 'talent and entertainment', category: 'Entertainment & Media', description: 'Endeavor Group Holdings is a global entertainment, sports, and content company. It owns WME (William Morris Endeavor), IMG, UFC (Ultimate Fighting Championship), and the Professional Bull Riders league. Founded by Ari Emanuel and Patrick Whitesell, Endeavor represents many of the biggest names in entertainment and sports.', website: 'https://www.endeavorco.com', founded: 1898, individuals: [{ id: slug('Ari Emanuel'), name: 'Ari Emanuel', role: 'CEO', bio: 'CEO of Endeavor. One of the most powerful talent agents in Hollywood. Brother of former Chicago mayor Rahm Emanuel.' }], connections: [] });
ae('United States', { name: 'Creative Artists Agency', id: slug('Creative Artists Agency'), type: 'talent agency', category: 'Entertainment & Media', description: 'Creative Artists Agency (CAA) is one of the leading talent and sports agencies in the world, representing actors, directors, writers, athletes, and musicians. Founded in 1975, CAA has been at the center of Hollywood dealmaking for decades and has expanded into sports, brand consulting, and venture investing.', website: 'https://www.caa.com', founded: 1975, individuals: [{ id: slug('Bryan Lourd'), name: 'Bryan Lourd', role: 'Co-Chairman', bio: 'Co-Chairman of Creative Artists Agency. One of the most powerful executives in entertainment.' }], connections: [{ name: 'Endeavor Group Holdings', type: 'industry rival', description: 'CAA and WME/Endeavor are the two dominant talent agencies in Hollywood.' }] });
ae('United States', { name: 'Activision Blizzard', id: slug('Activision Blizzard'), type: 'gaming company', category: 'Entertainment & Media', description: 'Activision Blizzard was one of the world\'s largest video game companies, owning franchises like Call of Duty, World of Warcraft, Candy Crush, and Overwatch. Under CEO Bobby Kotick, the company grew into a gaming powerhouse before being acquired by Microsoft in 2023 for $69 billion.', website: 'https://www.activisionblizzard.com', founded: 2008, individuals: [{ id: slug('Bobby Kotick'), name: 'Bobby Kotick', role: 'Former CEO', bio: 'Former CEO of Activision Blizzard (1991-2023). Led the company through its growth into one of the largest gaming companies before the Microsoft acquisition.' }], connections: [] });
ae('United States', { name: 'The New York Times Company', id: slug('The New York Times Company'), type: 'media company', category: 'Entertainment & Media', description: 'The New York Times Company is a global media organization that includes The New York Times newspaper, the most influential newspaper in the United States. The Sulzberger family has controlled the company since 1896. The Times has over 10 million digital subscribers, making it the most successful digital news subscription business.', website: 'https://www.nytco.com', founded: 1851, individuals: [{ id: slug('A.G. Sulzberger'), name: 'A.G. Sulzberger', role: 'Publisher & Chairman', bio: 'Publisher of The New York Times and Chairman of the NYT Company. Fifth generation of the Sulzberger-Ochs family to lead the paper.' }], connections: [] });
ae('United States', { name: 'Advance Publications', id: slug('Advance Publications'), type: 'media conglomerate', category: 'Entertainment & Media', description: 'Advance Publications is a privately held media company owned by the Newhouse family. It owns Conde Nast (Vogue, The New Yorker, Vanity Fair, GQ, Wired), Discovery/Warner Bros. Discovery stake, Reddit, and numerous newspapers. Founded by Samuel Irving Newhouse Sr., it is one of the largest private media empires.', website: 'https://www.advance.com', founded: 1922, individuals: [{ id: slug('Donald Newhouse'), name: 'Donald Newhouse', role: 'Co-Owner', bio: 'Billionaire co-owner of Advance Publications along with his late brother Si Newhouse.' }], connections: [] });

// ===== TECHNOLOGY =====
ae('United States', { name: 'Oracle Corporation', id: slug('Oracle Corporation'), type: 'technology company', category: 'Technology', description: 'Oracle Corporation is a multinational technology company that provides cloud computing, database software, and enterprise solutions. Founded in 1977 by Larry Ellison, Bob Miner, and Ed Oates, Oracle is one of the largest software companies in the world with annual revenues exceeding $50 billion.', website: 'https://www.oracle.com', founded: 1977, individuals: [{ id: slug('Larry Ellison'), name: 'Larry Ellison', role: 'Co-Founder & CTO', bio: 'Co-founder, CTO, and former CEO of Oracle. One of the wealthiest people in the world. Major investor in Tesla and real estate in Hawaii.' }, { id: slug('Safra Catz'), name: 'Safra Catz', role: 'CEO', bio: 'CEO of Oracle Corporation. Israeli-born American businesswoman and one of the highest-paid female executives in the world.' }], connections: [{ name: 'Google', type: 'industry peer', description: 'Both are major cloud computing providers.' }] });
ae('United States', { name: 'Dell Technologies', id: slug('Dell Technologies'), type: 'technology company', category: 'Technology', description: 'Dell Technologies is a multinational technology company that designs, sells, and supports computers, servers, data storage, networking equipment, and software. Founded in 1984 by Michael Dell from his University of Texas dorm room, it grew into one of the world\'s largest technology infrastructure companies.', website: 'https://www.dell.com', founded: 1984, individuals: [{ id: slug('Michael Dell'), name: 'Michael Dell', role: 'Founder, Chairman & CEO', bio: 'Founder, Chairman and CEO of Dell Technologies. Billionaire entrepreneur and investor. Largest shareholder through MSD Capital.' }], connections: [{ name: 'VMware', type: 'former subsidiary', description: 'Dell owned VMware before its spinoff.' }] });
ae('United States', { name: 'Qualcomm', id: slug('Qualcomm'), type: 'semiconductor company', category: 'Technology', description: 'Qualcomm is a multinational corporation that creates semiconductors, software, and services related to wireless technology. It is the world\'s largest supplier of mobile phone chips and holds key patents for cellular communications technology. Co-founded by Irwin Jacobs and Andrew Viterbi.', website: 'https://www.qualcomm.com', founded: 1985, individuals: [{ id: slug('Irwin Jacobs'), name: 'Irwin Jacobs', role: 'Co-Founder', bio: 'Co-founder and former CEO and Chairman of Qualcomm. Electrical engineer and philanthropist who helped pioneer CDMA technology.' }], connections: [] });
ae('United States', { name: 'Broadcom', id: slug('Broadcom'), type: 'semiconductor company', category: 'Technology', description: 'Broadcom Inc. is a global technology company that designs, develops, and supplies semiconductor and infrastructure software solutions. With revenues exceeding $35 billion, Broadcom is one of the largest chip companies in the world, serving data centers, networking, broadband, and wireless markets.', website: 'https://www.broadcom.com', founded: 1991, individuals: [{ id: slug('Hock Tan'), name: 'Hock Tan', role: 'CEO', bio: 'CEO of Broadcom. Malaysian-born American billionaire who grew Broadcom through aggressive acquisitions including VMware.' }], connections: [] });
ae('United States', { name: 'Palantir Technologies', id: slug('Palantir Technologies'), type: 'data analytics', category: 'Technology', description: 'Palantir Technologies is a public American software company that specializes in big data analytics. Founded in 2003 with funding from Peter Thiel and the CIA\'s venture capital arm In-Q-Tel, Palantir builds software platforms (Gotham and Foundry) for government intelligence agencies and large corporations to integrate, manage, and analyze data.', website: 'https://www.palantir.com', founded: 2003, individuals: [{ id: slug('Alex Karp'), name: 'Alex Karp', role: 'CEO', bio: 'Co-founder and CEO of Palantir Technologies. Holds a doctorate in philosophy from Goethe University Frankfurt.' }, { id: slug('Peter Thiel'), name: 'Peter Thiel', role: 'Co-Founder & Chairman', bio: 'Co-founder of Palantir and PayPal. German-American billionaire venture capitalist and political figure.' }], connections: [] });
ae('United States', { name: 'Zoom Video Communications', id: slug('Zoom Video Communications'), type: 'video communications', category: 'Technology', description: 'Zoom Video Communications is a communications technology company that provides video telephony and online chat services. Founded by Eric Yuan, Zoom became ubiquitous during the COVID-19 pandemic and is now a core business communications platform used by millions globally.', website: 'https://www.zoom.us', founded: 2011, individuals: [{ id: slug('Eric Yuan'), name: 'Eric Yuan', role: 'Founder & CEO', bio: 'Founder and CEO of Zoom. Chinese-American billionaire who created one of the most widely used communication platforms.' }], connections: [] });
ae('United States', { name: 'Uber Technologies', id: slug('Uber Technologies'), type: 'ride-sharing/technology', category: 'Technology', description: 'Uber Technologies is a technology company that operates a ride-hailing platform, food delivery service (Uber Eats), and freight brokerage. Founded in 2009, Uber disrupted the global transportation industry and operates in over 70 countries.', website: 'https://www.uber.com', founded: 2009, individuals: [{ id: slug('Dara Khosrowshahi'), name: 'Dara Khosrowshahi', role: 'CEO', bio: 'CEO of Uber Technologies since 2017. Iranian-American businessman and former CEO of Expedia Group.' }, { id: slug('Travis Kalanick'), name: 'Travis Kalanick', role: 'Co-Founder', bio: 'Co-founder and former CEO of Uber. Stepped down in 2017.' }], connections: [] });
ae('United States', { name: 'Airbnb', id: slug('Airbnb'), type: 'hospitality platform', category: 'Technology', description: 'Airbnb is an online marketplace for lodging, primarily homestays and tourism experiences. Founded in 2008, it has disrupted the global hospitality industry with over 7 million listings worldwide. The platform enables hosts to rent out their properties to guests.', website: 'https://www.airbnb.com', founded: 2008, individuals: [{ id: slug('Brian Chesky'), name: 'Brian Chesky', role: 'Co-Founder & CEO', bio: 'Co-founder and CEO of Airbnb. Transformed the hospitality industry with the home-sharing platform.' }], connections: [] });
ae('United States', { name: 'Stripe', id: slug('Stripe'), type: 'fintech company', category: 'Technology', description: 'Stripe is a financial technology company that provides payment processing software and APIs for internet businesses. Founded in 2010 by Irish brothers Patrick and John Collison, Stripe processes hundreds of billions of dollars annually and is one of the most valuable private technology companies.', website: 'https://stripe.com', founded: 2010, individuals: [], connections: [] });

// ===== REAL ESTATE & PROPERTY =====
ae('United States', { name: 'Related Companies', id: slug('Related Companies'), type: 'real estate development', category: 'Real Estate & Property', description: 'Related Companies is one of the largest privately held real estate firms in the United States, best known for developing Hudson Yards on Manhattan\'s Far West Side, the largest private real estate development in US history. The firm has developed over $60 billion in real estate across residential, commercial, and mixed-use projects.', website: 'https://www.related.com', founded: 1972, individuals: [{ id: slug('Stephen M. Ross'), name: 'Stephen M. Ross', role: 'Founder & Chairman', bio: 'Founder and Chairman of Related Companies. Billionaire developer behind Hudson Yards. Owner of the Miami Dolphins.' }], connections: [{ name: 'Brookfield Properties', type: 'industry peer', description: 'Both are major real estate development firms in New York.' }] });
ae('United States', { name: 'Vornado Realty Trust', id: slug('Vornado Realty Trust'), type: 'REIT', category: 'Real Estate & Property', description: 'Vornado Realty Trust is one of the largest real estate investment trusts in the United States, focused on office and retail properties in New York City. The company owns and manages over 19 million square feet of Manhattan office space, making it one of the borough\'s largest landlords.', website: 'https://www.vno.com', founded: 1982, individuals: [{ id: slug('Steven Roth'), name: 'Steven Roth', role: 'Chairman & CEO', bio: 'Founder, Chairman and CEO of Vornado Realty Trust. Billionaire real estate developer and one of Manhattan\'s most powerful landlords.' }], connections: [] });
ae('United States', { name: 'Tishman Speyer', id: slug('Tishman Speyer'), type: 'real estate', category: 'Real Estate & Property', description: 'Tishman Speyer is one of the leading owners, developers, operators, and fund managers of first-class real estate worldwide. The firm owns iconic properties including Rockefeller Center, the Chrysler Building, and the Spiral in New York, as well as major developments in cities globally.', website: 'https://www.tishmanspeyer.com', founded: 1978, individuals: [{ id: slug('Jerry Speyer'), name: 'Jerry Speyer', role: 'Chairman', bio: 'Chairman and Co-CEO of Tishman Speyer. Billionaire real estate developer who led the acquisition of Rockefeller Center.' }, { id: slug('Rob Speyer'), name: 'Rob Speyer', role: 'President & CEO', bio: 'President and CEO of Tishman Speyer. Son of Jerry Speyer, leads the firm\'s global operations.' }], connections: [{ name: 'Related Companies', type: 'industry peer', description: 'Both are leading New York real estate developers.' }] });
ae('United States', { name: 'RXR Realty', id: slug('RXR Realty'), type: 'real estate', category: 'Real Estate & Property', description: 'RXR Realty is a vertically integrated real estate company that operates across the New York metro area, managing, developing, and investing in commercial and residential properties. The firm manages a portfolio of over 30 million square feet.', website: 'https://www.rxrrealty.com', founded: 2007, individuals: [{ id: slug('Scott Rechler'), name: 'Scott Rechler', role: 'Chairman & CEO', bio: 'Chairman and CEO of RXR Realty. Prominent New York real estate executive and former vice chairman of the Port Authority.' }], connections: [] });
ae('United States', { name: 'Boston Properties', id: slug('Boston Properties'), type: 'REIT', category: 'Real Estate & Property', description: 'Boston Properties (BXP) is one of the largest publicly traded developers, owners, and managers of Class A office space in the United States. Founded by Mortimer Zuckerman, the company owns properties in Boston, New York, Washington DC, San Francisco, and other major markets.', website: 'https://www.bxp.com', founded: 1970, individuals: [{ id: slug('Mortimer Zuckerman'), name: 'Mortimer Zuckerman', role: 'Founder & Chairman Emeritus', bio: 'Founder and Chairman Emeritus of Boston Properties. Also owner/publisher of the New York Daily News and former editor of US News & World Report.' }], connections: [] });
ae('United States', { name: 'SL Green Realty', id: slug('SL Green Realty'), type: 'REIT', category: 'Real Estate & Property', description: 'SL Green Realty Corp is Manhattan\'s largest office landlord, owning interests in over 30 million square feet of commercial space in New York City. The company is a fully integrated REIT focused on acquiring, managing, and maximizing the value of Manhattan commercial properties, including One Vanderbilt, one of the tallest buildings in NYC.', website: 'https://www.slgreen.com', founded: 1997, individuals: [{ id: slug('Marc Holliday'), name: 'Marc Holliday', role: 'Chairman & CEO', bio: 'Chairman and CEO of SL Green Realty, Manhattan\'s largest office landlord.' }], connections: [{ name: 'Vornado Realty Trust', type: 'industry peer', description: 'Both are major Manhattan office landlords.' }] });

// ===== EDUCATION & ACADEMIA =====
ae('United States', { name: 'Brandeis University', id: slug('Brandeis University'), type: 'university', category: 'Education & Academia', description: 'Brandeis University is a private research university in Waltham, Massachusetts. Founded in 1948 by the American Jewish community and named after Louis Brandeis, the first Jewish Supreme Court justice, it is the only secular Jewish-sponsored university in the United States. Brandeis is known for its strong programs in social science, humanities, and the sciences.', website: 'https://www.brandeis.edu', founded: 1948, individuals: [{ id: slug('Ron Liebowitz'), name: 'Ron Liebowitz', role: 'President', bio: 'President of Brandeis University. Political geographer and former president of Middlebury College.' }], connections: [{ name: 'Yeshiva University', type: 'academic peer', description: 'Both are major Jewish-affiliated universities.' }, { name: 'Touro University', type: 'academic peer', description: 'Both are Jewish-affiliated institutions of higher learning.' }] });
ae('United States', { name: 'Jewish Theological Seminary', id: slug('Jewish Theological Seminary'), type: 'seminary', category: 'Education & Academia', description: 'The Jewish Theological Seminary of America (JTS) is the academic and spiritual center of Conservative Judaism. Founded in 1887, JTS trains rabbis, cantors, educators, and scholars and operates the JTS Library, one of the greatest collections of Judaica in the world with over 400,000 volumes.', website: 'https://www.jtsa.edu', founded: 1887, individuals: [{ id: slug('Shuly Rubin Schwartz'), name: 'Shuly Rubin Schwartz', role: 'Chancellor', bio: 'Chancellor of JTS, the first woman to lead the institution. Historian of American Jewish life.' }], connections: [{ name: 'Rabbinical Assembly', type: 'alumni organization', description: 'JTS graduates typically join the Rabbinical Assembly, the professional organization of Conservative rabbis.' }, { name: 'Hebrew Union College (HUC)', type: 'academic peer', description: 'Both are major rabbinical seminaries in the United States.' }] });
ae('United States', { name: 'Yeshiva University', id: slug('Yeshiva University'), type: 'university', category: 'Education & Academia', description: 'Yeshiva University is a private Orthodox Jewish university in New York City. Founded in 1886, it is the oldest and most comprehensive educational institution under Jewish auspices in America. YU includes the Albert Einstein College of Medicine, the Benjamin N. Cardozo School of Law, and the Rabbi Isaac Elchanan Theological Seminary (RIETS), the largest Orthodox rabbinical seminary in the world.', website: 'https://www.yu.edu', founded: 1886, individuals: [{ id: slug('Ari Berman'), name: 'Ari Berman', role: 'President', bio: 'President of Yeshiva University. Orthodox rabbi and scholar who became president in 2017.' }], connections: [{ name: 'Brandeis University', type: 'academic peer', description: 'Both are major Jewish-affiliated universities.' }, { name: 'Jewish Theological Seminary', type: 'academic peer', description: 'Both are major Jewish educational institutions in New York.' }] });
ae('United States', { name: 'Hillel International', id: slug('Hillel International'), type: 'campus organization', category: 'Education & Academia', description: 'Hillel International is the world\'s largest Jewish campus organization, engaging college students at more than 850 colleges and universities across North America and around the world. Founded in 1923 at the University of Illinois, Hillel provides Jewish life programming, social events, Israel engagement, and community service opportunities for Jewish students.', website: 'https://www.hillel.org', founded: 1923, individuals: [{ id: slug('Adam Lehman'), name: 'Adam Lehman', role: 'President & CEO', bio: 'President and CEO of Hillel International. Former technology executive.' }], connections: [{ name: 'The Jewish Federations of North America', type: 'funder', description: 'Jewish Federations collectively fund Hillel campus operations.' }, { name: 'Birthright Israel', type: 'partner', description: 'Hillel helps promote and support Birthright Israel trips on campuses.' }] });

// ===== ADVOCACY & PUBLIC AFFAIRS =====
ae('United States', { name: 'J Street', id: slug('J Street'), type: 'advocacy organization', category: 'Advocacy & Public Affairs', description: 'J Street is a liberal American Jewish advocacy organization that promotes American leadership to end the Israeli-Palestinian conflict peacefully through a two-state solution. Founded in 2008, it serves as a counterweight to more hawkish pro-Israel organizations and operates a political action committee supporting candidates who favor diplomatic solutions.', website: 'https://jstreet.org', founded: 2008, individuals: [{ id: slug('Jeremy Ben-Ami'), name: 'Jeremy Ben-Ami', role: 'President', bio: 'Founder and president of J Street. Former domestic policy adviser in the Clinton White House.' }], connections: [{ name: 'AIPAC (American Israel Public Affairs Committee)', type: 'ideological counterpart', description: 'J Street positions itself as a dovish alternative to AIPAC on Israel policy.' }] });
ae('United States', { name: 'Zionist Organization of America', id: slug('Zionist Organization of America'), type: 'Zionist organization', category: 'Advocacy & Public Affairs', description: 'The Zionist Organization of America (ZOA) is the oldest pro-Israel organization in the United States, founded in 1897. It advocates for strong US-Israel relations and takes hawkish positions on Israeli security and sovereignty issues. ZOA hosts an annual gala dinner that attracts major political figures.', website: 'https://zoa.org', founded: 1897, individuals: [{ id: slug('Morton Klein'), name: 'Morton Klein', role: 'National President', bio: 'National President of the Zionist Organization of America. Holocaust survivor from a displaced persons camp who became a leading pro-Israel activist.' }], connections: [{ name: 'World Zionist Organization', type: 'affiliate', description: 'ZOA is affiliated with the World Zionist Organization.' }] });
ae('United States', { name: 'Jewish Council for Public Affairs', id: slug('Jewish Council for Public Affairs'), type: 'advocacy umbrella', category: 'Advocacy & Public Affairs', description: 'The Jewish Council for Public Affairs (JCPA) is the umbrella body for Jewish community relations agencies across the United States. It coordinates public affairs activities of 16 national Jewish organizations and 125 local Jewish community relations councils, working on domestic policy issues including civil rights, social justice, and religious freedom.', website: 'https://www.jewishpublicaffairs.org', founded: 1944, individuals: [], connections: [{ name: 'The Jewish Federations of North America', type: 'communal partner', description: 'JCPA works closely with the federation system on public affairs.' }] });
ae('United States', { name: 'Simon Wiesenthal Center', id: slug('Simon Wiesenthal Center'), type: 'human rights organization', category: 'Advocacy & Public Affairs', description: 'The Simon Wiesenthal Center is a global Jewish human rights organization that confronts antisemitism and hate, defends the safety of Jews worldwide, and teaches the lessons of the Holocaust. Named after the famed Nazi hunter, the center operates the Museum of Tolerance in Los Angeles and Jerusalem and has over 400,000 member families.', website: 'https://www.wiesenthal.com', founded: 1977, individuals: [{ id: slug('Marvin Hier'), name: 'Marvin Hier', role: 'Founder & Dean', bio: 'Rabbi Marvin Hier is the founder and dean of the Simon Wiesenthal Center. Academy Award-winning filmmaker for Genocide documentary.' }], connections: [{ name: 'Anti-Defamation League', type: 'human rights peer', description: 'Both combat antisemitism and hate globally.' }, { name: 'Yad Vashem', type: 'Holocaust education partner', description: 'Both are leaders in Holocaust education and remembrance.' }] });
ae('United States', { name: 'American Jewish Committee', id: slug('American Jewish Committee'), type: 'advocacy organization', category: 'Advocacy & Public Affairs', description: 'The American Jewish Committee (AJC) is a global advocacy organization founded in 1906 in response to pogroms in Russia. AJC works to enhance the well-being of the Jewish people and Israel, and to advance human rights and democratic values. It operates offices worldwide and conducts the annual Survey of American Jewish Opinion.', website: 'https://www.ajc.org', founded: 1906, individuals: [{ id: slug('Ted Deutch'), name: 'Ted Deutch', role: 'CEO', bio: 'CEO of the American Jewish Committee. Former US Congressman from Florida who led the House Ethics Committee.' }], connections: [{ name: 'Anti-Defamation League', type: 'advocacy peer', description: 'Both are major American Jewish defense and advocacy organizations.' }, { name: 'Conference of Presidents of Major American Jewish Organizations', type: 'member', description: 'AJC is a member of the Conference of Presidents.' }] });

// ===== CHARITY & PHILANTHROPY =====
ae('United States', { name: 'UJA-Federation of New York', id: slug('UJA-Federation of New York'), type: 'federation', category: 'Charity & Philanthropy', description: 'UJA-Federation of New York is the largest local philanthropy in the world, raising and distributing hundreds of millions of dollars annually to support the New York Jewish community, Israel, and over 100 nonprofit agencies. It addresses food insecurity, poverty, education, community building, and emergency relief.', website: 'https://www.ujafedny.org', founded: 1917, individuals: [{ id: slug('Eric Goldstein UJA'), name: 'Eric Goldstein', role: 'CEO', bio: 'CEO of UJA-Federation of New York, the largest local philanthropy in the world.' }], connections: [{ name: 'The Jewish Federations of North America', type: 'member federation', description: 'UJA-Federation is the largest member federation of JFNA.' }, { name: 'HIAS (Hebrew Immigrant Aid Society)', type: 'grantee', description: 'UJA-Federation provides funding to HIAS for refugee services.' }] });
ae('United States', { name: 'Jewish Community Centers Association', id: slug('Jewish Community Centers Association'), type: 'community organization', category: 'Community & Social Organizations', description: 'The Jewish Community Centers Association of North America (JCCA) supports over 170 JCCs, YM-YWHAs, and camp sites across the US and Canada. Collectively, JCCs serve over 1.5 million people weekly through fitness, education, cultural, and social programs. JCCs serve both Jewish and non-Jewish community members.', website: 'https://www.jcca.org', founded: 1917, individuals: [], connections: [{ name: 'The Jewish Federations of North America', type: 'communal partner', description: 'JCCs are core agencies supported by the Jewish federation system.' }] });
ae('United States', { name: 'Claims Conference', id: slug('Claims Conference'), type: 'restitution organization', category: 'Charity & Philanthropy', description: 'The Conference on Jewish Material Claims Against Germany (Claims Conference) negotiates for and distributes compensation to Holocaust survivors worldwide. Since 1951, it has secured approximately $90 billion in indemnification and restitution from Germany and Austria for Holocaust survivors and their heirs. It also funds Holocaust education, research, and documentation programs globally.', website: 'https://www.claimscon.org', founded: 1951, individuals: [{ id: slug('Gideon Taylor'), name: 'Gideon Taylor', role: 'President', bio: 'President of the Claims Conference which has secured over $90 billion for Holocaust survivors.' }], connections: [{ name: 'Yad Vashem', type: 'partner', description: 'Both organizations are central to Holocaust remembrance and survivor support.' }] });
ae('United States', { name: 'Charles and Lynn Schusterman Family Foundation', id: slug('Charles and Lynn Schusterman Family Foundation'), type: 'foundation', category: 'Philanthropy & Foundations', description: 'The Charles and Lynn Schusterman Family Philanthropies is one of the largest Jewish philanthropies in the United States. It invests in strengthening Jewish life and Israel, education, and social justice initiatives. The foundation has distributed over $2 billion in grants since its founding.', website: 'https://www.schusterman.org', founded: 1987, individuals: [{ id: slug('Stacy Schusterman'), name: 'Stacy Schusterman', role: 'Chair', bio: 'Chair of Charles and Lynn Schusterman Family Philanthropies. Daughter of founder Charles Schusterman.' }], connections: [{ name: 'Birthright Israel', type: 'funder', description: 'Schusterman is a major funder of Birthright Israel.' }, { name: 'ROI Community', type: 'initiative', description: 'Schusterman created the ROI Community of young Jewish innovators.' }] });
ae('United States', { name: 'Jim Joseph Foundation', id: slug('Jim Joseph Foundation'), type: 'foundation', category: 'Philanthropy & Foundations', description: 'The Jim Joseph Foundation is one of the largest funders of Jewish education in the United States, with a $2 billion endowment. Named after its founder, a Northern California real estate developer, the foundation invests exclusively in Jewish education for young American Jews, including day schools, camps, campus life, and experiential learning.', website: 'https://jimjosephfoundation.org', founded: 2006, individuals: [], connections: [{ name: 'Foundation for Jewish Camp', type: 'grantee', description: 'Jim Joseph Foundation is a major funder of Jewish camping.' }, { name: 'Hillel International', type: 'grantee', description: 'Major funder of Hillel campus programming.' }] });
ae('United States', { name: 'Marcus Foundation', id: slug('Marcus Foundation'), type: 'foundation', category: 'Philanthropy & Foundations', description: 'The Marcus Foundation was established by Bernie Marcus, co-founder of The Home Depot. The foundation has donated over $2 billion to causes including the Georgia Aquarium, medical research, veteran support, Jewish causes, and free enterprise advocacy. Marcus is a major supporter of Israeli and Jewish causes.', website: 'https://www.marcusfoundation.org', founded: 1989, individuals: [{ id: slug('Bernie Marcus'), name: 'Bernie Marcus', role: 'Founder & Chairman', bio: 'Co-founder of The Home Depot. Billionaire philanthropist and major donor to Jewish and Israeli causes.' }], connections: [{ name: 'Birthright Israel', type: 'major donor', description: 'Bernie Marcus has been one of the largest individual donors to Birthright Israel.' }] });

// ===== FOOD & BEVERAGE =====
ae('United States', { name: 'Starbucks Corporation', id: slug('Starbucks Corporation'), type: 'coffeehouse chain', category: 'Food & Beverage', description: 'Starbucks Corporation is the world\'s largest coffeehouse chain with over 35,000 stores across 80 countries. Under former chairman Howard Schultz, Starbucks transformed from a small Seattle coffee bean retailer into a global brand that changed coffee culture worldwide.', website: 'https://www.starbucks.com', founded: 1971, individuals: [{ id: slug('Howard Schultz'), name: 'Howard Schultz', role: 'Former Chairman & CEO', bio: 'Former Chairman and CEO of Starbucks who built the company from 11 stores to a global empire. Brooklyn-raised son of a truck driver. Ran briefly for US president in 2020.' }], connections: [] });
ae('United States', { name: 'Levi Strauss & Co.', id: slug('Levi Strauss & Co.'), type: 'apparel company', category: 'Fashion & Consumer Goods', description: 'Levi Strauss & Co. is an American clothing company known worldwide for its Levi\'s brand of denim jeans. Founded in 1853 by Bavarian-born Jewish immigrant Levi Strauss during the California Gold Rush, the company invented blue jeans and remains the world\'s largest jeans manufacturer.', website: 'https://www.levistrauss.com', founded: 1853, individuals: [{ id: slug('Levi Strauss'), name: 'Levi Strauss', role: 'Founder', bio: 'Bavarian-born Jewish immigrant who founded Levi Strauss & Co. during the California Gold Rush and invented blue jeans.' }], connections: [] });
ae('United States', { name: 'Estee Lauder Companies', id: slug('Estee Lauder Companies'), type: 'cosmetics conglomerate', category: 'Fashion & Consumer Goods', description: 'The Estee Lauder Companies is one of the world\'s largest manufacturers and marketers of prestige skincare, makeup, fragrance, and hair care products. Founded in 1946 by Estee Lauder, a Jewish American entrepreneur, the company owns brands including Estee Lauder, Clinique, MAC, La Mer, Bobbi Brown, and Tom Ford Beauty. The Lauder family remains the controlling shareholders.', website: 'https://www.elcompanies.com', founded: 1946, individuals: [{ id: slug('William Lauder'), name: 'William Lauder', role: 'Executive Chairman', bio: 'Executive Chairman of Estee Lauder Companies. Grandson of founder Estee Lauder and son of Ronald Lauder (WJC president).' }, { id: slug('Ronald Lauder'), name: 'Ronald Lauder', role: 'Board Member & WJC President', bio: 'Son of Estee Lauder. President of the World Jewish Congress. Former US Ambassador to Austria. Major art collector and philanthropist.' }], connections: [{ name: 'World Jewish Congress', type: 'leadership connection', description: 'Ronald Lauder serves as president of the World Jewish Congress.' }] });
ae('United States', { name: 'Ralph Lauren Corporation', id: slug('Ralph Lauren Corporation'), type: 'fashion company', category: 'Fashion & Consumer Goods', description: 'Ralph Lauren Corporation is a global leader in the design, marketing, and distribution of premium lifestyle products including apparel, accessories, home furnishings, and fragrances. Founded in 1967 by Ralph Lauren (born Ralph Lifshitz), the son of Ashkenazi Jewish immigrants from Belarus, the company has become synonymous with American style.', website: 'https://www.ralphlauren.com', founded: 1967, individuals: [{ id: slug('Ralph Lauren'), name: 'Ralph Lauren', role: 'Founder & Executive Chairman', bio: 'Founder and Executive Chairman of Ralph Lauren Corporation. Born Ralph Lifshitz in the Bronx to Ashkenazi Jewish immigrants. One of the most influential fashion designers in history.' }], connections: [] });
ae('United States', { name: 'Calvin Klein', id: slug('Calvin Klein'), type: 'fashion brand', category: 'Fashion & Consumer Goods', description: 'Calvin Klein is a global fashion brand founded in 1968 by Calvin Klein, a Jewish American fashion designer from the Bronx. The brand is known for its clean, minimalist aesthetic across ready-to-wear, denim, underwear, perfume, and accessories. Now owned by PVH Corp.', website: 'https://www.calvinklein.us', founded: 1968, individuals: [{ id: slug('Calvin Klein person'), name: 'Calvin Klein', role: 'Founder', bio: 'Founder of Calvin Klein fashion brand. Revolutionary American fashion designer known for his minimalist aesthetic.' }], connections: [{ name: 'Ralph Lauren Corporation', type: 'industry peer', description: 'Both are iconic American fashion brands founded by Jewish designers.' }] });

// ===== SPORTS =====
ae('United States', { name: 'New England Patriots', id: slug('New England Patriots'), type: 'NFL franchise', category: 'Sports', description: 'The New England Patriots are a professional football franchise in the NFL owned by Robert Kraft since 1994. Under Kraft\'s ownership, the Patriots became the most successful NFL franchise of the 21st century, winning six Super Bowls. Kraft is a prominent Jewish philanthropist and supporter of Israel.', website: 'https://www.patriots.com', founded: 1959, individuals: [{ id: slug('Robert Kraft'), name: 'Robert Kraft', role: 'Owner & Chairman', bio: 'Owner of the New England Patriots since 1994. Billionaire businessman and major Jewish philanthropist. Strong supporter of Israel.' }], connections: [] });
ae('United States', { name: 'New York Giants', id: slug('New York Giants'), type: 'NFL franchise', category: 'Sports', description: 'The New York Giants are a professional football franchise in the NFL. The team has been owned by the Mara and Tisch families. Steve Tisch, of the Tisch family (Loews Corporation), serves as co-owner and chairman.', website: 'https://www.giants.com', founded: 1925, individuals: [{ id: slug('Steve Tisch'), name: 'Steve Tisch', role: 'Co-Owner & Chairman', bio: 'Co-owner and chairman of the New York Giants. Film producer and billionaire. Member of the Tisch family (Loews Corporation).' }], connections: [] });
ae('United States', { name: 'Golden State Warriors', id: slug('Golden State Warriors'), type: 'NBA franchise', category: 'Sports', description: 'The Golden State Warriors are a professional basketball franchise in the NBA owned by Joe Lacob and Peter Guber since 2010. Under their ownership, the Warriors have won four NBA championships and become one of the most valuable sports franchises in the world.', website: 'https://www.warriors.com', founded: 1946, individuals: [{ id: slug('Joe Lacob'), name: 'Joe Lacob', role: 'Governor & CEO', bio: 'Governor and CEO of the Golden State Warriors. Venture capitalist and former partner at Kleiner Perkins.' }], connections: [] });
ae('United States', { name: 'Los Angeles Clippers', id: slug('Los Angeles Clippers'), type: 'NBA franchise', category: 'Sports', description: 'The Los Angeles Clippers are a professional basketball franchise in the NBA. Previously owned by Donald Sterling, the team was purchased by Steve Ballmer in 2014. The team plays at the new Intuit Dome in Inglewood, California.', website: 'https://www.clippers.com', founded: 1970, individuals: [{ id: slug('Steve Ballmer'), name: 'Steve Ballmer', role: 'Owner', bio: 'Owner of the Los Angeles Clippers. Former CEO of Microsoft and one of the wealthiest people in the world.' }], connections: [] });
ae('United States', { name: 'Brooklyn Nets', id: slug('Brooklyn Nets'), type: 'NBA franchise', category: 'Sports', description: 'The Brooklyn Nets are a professional basketball franchise in the NBA playing at Barclays Center in Brooklyn. The team was previously owned by Russian-Israeli billionaire Mikhail Prokhorov and was purchased by Taiwanese-Canadian businessman Joe Tsai.', website: 'https://www.nba.com/nets', founded: 1967, individuals: [], connections: [] });
ae('United States', { name: 'Miami Heat', id: slug('Miami Heat'), type: 'NBA franchise', category: 'Sports', description: 'The Miami Heat are a professional basketball franchise in the NBA. The team is owned by Micky Arison, the former chairman and CEO of Carnival Corporation, the world\'s largest cruise line operator. Arison, an Israeli-American, inherited the team from his father Ted Arison.', website: 'https://www.heat.com', founded: 1988, individuals: [{ id: slug('Micky Arison'), name: 'Micky Arison', role: 'Managing General Partner', bio: 'Owner of the Miami Heat. Israeli-American billionaire and former CEO of Carnival Corporation.' }], connections: [] });

// ===== HEALTHCARE & PHARMACEUTICALS =====
ae('United States', { name: 'Teva Pharmaceutical (US Operations)', id: slug('Teva Pharmaceutical US'), type: 'pharmaceutical company', category: 'Healthcare & Pharmaceuticals', description: 'Teva Pharmaceutical Industries US operations represent the American arm of the world\'s largest generic drug manufacturer. Teva\'s US business includes its generic pharmaceuticals division, specialty medicines, and biosimilars. The US market is Teva\'s largest, generating over 40% of the company\'s global revenues.', website: 'https://www.tevapharm.com', founded: 1985, individuals: [], connections: [{ name: 'Teva Pharmaceutical Industries', type: 'parent company', description: 'Israeli-headquartered global pharmaceutical company.' }] });
ae('United States', { name: 'Mount Sinai Health System', id: slug('Mount Sinai Health System'), type: 'hospital system', category: 'Healthcare & Pharmaceuticals', description: 'Mount Sinai Health System is one of the largest academic medical systems in the New York metropolitan area, encompassing the Icahn School of Medicine at Mount Sinai and eight hospital campuses. Founded in 1852 as Jews\' Hospital, it was one of the first hospitals in the US to serve patients regardless of race, religion, or ability to pay.', website: 'https://www.mountsinai.org', founded: 1852, individuals: [{ id: slug('Dennis Charney'), name: 'Dennis Charney', role: 'Dean, Icahn School of Medicine', bio: 'Dean of the Icahn School of Medicine at Mount Sinai. Leading psychiatrist and neuroscientist.' }], connections: [{ name: 'Albert Einstein Israelite Hospital', type: 'medical peer', description: 'Both are Jewish-founded hospital systems with major research programs.' }] });
ae('United States', { name: 'Cedars-Sinai Medical Center', id: slug('Cedars-Sinai Medical Center'), type: 'hospital', category: 'Healthcare & Pharmaceuticals', description: 'Cedars-Sinai Medical Center is a nonprofit academic healthcare organization and one of the largest hospitals in the western United States. Located in Los Angeles, it was formed through the merger of Cedars of Lebanon Hospital and Mount Sinai Hospital. The hospital is particularly famous for treating Hollywood celebrities and is a leading research institution.', website: 'https://www.cedars-sinai.org', founded: 1902, individuals: [], connections: [{ name: 'Mount Sinai Health System', type: 'medical peer', description: 'Both are major Jewish-founded hospital systems.' }] });
ae('United States', { name: 'Montefiore Medical Center', id: slug('Montefiore Medical Center'), type: 'hospital system', category: 'Healthcare & Pharmaceuticals', description: 'Montefiore Medical Center is a major academic medical center in the Bronx, New York. Named after Sir Moses Montefiore, the Victorian-era Jewish philanthropist, it serves as the university hospital for Albert Einstein College of Medicine. Montefiore is one of the largest employers in New York City and provides care to over 3 million patients annually.', website: 'https://www.montefiore.org', founded: 1884, individuals: [], connections: [{ name: 'Yeshiva University', type: 'academic affiliate', description: 'Albert Einstein College of Medicine, affiliated with Montefiore, is part of Yeshiva University\'s academic network.' }] });

// ===== LAW FIRMS =====
ae('United States', { name: 'Skadden, Arps, Slate, Meagher & Flom', id: slug('Skadden Arps'), type: 'law firm', category: 'Law Firms', description: 'Skadden, Arps, Slate, Meagher & Flom (Skadden) is one of the largest and most prestigious law firms in the world with over 1,700 attorneys across 22 offices globally. Founded in 1948, Skadden pioneered hostile takeover defense tactics and is a leading firm in mergers and acquisitions, corporate finance, and litigation.', website: 'https://www.skadden.com', founded: 1948, individuals: [], connections: [{ name: 'Kirkland & Ellis', type: 'industry peer', description: 'Both are among the highest-grossing law firms in the world.' }] });
ae('United States', { name: 'Wachtell, Lipton, Rosen & Katz', id: slug('Wachtell Lipton'), type: 'law firm', category: 'Law Firms', description: 'Wachtell, Lipton, Rosen & Katz is a prominent American law firm based in New York City, renowned for its mergers and acquisitions practice. Founded in 1965, the firm is known for having the highest revenue per lawyer of any law firm in the world. Herbert Wachtell and Martin Lipton co-founded the firm; Lipton invented the "poison pill" takeover defense.', website: 'https://www.wlrk.com', founded: 1965, individuals: [{ id: slug('Martin Lipton'), name: 'Martin Lipton', role: 'Co-Founder', bio: 'Co-founder of Wachtell Lipton. Inventor of the "poison pill" takeover defense. One of the most influential corporate lawyers in history.' }], connections: [{ name: 'Skadden, Arps, Slate, Meagher & Flom', type: 'industry peer', description: 'Both are elite M&A law firms based in New York.' }] });
ae('United States', { name: 'Paul, Weiss, Rifkind, Wharton & Garrison', id: slug('Paul Weiss'), type: 'law firm', category: 'Law Firms', description: 'Paul, Weiss, Rifkind, Wharton & Garrison is one of the preeminent international law firms, known for its practices in corporate law, litigation, and restructuring. The firm traces its roots to 1875 and played a significant role in the civil rights movement. It has represented numerous Fortune 500 companies and major financial institutions.', website: 'https://www.paulweiss.com', founded: 1875, individuals: [], connections: [] });
ae('United States', { name: 'Fried, Frank, Harris, Shriver & Jacobson', id: slug('Fried Frank'), type: 'law firm', category: 'Law Firms', description: 'Fried, Frank, Harris, Shriver & Jacobson is a major international law firm based in New York City. Known for its expertise in corporate transactions, real estate, restructuring, and government contracts. The firm is one of the most profitable law firms in the United States.', website: 'https://www.friedfrank.com', founded: 1971, individuals: [], connections: [] });
ae('United States', { name: 'Schulte Roth & Zabel', id: slug('Schulte Roth & Zabel'), type: 'law firm', category: 'Law Firms', description: 'Schulte Roth & Zabel is a law firm based in New York City known for its dominant position in investment management and hedge fund law. The firm represents many of the world\'s largest hedge funds and private equity firms and is considered the go-to law firm for the alternative investment industry.', website: 'https://www.srz.com', founded: 1969, individuals: [], connections: [] });

// ===== RETAIL & E-COMMERCE =====
ae('United States', { name: 'Costco Wholesale', id: slug('Costco Wholesale'), type: 'retail chain', category: 'Retail & Consumer Goods', description: 'Costco Wholesale is the world\'s third-largest retailer and the world\'s largest membership-only warehouse club. Co-founded in 1983 by Jeffrey Brotman and Jim Sinegal, Costco operates over 870 warehouses globally and is known for its bulk merchandise, low prices, and high employee satisfaction. Brotman, a Jewish American, served as the company\'s founding chairman.', website: 'https://www.costco.com', founded: 1983, individuals: [{ id: slug('Jeffrey Brotman'), name: 'Jeffrey Brotman', role: 'Co-Founder', bio: 'Co-founder and former chairman of Costco Wholesale. Jewish American businessman who built one of the world\'s largest retailers. Died 2017.' }], connections: [] });

console.log(`Added ${added} new US entries`);

// ============================================================
// REBUILD AFFILIATIONS
// ============================================================
console.log('Rebuilding affiliations...');
const affMap = {};
for (const country in data.countries) {
  for (const entry of data.countries[country]) {
    for (const ind of (entry.individuals || [])) {
      if (!affMap[ind.id]) affMap[ind.id] = [];
      affMap[ind.id].push({ organization: entry.name, role: ind.role || 'Associated', entryId: entry.id, country: country });
    }
  }
}
let affCount = 0;
for (const pid in peopleData.people) {
  if (!peopleData.people[pid].affiliations) peopleData.people[pid].affiliations = [];
  if (affMap[pid]) {
    for (const aff of affMap[pid]) {
      if (!peopleData.people[pid].affiliations.some(a => a.entryId === aff.entryId)) {
        peopleData.people[pid].affiliations.push(aff);
        affCount++;
      }
    }
  }
}
console.log(`Updated ${affCount} affiliations`);

// SAVE
fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
fs.writeFileSync(peoplePath, JSON.stringify(peopleData, null, 2));

let t = 0, tc = 0;
for (const c in data.countries) { t += data.countries[c].length; data.countries[c].forEach(e => { if (e.connections) tc += e.connections.length; }); }
console.log(`\nTotal entries: ${t} | People: ${Object.keys(peopleData.people).length} | Connections: ${tc}`);
