// expandData24.js - MASSIVE Israel + global expansion
const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '..', 'data', 'jewish.json');
const peoplePath = path.join(__dirname, '..', 'data', 'people.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const peopleData = JSON.parse(fs.readFileSync(peoplePath, 'utf8'));

function slug(s) { return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function addPerson(id, name, bio) { if (!peopleData.people[id]) peopleData.people[id] = { name, bio, notes: '', affiliations: [] }; }
function addEntry(country, entry) { if (!data.countries[country]) data.countries[country] = []; if (data.countries[country].some(e => e.id === entry.id)) return false; data.countries[country].push(entry); return true; }
let added = 0;
function ae(country, e) { if (!e.individuals) e.individuals = []; if (!e.connections) e.connections = []; if (addEntry(country, e)) added++; for (const ind of e.individuals) addPerson(ind.id, ind.name, ind.bio); }

// ===================== ISRAEL =====================
console.log('Adding Israel entries...');

ae('Israel', { name: 'Bank Hapoalim', id: slug('Bank Hapoalim'), type: 'bank', category: 'Banking & Financial Services', description: 'Bank Hapoalim is Israel\'s largest bank by total assets, serving over 2 million customers. Founded in 1921 by the Histadrut labor federation, it provides retail, commercial, and private banking services. It has operations in major financial centers worldwide and plays a central role in Israel\'s economy.', website: 'https://www.bankhapoalim.com', founded: 1921, individuals: [{ id: slug('Dov Kotler'), name: 'Dov Kotler', role: 'CEO', bio: 'CEO of Bank Hapoalim, Israel\'s largest bank.' }], connections: [{ name: 'Bank Leumi', type: 'industry peer', description: 'Israel\'s two largest banks.' }] });
ae('Israel', { name: 'Bank Leumi', id: slug('Bank Leumi'), type: 'bank', category: 'Banking & Financial Services', description: 'Bank Leumi le-Israel is Israel\'s second-largest bank and one of its oldest financial institutions, founded in 1902 as the Anglo-Palestine Company as a subsidiary of the Jewish Colonial Trust established by Theodor Herzl. It has played a central role in financing Zionist settlement and Israel\'s economic development.', website: 'https://www.leumi.co.il', founded: 1902, individuals: [{ id: slug('Hanan Friedman'), name: 'Hanan Friedman', role: 'CEO', bio: 'CEO of Bank Leumi, one of Israel\'s oldest and largest financial institutions.' }], connections: [{ name: 'Bank Hapoalim', type: 'industry peer', description: 'Israel\'s two largest banks.' }] });
ae('Israel', { name: 'Israel Discount Bank', id: slug('Israel Discount Bank'), type: 'bank', category: 'Banking & Financial Services', description: 'Israel Discount Bank is the third-largest banking group in Israel. Founded in 1935, it provides a full range of banking services to retail, commercial, and private customers. The bank has subsidiaries and representative offices worldwide.', website: 'https://www.discountbank.co.il', founded: 1935, individuals: [], connections: [] });
ae('Israel', { name: 'Teva Pharmaceutical Industries', id: slug('Teva Pharmaceutical Industries'), type: 'pharmaceutical company', category: 'Healthcare & Pharmaceuticals', description: 'Teva Pharmaceutical Industries is the world\'s largest generic drug manufacturer and one of the largest pharmaceutical companies globally. Headquartered in Tel Aviv, Teva produces and markets generic and specialty medicines in nearly every therapeutic area. The company has operations in over 60 countries and employs approximately 40,000 people.', website: 'https://www.tevapharm.com', founded: 1901, individuals: [{ id: slug('Richard Francis Teva'), name: 'Richard Francis', role: 'CEO', bio: 'CEO of Teva Pharmaceutical Industries, the world\'s largest generic drug manufacturer.' }], connections: [] });
ae('Israel', { name: 'ICL Group', id: slug('ICL Group'), type: 'chemicals & mining', category: 'Manufacturing & Industry', description: 'ICL Group (formerly Israel Chemicals Ltd) is a global specialty minerals and chemicals company. It is a major producer of potash, phosphate, and specialty fertilizers, operating one of the world\'s largest bromine plants at the Dead Sea. ICL serves agriculture, food, and industrial markets in over 180 countries.', website: 'https://www.icl-group.com', founded: 1968, individuals: [], connections: [] });
ae('Israel', { name: 'Elbit Systems', id: slug('Elbit Systems'), type: 'defense contractor', category: 'Defense & Security', description: 'Elbit Systems is an international defense electronics company engaged in a broad range of programs throughout the world. It develops and supplies a wide range of airborne, land, and naval systems and products for defense, homeland security, and commercial applications. Elbit is Israel\'s largest publicly traded defense company.', website: 'https://elbitsystems.com', founded: 1966, individuals: [{ id: slug('Bezhalel Machlis'), name: 'Bezhalel Machlis', role: 'President & CEO', bio: 'President and CEO of Elbit Systems, Israel\'s largest publicly traded defense company.' }], connections: [{ name: 'Israel Aerospace Industries', type: 'defense peer', description: 'Both are major Israeli defense companies.' }] });
ae('Israel', { name: 'Israel Aerospace Industries', id: slug('Israel Aerospace Industries'), type: 'defense & aerospace', category: 'Defense & Security', description: 'Israel Aerospace Industries (IAI) is Israel\'s largest aerospace and defense company, wholly owned by the Israeli government. IAI develops and manufactures systems for air, space, sea, land, cyber, and homeland security. It is a pioneer in the development of unmanned aerial vehicles (drones) and missile defense systems.', website: 'https://www.iai.co.il', founded: 1953, individuals: [{ id: slug('Boaz Levy'), name: 'Boaz Levy', role: 'President & CEO', bio: 'President and CEO of Israel Aerospace Industries.' }], connections: [{ name: 'Elbit Systems', type: 'defense peer', description: 'Both are major Israeli defense companies.' }, { name: 'Rafael Advanced Defense Systems', type: 'defense peer', description: 'Israel\'s three main defense companies.' }] });
ae('Israel', { name: 'Rafael Advanced Defense Systems', id: slug('Rafael Advanced Defense Systems'), type: 'defense company', category: 'Defense & Security', description: 'Rafael Advanced Defense Systems is an Israeli defense technology company. It develops and produces weapons, military, and defense technologies including the Iron Dome missile defense system, the Trophy active protection system, and the Spike missile family. Rafael is majority owned by the Israeli government.', website: 'https://www.rafael.co.il', founded: 1948, individuals: [{ id: slug('Yoav Har-Even'), name: 'Yoav Har-Even', role: 'President & CEO', bio: 'President and CEO of Rafael Advanced Defense Systems, maker of the Iron Dome.' }], connections: [{ name: 'Israel Aerospace Industries', type: 'defense peer', description: 'Both are state-owned defense companies.' }, { name: 'Raytheon', type: 'Iron Dome partner', description: 'Raytheon co-produces the Iron Dome system for the US military.' }] });
ae('Israel', { name: 'CyberArk', id: slug('CyberArk'), type: 'cybersecurity company', category: 'Technology', description: 'CyberArk is an Israeli-American cybersecurity company that specializes in privileged access management, identity security, and credential protection. Founded in 1999, CyberArk serves over half of the Fortune 500 companies and is a leader in identity security solutions.', website: 'https://www.cyberark.com', founded: 1999, individuals: [{ id: slug('Udi Mokady'), name: 'Udi Mokady', role: 'Founder & Executive Chairman', bio: 'Founder and Executive Chairman of CyberArk. Pioneer in privileged access management.' }], connections: [{ name: 'Check Point Software Technologies', type: 'cybersecurity peer', description: 'Both are leading Israeli cybersecurity companies.' }] });
ae('Israel', { name: 'SolarEdge Technologies', id: slug('SolarEdge Technologies'), type: 'solar energy', category: 'Utilities & Energy', description: 'SolarEdge Technologies is an Israeli company that develops solar inverters, power optimizers, and smart energy management solutions. Founded in 2006, it is a world leader in solar technology, helping maximize energy production from solar panels for residential, commercial, and utility-scale installations.', website: 'https://www.solaredge.com', founded: 2006, individuals: [{ id: slug('Guy Sella'), name: 'Guy Sella', role: 'Co-Founder', bio: 'Co-founder and former CEO of SolarEdge Technologies. Passed away in 2019.' }], connections: [] });
ae('Israel', { name: 'Fiverr International', id: slug('Fiverr International'), type: 'freelance marketplace', category: 'Technology', description: 'Fiverr International is an Israeli online marketplace for freelance services. Founded in 2010, the platform connects businesses with freelancers offering digital services including graphic design, programming, video editing, and content writing. Fiverr has facilitated millions of transactions globally.', website: 'https://www.fiverr.com', founded: 2010, individuals: [{ id: slug('Micha Kaufman'), name: 'Micha Kaufman', role: 'Co-Founder & CEO', bio: 'Co-founder and CEO of Fiverr, the global freelance services marketplace.' }], connections: [] });
ae('Israel', { name: 'monday.com', id: slug('monday.com'), type: 'work management platform', category: 'Technology', description: 'monday.com is an Israeli cloud-based work management platform that enables teams to build custom workflows for managing projects, processes, and everyday work. Founded in 2012, the company has grown rapidly to serve over 186,000 customers worldwide. It went public on NASDAQ in 2021.', website: 'https://monday.com', founded: 2012, individuals: [{ id: slug('Roy Mann'), name: 'Roy Mann', role: 'Co-Founder & CEO', bio: 'Co-founder and CEO of monday.com, the work management platform.' }], connections: [] });
ae('Israel', { name: 'IronSource (Unity)', id: slug('IronSource'), type: 'app monetization', category: 'Technology', description: 'IronSource was an Israeli technology company specializing in app monetization and distribution. Founded in 2010, it merged with Unity Technologies in 2022 in a deal valued at $4.4 billion. IronSource\'s platform was used by many of the world\'s top mobile app developers.', website: 'https://www.is.com', founded: 2010, individuals: [{ id: slug('Tomer Bar-Zeev'), name: 'Tomer Bar-Zeev', role: 'Co-Founder & CEO', bio: 'Co-founder and CEO of IronSource, which merged with Unity Technologies.' }], connections: [] });
ae('Israel', { name: 'Mekorot', id: slug('Mekorot'), type: 'water utility', category: 'Utilities & Energy', description: 'Mekorot is Israel\'s national water company and the country\'s largest water utility. It supplies approximately 80% of Israel\'s drinking water and operates the National Water Carrier, the largest water project in the country. Mekorot is a world leader in water management technology, desalination, and water recycling.', website: 'https://www.mekorot.co.il', founded: 1937, individuals: [], connections: [] });
ae('Israel', { name: 'Israel Electric Corporation', id: slug('Israel Electric Corporation'), type: 'electric utility', category: 'Utilities & Energy', description: 'The Israel Electric Corporation (IEC) is the largest supplier of electric power in Israel, providing electricity to approximately 2.8 million customers. It operates power plants, transmission, and distribution networks across the country. IEC is a government-owned company undergoing gradual reform and competition.', website: 'https://www.iec.co.il', founded: 1923, individuals: [], connections: [] });
ae('Israel', { name: 'Strauss Group', id: slug('Strauss Group'), type: 'food company', category: 'Food & Beverage', description: 'Strauss Group is one of Israel\'s largest food and beverage companies, producing dairy products, coffee, snacks, and dips. The company operates through partnerships with global brands including Danone and PepsiCo (Sabra hummus). Strauss products are sold in over 20 countries.', website: 'https://www.strauss-group.com', founded: 1936, individuals: [{ id: slug('Ofra Strauss'), name: 'Ofra Strauss', role: 'Chairperson', bio: 'Chairperson of Strauss Group. Third-generation leader of the Strauss family food business.' }], connections: [] });
ae('Israel', { name: 'Osem-Nestle', id: slug('Osem-Nestle'), type: 'food company', category: 'Food & Beverage', description: 'Osem is one of Israel\'s largest food manufacturers, producing snacks, pasta, breakfast cereals, and other food products. The Bamba peanut puff snack is its most iconic product. Osem was acquired by Nestle and operates as Osem-Nestle. It is one of the most recognized food brands in Israel.', website: 'https://www.osem.co.il', founded: 1942, individuals: [], connections: [] });
ae('Israel', { name: 'Beersheba Theater', id: slug('Beersheba Theater'), type: 'performing arts', category: 'Culture & Arts', description: 'The Beersheba Theater (also known as the Be\'er Sheva Theater) is one of Israel\'s leading repertory theaters, serving the Negev region. Founded in 1973, it produces original Hebrew-language plays and adaptations, contributing significantly to Israel\'s vibrant performing arts scene.', website: '', founded: 1973, individuals: [], connections: [] });
ae('Israel', { name: 'Israel Philharmonic Orchestra', id: slug('Israel Philharmonic Orchestra'), type: 'orchestra', category: 'Culture & Arts', description: 'The Israel Philharmonic Orchestra (IPO) is one of the world\'s premier orchestras. Founded in 1936 by violinist Bronislaw Huberman as the Palestine Orchestra, its inaugural concert was conducted by Arturo Toscanini. The IPO performs over 200 concerts annually and has been led by music directors including Zubin Mehta and Lahav Shani.', website: 'https://www.ipo.co.il', founded: 1936, individuals: [{ id: slug('Lahav Shani'), name: 'Lahav Shani', role: 'Music Director', bio: 'Music Director of the Israel Philharmonic Orchestra and the Berlin Philharmonic. One of the youngest conductors to lead both ensembles.' }], connections: [] });
ae('Israel', { name: 'Habima National Theatre', id: slug('Habima National Theatre'), type: 'theater', category: 'Culture & Arts', description: 'Habima is the national theater of Israel and one of the first Hebrew-language theaters in the world. Founded in Moscow in 1917 and relocated to Tel Aviv in 1931, it has been a cultural institution of enduring significance to Hebrew culture and Israeli performing arts. Habima performs at its landmark building on Habima Square in central Tel Aviv.', website: 'https://www.habima.co.il', founded: 1917, individuals: [], connections: [] });
ae('Israel', { name: 'Hebrew University of Jerusalem', id: slug('Hebrew University of Jerusalem'), type: 'university', category: 'Education & Academia', description: 'The Hebrew University of Jerusalem is Israel\'s premier university and one of the world\'s leading research institutions. Founded in 1918 and officially opened in 1925, its founders include Albert Einstein, Sigmund Freud, Martin Buber, and Chaim Weizmann. It consistently ranks among the top 100 universities in the world.', website: 'https://www.huji.ac.il', founded: 1925, individuals: [{ id: slug('Asher Cohen HUJ'), name: 'Asher Cohen', role: 'President', bio: 'President of the Hebrew University of Jerusalem.' }], connections: [{ name: 'Weizmann Institute of Science', type: 'academic peer', description: 'Both are premier Israeli research institutions.' }] });
ae('Israel', { name: 'Tel Aviv University', id: slug('Tel Aviv University'), type: 'university', category: 'Education & Academia', description: 'Tel Aviv University (TAU) is the largest university in Israel with over 30,000 students. Founded in 1956, it is a comprehensive research university comprising nine faculties covering the full spectrum of sciences, humanities, and arts. TAU is a global leader in cybersecurity, brain research, and nanotechnology.', website: 'https://www.tau.ac.il', founded: 1956, individuals: [{ id: slug('Ariel Porat'), name: 'Ariel Porat', role: 'President', bio: 'President of Tel Aviv University, Israel\'s largest university.' }], connections: [{ name: 'Hebrew University of Jerusalem', type: 'academic peer', description: 'Both are major Israeli research universities.' }] });
ae('Israel', { name: 'Ben-Gurion University of the Negev', id: slug('Ben-Gurion University of the Negev'), type: 'university', category: 'Education & Academia', description: 'Ben-Gurion University of the Negev is a public research university in Beersheba, Israel. Named after Israel\'s first prime minister David Ben-Gurion, it was founded with a mission to develop the Negev desert region. BGU is a leader in desert research, cybersecurity, water engineering, and alternative energy.', website: 'https://www.bgu.ac.il', founded: 1969, individuals: [], connections: [] });
ae('Israel', { name: 'Yad Vashem', id: slug('Yad Vashem'), type: 'Holocaust memorial', category: 'Heritage & Memorials', description: 'Yad Vashem is Israel\'s official memorial to the victims of the Holocaust. Located on Mount Herzl in Jerusalem, it is the world\'s most comprehensive Holocaust museum, research center, and archive. Yad Vashem has collected the names of over 4.8 million Holocaust victims and houses extensive archives, exhibitions, and educational programs.', website: 'https://www.yadvashem.org', founded: 1953, individuals: [{ id: slug('Dani Dayan'), name: 'Dani Dayan', role: 'Chairman', bio: 'Chairman of Yad Vashem. Former Israeli consul general in New York and chairman of the Yesha Council.' }], connections: [{ name: 'United States Holocaust Memorial Museum', type: 'partner', description: 'Both are premier Holocaust remembrance institutions.' }] });
ae('Israel', { name: 'Hadassah Medical Center', id: slug('Hadassah Medical Center'), type: 'hospital', category: 'Healthcare & Pharmaceuticals', description: 'Hadassah Medical Center is a leading medical center in Jerusalem with two hospital campuses (Ein Kerem and Mount Scopus). Operated by the Hadassah Women\'s Zionist Organization of America, it is a teaching hospital affiliated with the Hebrew University of Jerusalem and provides treatment to over one million patients annually regardless of religion or nationality.', website: 'https://www.hadassah.org.il', founded: 1934, individuals: [], connections: [{ name: 'Hebrew University of Jerusalem', type: 'academic affiliate', description: 'Hadassah serves as a teaching hospital for the Hebrew University Faculty of Medicine.' }] });
ae('Israel', { name: 'Sheba Medical Center', id: slug('Sheba Medical Center'), type: 'hospital', category: 'Healthcare & Pharmaceuticals', description: 'Sheba Medical Center (Tel HaShomer) is the largest and most comprehensive medical center in the Middle East and one of the top ten hospitals in the world. Located in Ramat Gan, it serves approximately 1.6 million patients annually. Sheba is a leader in research, innovation, and international medical cooperation.', website: 'https://www.shebaonline.org', founded: 1948, individuals: [{ id: slug('Yitshak Kreiss'), name: 'Yitshak Kreiss', role: 'Director General', bio: 'Director General of Sheba Medical Center, the largest hospital in the Middle East.' }], connections: [{ name: 'Hadassah Medical Center', type: 'medical peer', description: 'Both are leading Israeli medical centers.' }] });
ae('Israel', { name: 'Amdocs', id: slug('Amdocs'), type: 'IT services', category: 'Technology', description: 'Amdocs is a multinational corporation that provides software and services for communications, media, and entertainment companies. Originally founded in Israel, Amdocs serves the world\'s largest communications and media companies. It has over 30,000 employees worldwide and generates revenues exceeding $4.5 billion annually.', website: 'https://www.amdocs.com', founded: 1982, individuals: [], connections: [] });
ae('Israel', { name: 'Nice Systems', id: slug('Nice Systems'), type: 'enterprise software', category: 'Technology', description: 'NICE (formerly Nice Systems) is an Israeli enterprise software company that specializes in cloud and on-premises solutions for customer engagement, financial crime prevention, and public safety. NICE serves over 25,000 organizations in more than 150 countries.', website: 'https://www.nice.com', founded: 1986, individuals: [{ id: slug('Barak Eilam'), name: 'Barak Eilam', role: 'CEO', bio: 'CEO of NICE, leading the company\'s cloud transformation.' }], connections: [] });
ae('Israel', { name: 'Tower Semiconductor', id: slug('Tower Semiconductor'), type: 'semiconductor foundry', category: 'Technology', description: 'Tower Semiconductor is an Israeli specialty semiconductor foundry. The company manufactures integrated circuits for various applications including consumer electronics, industrial, automotive, medical, and aerospace & defense. Intel attempted to acquire Tower for $5.4 billion in 2022.', website: 'https://www.towersemi.com', founded: 1993, individuals: [], connections: [] });

// ===================== UNITED KINGDOM =====================
console.log('Adding UK entries...');

ae('United Kingdom', { name: 'United Synagogue', id: slug('United Synagogue'), type: 'synagogue network', category: 'Religion & Synagogues', description: 'The United Synagogue is the largest synagogue body in Europe, representing mainstream Orthodox Judaism in the United Kingdom. Founded by Act of Parliament in 1870, it comprises over 60 communities across London and the South East, serving approximately 40,000 member households.', website: 'https://www.theus.org.uk', founded: 1870, individuals: [], connections: [{ name: 'Office of the Chief Rabbi', type: 'religious authority', description: 'The Chief Rabbi serves as the religious authority for United Synagogue congregations.' }] });
ae('United Kingdom', { name: 'Office of the Chief Rabbi', id: slug('Office of the Chief Rabbi'), type: 'religious authority', category: 'Religion & Synagogues', description: 'The Office of the Chief Rabbi is the religious authority for the mainstream Orthodox Jewish community in the United Kingdom and the Commonwealth. The Chief Rabbi is one of the most prominent Jewish leaders in the world. The current holder, Ephraim Mirvis, succeeded Lord Jonathan Sacks.', website: 'https://chiefrabbi.org', founded: 1845, individuals: [{ id: slug('Ephraim Mirvis'), name: 'Ephraim Mirvis', role: 'Chief Rabbi', bio: 'Chief Rabbi of the United Hebrew Congregations of the Commonwealth since 2013. South African-born Orthodox rabbi.' }], connections: [{ name: 'United Synagogue', type: 'congregational body', description: 'The Chief Rabbi provides religious leadership to the United Synagogue.' }] });
ae('United Kingdom', { name: 'World Jewish Relief', id: slug('World Jewish Relief'), type: 'humanitarian organization', category: 'Charity & Philanthropy', description: 'World Jewish Relief is the UK Jewish community\'s humanitarian agency, providing disaster relief and long-term development aid worldwide. Founded in 1933 to help Jews fleeing Nazi persecution, it has evolved to help communities irrespective of faith, supporting livelihood programs, education, and emergency response.', website: 'https://www.worldjewishrelief.org', founded: 1933, individuals: [], connections: [{ name: 'American Jewish Joint Distribution Committee', type: 'humanitarian peer', description: 'Both are Jewish humanitarian organizations serving global needs.' }] });
ae('United Kingdom', { name: 'Jewish Care', id: slug('Jewish Care'), type: 'social care', category: 'Community & Social Organizations', description: 'Jewish Care is the largest health and social care charity serving the Jewish community in London and the South East of England. It runs over 70 care centers, supporting over 10,000 people weekly through care homes, community centers, day centers, and mental health services.', website: 'https://www.jewishcare.org', founded: 1990, individuals: [], connections: [] });
ae('United Kingdom', { name: 'United Jewish Israel Appeal', id: slug('United Jewish Israel Appeal'), type: 'fundraising organization', category: 'Charity & Philanthropy', description: 'The United Jewish Israel Appeal (UJIA) is the UK Jewish community\'s principal Israel and education charity. It funds projects in Israel, runs educational programs, and sends young British Jews on Israel experience trips. UJIA raises tens of millions of pounds annually.', website: 'https://www.ujia.org', founded: 1920, individuals: [], connections: [{ name: 'Jewish Agency for Israel', type: 'partner', description: 'UJIA funds Jewish Agency programs in Israel.' }] });
ae('United Kingdom', { name: 'Holocaust Educational Trust', id: slug('Holocaust Educational Trust'), type: 'educational charity', category: 'Heritage & Memorials', description: 'The Holocaust Educational Trust is a British charity that works to educate young people about the Holocaust and its contemporary relevance. It runs the Lessons from Auschwitz project, which has taken over 40,000 students and teachers to Auschwitz-Birkenau, and works with schools and universities across the UK.', website: 'https://www.het.org.uk', founded: 1988, individuals: [{ id: slug('Karen Pollock'), name: 'Karen Pollock', role: 'CEO', bio: 'CEO of the Holocaust Educational Trust. CBE for services to Holocaust education.' }], connections: [{ name: 'Yad Vashem', type: 'partner', description: 'Both are leaders in Holocaust education.' }] });
ae('United Kingdom', { name: 'Liberal Judaism', id: slug('Liberal Judaism'), type: 'religious movement', category: 'Religion & Synagogues', description: 'Liberal Judaism is the UK movement for progressive Jews, representing the most progressive wing of Judaism in Britain. It has over 40 member communities across the UK. Liberal Judaism was founded in 1902 and ordains both male and female rabbis. It is affiliated with the World Union for Progressive Judaism.', website: 'https://www.liberaljudaism.org', founded: 1902, individuals: [], connections: [{ name: 'World Union for Progressive Judaism', type: 'affiliate', description: 'Liberal Judaism is affiliated with WUPJ.' }] });
ae('United Kingdom', { name: 'N. M. Rothschild & Sons', id: slug('N. M. Rothschild & Sons'), type: 'investment bank', category: 'Banking & Financial Services', description: 'N. M. Rothschild & Sons is a multinational private banking and investment company, part of the Rothschild & Co group. Founded in 1811 in London by Nathan Mayer Rothschild, it is one of the oldest banking houses in the world. The bank provides financial advisory, wealth management, and merchant banking services.', website: 'https://www.rothschildandco.com', founded: 1811, individuals: [{ id: slug('Alexandre de Rothschild'), name: 'Alexandre de Rothschild', role: 'Chairman', bio: 'Chairman of Rothschild & Co. Seventh generation of the Rothschild banking dynasty.' }], connections: [{ name: 'Lazard', type: 'banking peer', description: 'Both are leading independent advisory and banking firms.' }] });
ae('United Kingdom', { name: 'Marks & Spencer', id: slug('Marks & Spencer'), type: 'retailer', category: 'Retail & Consumer Goods', description: 'Marks & Spencer (M&S) is a major British multinational retailer headquartered in London. Co-founded in 1884 by Michael Marks, a Belarusian Jewish refugee, and Thomas Spencer, M&S grew into one of the UK\'s most iconic retailers. It specializes in clothing, food, and homeware and operates over 1,000 stores worldwide.', website: 'https://www.marksandspencer.com', founded: 1884, individuals: [{ id: slug('Michael Marks M&S'), name: 'Michael Marks', role: 'Co-Founder', bio: 'Co-founder of Marks & Spencer. A Belarusian Jewish immigrant who started with a market stall in Leeds with the motto "Don\'t ask the price, it\'s a penny."' }, { id: slug('Stuart Machin'), name: 'Stuart Machin', role: 'CEO', bio: 'CEO of Marks & Spencer, leading the retailer\'s transformation.' }], connections: [] });
ae('United Kingdom', { name: 'Tesco (co-founder)', id: slug('Tesco'), type: 'retailer', category: 'Retail & Consumer Goods', description: 'Tesco is the UK\'s largest retailer and one of the world\'s largest. Founded in 1919 by Jack Cohen, the son of Jewish immigrants from Poland, from a market stall in East London. The name Tesco came from the initials of T.E. Stockwell, a tea supplier, combined with the first two letters of Cohen. Tesco now operates thousands of stores globally.', website: 'https://www.tescoplc.com', founded: 1919, individuals: [{ id: slug('Jack Cohen Tesco'), name: 'Jack Cohen', role: 'Founder', bio: 'Founder of Tesco. Son of Polish Jewish immigrants who built the UK\'s largest grocery chain from a market stall.' }], connections: [] });

// ===================== FRANCE =====================
console.log('Adding France entries...');

ae('France', { name: 'Rothschild & Co', id: slug('Rothschild & Co'), type: 'investment bank', category: 'Banking & Financial Services', description: 'Rothschild & Co is a multinational investment bank and financial services company controlled by the French and British branches of the Rothschild family. The company provides global financial advisory, wealth and asset management, and merchant banking. The Rothschild banking dynasty, founded by Mayer Amschel Rothschild in the 18th century, has been one of the most influential financial families in history.', website: 'https://www.rothschildandco.com', founded: 1838, individuals: [], connections: [{ name: 'N. M. Rothschild & Sons', type: 'family connection', description: 'Both are branches of the Rothschild banking dynasty.' }] });
ae('France', { name: 'Alliance Israelite Universelle', id: slug('Alliance Israelite Universelle'), type: 'educational organization', category: 'Education & Academia', description: 'The Alliance Israelite Universelle is the oldest international Jewish organization in the world, founded in Paris in 1860. Its original mission was to defend the civil rights of Jews worldwide and promote education. AIU established a vast network of schools across the Mediterranean and Middle East that educated hundreds of thousands of Jews, particularly Sephardic and Mizrahi communities.', website: 'https://www.aiu.org', founded: 1860, individuals: [], connections: [{ name: 'World Jewish Congress', type: 'international peer', description: 'Both are international Jewish organizations with global missions.' }] });
ae('France', { name: 'Consistoire Central', id: slug('Consistoire Central'), type: 'religious body', category: 'Religion & Synagogues', description: 'The Consistoire Central Israelite de France is the official representative body of Orthodox Judaism in France, responsible for organizing religious services, supervision of kosher food, and maintenance of synagogues. Originally established by Napoleon in 1808 as part of his reorganization of French Jewish communal life.', website: 'https://www.consistoire.org', founded: 1808, individuals: [{ id: slug('Haim Korsia'), name: 'Haim Korsia', role: 'Grand Rabbi of France', bio: 'Grand Rabbi of France since 2014. First Sephardic-origin Grand Rabbi.' }], connections: [] });
ae('France', { name: 'Keren Hayesod France', id: slug('Keren Hayesod France'), type: 'fundraising', category: 'Charity & Philanthropy', description: 'Keren Hayesod France (Appel Unifie pour Israel) is the French branch of Keren Hayesod, the global fundraising organization of the World Zionist Organization. It raises funds from the French Jewish community for immigration, absorption, and social programs in Israel.', website: 'https://www.kerenhayesod.fr', founded: 1920, individuals: [], connections: [{ name: 'Keren Hayesod', type: 'parent organization', description: 'French branch of the global Keren Hayesod fundraising organization.' }] });
ae('France', { name: 'Fonds Social Juif Unifie', id: slug('Fonds Social Juif Unifie'), type: 'welfare organization', category: 'Charity & Philanthropy', description: 'The Fonds Social Juif Unifie (FSJU, United Jewish Social Fund) is the central welfare organization of the French Jewish community. It coordinates social services, education, and cultural programs for French Jews. FSJU is a key pillar of organized French Jewish life, supporting schools, community centers, and social welfare agencies.', website: 'https://www.fsju.org', founded: 1950, individuals: [], connections: [{ name: 'CRIF', type: 'communal partner', description: 'FSJU and CRIF are both central institutions of French Jewish communal life.' }] });
ae('France', { name: 'Publicis Groupe', id: slug('Publicis Groupe'), type: 'advertising conglomerate', category: 'Advertising & PR', description: 'Publicis Groupe is one of the world\'s largest advertising and public relations companies, headquartered in Paris. Founded in 1926 by Marcel Bleustein-Blanchet, a French Jew, the company has grown to become a global leader in marketing communications, media, and digital transformation.', website: 'https://www.publicisgroupe.com', founded: 1926, individuals: [{ id: slug('Arthur Sadoun'), name: 'Arthur Sadoun', role: 'Chairman & CEO', bio: 'Chairman and CEO of Publicis Groupe, one of the world\'s largest advertising groups.' }], connections: [] });
ae('France', { name: 'BlaBlaCar', id: slug('BlaBlaCar'), type: 'ride-sharing', category: 'Technology', description: 'BlaBlaCar is a French online marketplace for carpooling, founded in 2006. It connects drivers with empty seats to passengers looking for rides on the same route. BlaBlaCar operates in 22 countries and has over 100 million members, making it the world\'s largest long-distance carpooling community.', website: 'https://www.blablacar.com', founded: 2006, individuals: [{ id: slug('Nicolas Brusson'), name: 'Nicolas Brusson', role: 'Co-Founder & CEO', bio: 'Co-founder and CEO of BlaBlaCar.' }], connections: [] });

// ===================== GERMANY =====================
console.log('Adding Germany entries...');

ae('Germany', { name: 'Axel Springer SE', id: slug('Axel Springer SE'), type: 'media company', category: 'Entertainment & Media', description: 'Axel Springer SE is one of Europe\'s largest media companies, owning Bild (Germany\'s most-read newspaper), Die Welt, Business Insider, Politico, and other major media properties. The company is known for its strong pro-Israel editorial stance and its articles of incorporation commit it to supporting Israel\'s right to exist.', website: 'https://www.axelspringer.com', founded: 1946, individuals: [{ id: slug('Mathias Dopfner'), name: 'Mathias Dopfner', role: 'CEO', bio: 'CEO of Axel Springer SE. One of the most powerful media executives in Europe.' }], connections: [] });
ae('Germany', { name: 'Abraham Geiger College', id: slug('Abraham Geiger College'), type: 'rabbinical seminary', category: 'Education & Academia', description: 'Abraham Geiger College is a rabbinical seminary in Potsdam, Germany, affiliated with the University of Potsdam. Founded in 1999, it was the first liberal rabbinical seminary established in continental Europe since the Holocaust. It trains rabbis and cantors for liberal Jewish communities across Europe.', website: 'https://www.abrahamgeigercollege.de', founded: 1999, individuals: [], connections: [{ name: 'Central Council of Jews in Germany', type: 'communal partner', description: 'AGC serves the broader German Jewish community.' }] });
ae('Germany', { name: 'Memorial to the Murdered Jews of Europe', id: slug('Memorial to the Murdered Jews of Europe'), type: 'memorial', category: 'Heritage & Memorials', description: 'The Memorial to the Murdered Jews of Europe (Holocaust Memorial) in Berlin is Germany\'s central memorial to the Jewish victims of the Holocaust. Designed by architect Peter Eisenman, the memorial consists of 2,711 concrete stelae arranged in a grid pattern on a sloping field. An underground information center documents the persecution and murder of European Jews.', website: 'https://www.stiftung-denkmal.de', founded: 2005, individuals: [], connections: [{ name: 'Jewish Museum Berlin', type: 'memorial peer', description: 'Both are major Holocaust-related sites in Berlin.' }] });

// ===================== CANADA =====================
console.log('Adding Canada entries...');

ae('Canada', { name: 'Jewish Federations of Canada-UIA', id: slug('Jewish Federations of Canada-UIA'), type: 'umbrella organization', category: 'Representative & Umbrella Bodies', description: 'The Jewish Federations of Canada - United Israel Appeal (JFC-UIA) is the national umbrella organization for Canada\'s Jewish communities. It represents Jewish Federations across Canada and coordinates national campaigns, advocacy, and connections to Israel. JFC-UIA raises and distributes funds for Jewish communities in Canada, Israel, and worldwide.', website: 'https://www.jfcuia.org', founded: 1962, individuals: [], connections: [{ name: 'The Jewish Federations of North America', type: 'American counterpart', description: 'Both are federation umbrella organizations serving their respective countries.' }] });
ae('Canada', { name: 'B\'nai Brith Canada', id: slug('B\'nai Brith Canada'), type: 'advocacy organization', category: 'Advocacy & Public Affairs', description: 'B\'nai Brith Canada is the oldest Jewish organization in Canada, founded in 1875. It combats antisemitism, racism, and bigotry through advocacy, education, and community action. B\'nai Brith Canada publishes an annual Audit of Antisemitic Incidents, a key barometer of antisemitism in the country.', website: 'https://www.bnaibrith.ca', founded: 1875, individuals: [], connections: [{ name: 'Anti-Defamation League', type: 'counterpart', description: 'B\'nai Brith Canada and ADL both combat antisemitism in North America.' }] });
ae('Canada', { name: 'Schwartz/Reisman Centre', id: slug('Schwartz Reisman Centre'), type: 'community center', category: 'Community & Social Organizations', description: 'The Schwartz/Reisman Centre is a state-of-the-art Jewish community center in Vaughan, Ontario, serving the large Jewish population of the Greater Toronto Area. It houses a fitness center, swimming pools, theater, library, and numerous program spaces for education, culture, and recreation.', website: '', founded: 2007, individuals: [], connections: [] });
ae('Canada', { name: 'Canadian Friends of Hebrew University', id: slug('Canadian Friends of Hebrew University'), type: 'support organization', category: 'Education & Academia', description: 'Canadian Friends of the Hebrew University (CFHU) raises awareness and funds in Canada for the Hebrew University of Jerusalem. It connects Canadian researchers, students, and donors with one of the world\'s top universities and supports scholarships, research, and academic exchange.', website: 'https://www.cfhu.org', founded: 1944, individuals: [], connections: [{ name: 'Hebrew University of Jerusalem', type: 'beneficiary', description: 'CFHU raises Canadian support for the Hebrew University.' }] });

// ===================== AUSTRALIA =====================
console.log('Adding Australia entries...');

ae('Australia', { name: 'Executive Council of Australian Jewry', id: slug('Executive Council of Australian Jewry'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Executive Council of Australian Jewry (ECAJ) is the peak representative body of the Australian Jewish community. Founded in 1944, it represents the community to the Australian government, media, and public on matters of concern and publishes an annual report on antisemitism in Australia.', website: 'https://www.ecaj.org.au', founded: 1944, individuals: [{ id: slug('Jillian Segal'), name: 'Jillian Segal', role: 'President', bio: 'President of the Executive Council of Australian Jewry. Accomplished Australian barrister and communal leader.' }], connections: [{ name: 'Board of Deputies of British Jews', type: 'commonwealth peer', description: 'Both are national representative bodies within Commonwealth countries.' }] });
ae('Australia', { name: 'Monash University Jewish Studies', id: slug('Monash University Jewish Studies'), type: 'academic program', category: 'Education & Academia', description: 'The Australian Centre for Jewish Civilisation at Monash University in Melbourne is one of the leading academic programs for Jewish studies in the Southern Hemisphere. It offers undergraduate and postgraduate programs in Jewish history, culture, and thought.', website: 'https://www.monash.edu', founded: 1991, individuals: [], connections: [] });
ae('Australia', { name: 'Westfield Corporation', id: slug('Westfield Corporation'), type: 'real estate', category: 'Real Estate & Property', description: 'Westfield Corporation was an Australian shopping center company founded by Frank Lowy, a Jewish Hungarian-born Australian businessman. Before its merger with Unibail-Rodamco in 2018, Westfield was one of the largest shopping mall developers in the world, operating over 100 shopping centers globally.', website: '', founded: 1960, individuals: [{ id: slug('Frank Lowy'), name: 'Frank Lowy', role: 'Founder', bio: 'Co-founder of Westfield Corporation. Hungarian-born Holocaust survivor who became one of Australia\'s richest people. Major philanthropist and supporter of Israel.' }], connections: [] });

// ===================== SOUTH AFRICA =====================
console.log('Adding South Africa entries...');

ae('South Africa', { name: 'South African Zionist Federation', id: slug('South African Zionist Federation'), type: 'Zionist organization', category: 'Advocacy & Political Organizations', description: 'The South African Zionist Federation (SAZF) is the umbrella Zionist body in South Africa, promoting Israel and Zionism within the South African Jewish community. Founded in 1898, it is one of the oldest Zionist federations in the world and represents over 30 affiliated Zionist organizations.', website: 'https://www.sazf.org', founded: 1898, individuals: [], connections: [{ name: 'World Zionist Organization', type: 'affiliate', description: 'SAZF is affiliated with the World Zionist Organization.' }] });
ae('South Africa', { name: 'Cape Town Holocaust & Genocide Centre', id: slug('Cape Town Holocaust Genocide Centre'), type: 'museum', category: 'Heritage & Memorials', description: 'The Cape Town Holocaust & Genocide Centre is a museum and educational center dedicated to the memory of the six million Jews murdered in the Holocaust and other genocides. It is the first museum in Africa dedicated to the Holocaust and serves as a leading educational institution on human rights and genocide prevention.', website: 'https://www.ctholocaust.co.za', founded: 1999, individuals: [], connections: [{ name: 'Yad Vashem', type: 'partner', description: 'Both are Holocaust education institutions.' }] });
ae('South Africa', { name: 'Nandos', id: slug('Nandos'), type: 'restaurant chain', category: 'Food & Beverage', description: 'Nando\'s is an international casual dining restaurant chain originating from South Africa. Co-founded in 1987 by Robert Brozin, a South African Jewish entrepreneur, and Fernando Duarte. Known for its peri-peri chicken, Nando\'s now operates over 1,200 restaurants in 30 countries.', website: 'https://www.nandos.com', founded: 1987, individuals: [{ id: slug('Robert Brozin'), name: 'Robert Brozin', role: 'Co-Founder', bio: 'South African Jewish entrepreneur who co-founded Nando\'s and built it into an international restaurant chain.' }], connections: [] });

// ===================== RUSSIA =====================
console.log('Adding Russia entries...');

ae('Russia', { name: 'Federation of Jewish Communities of Russia', id: slug('Federation of Jewish Communities of Russia'), type: 'communal organization', category: 'Representative & Umbrella Bodies', description: 'The Federation of Jewish Communities of Russia (FJCR) is the largest Jewish organization in Russia, representing over 170 Jewish communities across the country. Led by Chief Rabbi Berel Lazar, it operates synagogues, schools, community centers, and welfare programs throughout Russia.', website: 'https://www.fjc.ru', founded: 1999, individuals: [{ id: slug('Berel Lazar'), name: 'Berel Lazar', role: 'Chief Rabbi of Russia', bio: 'Chief Rabbi of Russia since 2000. Italian-born Chabad-Lubavitch rabbi who has rebuilt Jewish life across Russia.' }], connections: [{ name: 'Chabad', type: 'affiliated movement', description: 'FJCR is closely associated with the Chabad-Lubavitch movement.' }] });
ae('Russia', { name: 'Russian Jewish Congress', id: slug('Russian Jewish Congress'), type: 'communal organization', category: 'Representative & Umbrella Bodies', description: 'The Russian Jewish Congress (RJC) is a major Jewish organization in Russia founded in 1996 by prominent Russian Jewish businessmen. It works to strengthen Jewish community life, combat antisemitism, preserve Jewish heritage, and promote Russian-Israeli relations.', website: 'https://www.rjc.ru', founded: 1996, individuals: [], connections: [{ name: 'World Jewish Congress', type: 'affiliate', description: 'RJC is affiliated with the World Jewish Congress.' }] });

// ===================== POLAND =====================
console.log('Adding Poland entries...');

ae('Poland', { name: 'POLIN Museum of the History of Polish Jews', id: slug('POLIN Museum'), type: 'museum', category: 'Heritage & Memorials', description: 'The POLIN Museum of the History of Polish Jews is located in Warsaw on the site of the former Warsaw Ghetto. Opened in 2013, it documents the thousand-year history of Jews in Poland. The museum\'s core exhibition won the European Museum of the Year Award in 2016. POLIN has become a world-renowned institution for Jewish heritage and education.', website: 'https://www.polin.pl', founded: 2013, individuals: [], connections: [{ name: 'Yad Vashem', type: 'partner', description: 'Both are leading Jewish history and Holocaust institutions.' }, { name: 'Jewish Museum Berlin', type: 'museum peer', description: 'Both document the history of major European Jewish communities.' }] });
ae('Poland', { name: 'Foundation for the Preservation of Jewish Heritage in Poland', id: slug('Foundation Preservation Jewish Heritage Poland'), type: 'heritage organization', category: 'Heritage & Memorials', description: 'The Foundation for the Preservation of Jewish Heritage in Poland works to protect and restore Jewish heritage sites across Poland, including synagogues, cemeteries, and other historically significant places. Poland has one of the richest collections of Jewish heritage sites in Europe, many of which require preservation.', website: 'https://www.fodz.pl', founded: 2002, individuals: [], connections: [] });

// ===================== ITALY =====================  
console.log('Adding Italy entries...');

ae('Italy', { name: 'Union of Italian Jewish Communities', id: slug('Union of Italian Jewish Communities'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Union of Italian Jewish Communities (Unione delle Comunita Ebraiche Italiane, UCEI) is the umbrella organization of Italian Jewry, representing approximately 25,000 Jews across 21 communities. Italy has one of the oldest continuous Jewish communities in Europe, predating the Roman Empire.', website: 'https://www.ucei.it', founded: 1930, individuals: [], connections: [{ name: 'European Jewish Congress', type: 'affiliate', description: 'UCEI represents Italian Jewry in the European Jewish Congress.' }] });
ae('Italy', { name: 'Jewish Museum of Rome', id: slug('Jewish Museum of Rome'), type: 'museum', category: 'Heritage & Memorials', description: 'The Jewish Museum of Rome is located in the Great Synagogue of Rome complex in the historic Jewish Ghetto. It documents the over 2,000-year history of the Jewish community in Rome, one of the oldest in Europe. The museum displays ceremonial objects, textiles, and historical documents.', website: 'https://www.museoebraico.roma.it', founded: 1960, individuals: [], connections: [] });

// ===================== SPAIN =====================
console.log('Adding Spain entries...');

ae('Spain', { name: 'Federation of Jewish Communities of Spain', id: slug('Federation of Jewish Communities of Spain'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Federation of Jewish Communities of Spain (FCJE) represents the Jewish communities across Spain. Spain\'s Jewish community of approximately 40,000-50,000 is descended partly from Jews who returned after the 1492 Expulsion and partly from more recent immigrants. In 2015, Spain passed a law offering citizenship to descendants of Sephardic Jews expelled in 1492.', website: 'https://www.fcje.org', founded: 1968, individuals: [], connections: [] });
ae('Spain', { name: 'Casa Sefarad-Israel', id: slug('Casa Sefarad-Israel'), type: 'cultural center', category: 'Culture & Arts', description: 'Casa Sefarad-Israel is a Spanish government-supported institution based in Madrid dedicated to promoting cultural dialogue between Spain and the Jewish world, particularly the Sephardic heritage. It organizes cultural events, exhibitions, and educational programs exploring the shared history of Spain and the Jewish people.', website: '', founded: 2006, individuals: [], connections: [] });

// ===================== SWITZERLAND =====================
console.log('Adding Switzerland entries...');

ae('Switzerland', { name: 'Swiss Federation of Jewish Communities', id: slug('Swiss Federation of Jewish Communities'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Swiss Federation of Jewish Communities (Schweizerischer Israelitischer Gemeindebund, SIG) is the umbrella organization of Jewish communities in Switzerland. It represents approximately 18,000 Jews and advocates for the community on political and social issues, including combating antisemitism and preserving religious freedom.', website: 'https://www.swissjews.ch', founded: 1904, individuals: [], connections: [] });
ae('Switzerland', { name: 'Glencore', id: slug('Glencore'), type: 'commodities trading', category: 'Conglomerates & Holding Companies', description: 'Glencore is one of the world\'s largest commodity trading and mining companies, headquartered in Baar, Switzerland. Founded by Marc Rich, a Jewish American commodities trader, the company trades and produces metals, minerals, oil, and agricultural products. Glencore has revenues exceeding $250 billion.', website: 'https://www.glencore.com', founded: 1974, individuals: [{ id: slug('Marc Rich'), name: 'Marc Rich', role: 'Founder', bio: 'Founder of Glencore (originally Marc Rich + Co). Controversial commodities trader who was pardoned by President Clinton. Died in 2013.' }], connections: [] });

// ===================== BRAZIL =====================
console.log('Adding Brazil entries...');

ae('Brazil', { name: 'Confederacao Israelita do Brasil', id: slug('Confederacao Israelita do Brasil'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Confederacao Israelita do Brasil (CONIB) is the umbrella organization of Brazilian Jewry, representing the approximately 120,000 Jews in Brazil, Latin America\'s second-largest Jewish community. CONIB coordinates communal affairs, combats antisemitism, and represents Brazilian Jews nationally and internationally.', website: 'https://www.conib.org.br', founded: 1948, individuals: [], connections: [{ name: 'World Jewish Congress', type: 'affiliate', description: 'CONIB represents Brazilian Jewry in the World Jewish Congress.' }] });
ae('Brazil', { name: 'Safra Group', id: slug('Safra Group'), type: 'banking & investment', category: 'Banking & Financial Services', description: 'The Safra Group is a global banking and investment group controlled by the Safra family, a Sephardic Jewish banking dynasty of Lebanese-Brazilian origin. The group includes Banco Safra (Brazil\'s fifth-largest private bank), J. Safra Sarasin (Swiss private bank), and significant real estate holdings worldwide.', website: 'https://www.safra.com.br', founded: 1841, individuals: [{ id: slug('Joseph Safra'), name: 'Joseph Safra', role: 'Former Patriarch', bio: 'Former patriarch of the Safra banking dynasty. Was the richest person in Brazil before his death in 2020.' }], connections: [{ name: 'N. M. Rothschild & Sons', type: 'banking peer', description: 'Both are Jewish-founded private banking dynasties.' }] });

// ===================== ARGENTINA =====================
console.log('Adding Argentina entries...');

ae('Argentina', { name: 'DAIA (Delegacion de Asociaciones Israelitas Argentinas)', id: slug('DAIA'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'DAIA (Delegacion de Asociaciones Israelitas Argentinas) is the political representative body of the Argentine Jewish community, the largest in Latin America with approximately 180,000-250,000 members. DAIA combats antisemitism, advocates for the community, and has been at the forefront of seeking justice for the 1994 AMIA bombing that killed 85 people.', website: 'https://www.daia.org.ar', founded: 1935, individuals: [], connections: [{ name: 'AMIA (Asociacion Mutual Israelita Argentina)', type: 'communal partner', description: 'DAIA and AMIA are the two primary institutions of Argentine Jewry.' }] });
ae('Argentina', { name: 'MercadoLibre', id: slug('MercadoLibre'), type: 'e-commerce platform', category: 'Technology', description: 'MercadoLibre is the largest e-commerce and fintech company in Latin America, often called "the Amazon of Latin America." Founded in 1999 by Marcos Galperin, a Jewish Argentine entrepreneur, the company operates in 18 countries and has a market capitalization exceeding $70 billion. Its MercadoPago payment platform is the leading fintech solution in the region.', website: 'https://www.mercadolibre.com', founded: 1999, individuals: [{ id: slug('Marcos Galperin'), name: 'Marcos Galperin', role: 'Founder & CEO', bio: 'Founder and CEO of MercadoLibre, Latin America\'s largest e-commerce platform. One of the wealthiest people in Argentina.' }], connections: [] });

// ===================== MEXICO =====================
console.log('Adding Mexico entries...');

ae('Mexico', { name: 'Comite Central de la Comunidad Judia de Mexico', id: slug('Comite Central Comunidad Judia Mexico'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Comite Central de la Comunidad Judia de Mexico is the central representative body of Mexican Jewry, coordinating the activities of the various Jewish communities in Mexico. Mexico\'s Jewish community of approximately 50,000 is concentrated in Mexico City and includes Ashkenazi, Sephardic, and Syrian segments.', website: '', founded: 1938, individuals: [], connections: [] });
ae('Mexico', { name: 'Grupo Televisa', id: slug('Grupo Televisa'), type: 'media company', category: 'Entertainment & Media', description: 'Grupo Televisa is the largest mass media company in the Spanish-speaking world, headquartered in Mexico City. While the Azcarraga family has led the company, several prominent Jewish Mexican businessmen have been involved in its operations and have significant stakes in Mexican media and business.', website: 'https://www.televisa.com', founded: 1973, individuals: [], connections: [] });

// ===================== CHINA/HONG KONG =====================
console.log('Adding China entries...');

ae('China', { name: 'Sassoon Group Historical Legacy', id: slug('Sassoon Group Legacy'), type: 'historical trading house', category: 'Conglomerates & Holding Companies', description: 'The Sassoon family, known as the "Rothschilds of the East," was a Baghdadi Jewish family that built one of the most prominent business empires in Asia from the 18th to 20th centuries. The Sassoons were instrumental in developing trade between India, China, and Britain, and built landmarks including the Sassoon House in Shanghai and the Peace Hotel.', website: '', founded: 1832, individuals: [{ id: slug('David Sassoon'), name: 'David Sassoon', role: 'Founder', bio: 'Founder of the Sassoon business dynasty. Baghdadi Jewish merchant who established trading houses across Asia.' }], connections: [] });
ae('Hong Kong', { name: 'Kadoorie Family Enterprises', id: slug('Kadoorie Family Enterprises'), type: 'investment conglomerate', category: 'Conglomerates & Holding Companies', description: 'The Kadoorie family is one of the wealthiest and most prominent families in Hong Kong. Of Baghdadi Jewish origin, the family controls CLP Holdings (Hong Kong\'s major electricity provider), The Peninsula Hotels, and other businesses. The Kadoories are among the few Jewish families with deep roots in Hong Kong\'s business elite.', website: '', founded: 1880, individuals: [{ id: slug('Michael Kadoorie'), name: 'Michael Kadoorie', role: 'Chairman', bio: 'Chairman of CLP Holdings and The Hongkong and Shanghai Hotels. One of the wealthiest people in Hong Kong.' }], connections: [] });

// ===================== UAE =====================
console.log('Adding UAE entries...');

ae('United Arab Emirates', { name: 'Jewish Council of the Emirates', id: slug('Jewish Council of the Emirates'), type: 'communal organization', category: 'Community & Social Organizations', description: 'The Jewish Council of the Emirates is the representative body of the Jewish community in the UAE, which has grown significantly since the Abraham Accords in 2020. The JCE supports community programming, interfaith dialogue, and Jewish life in Dubai and Abu Dhabi from the community that numbers over 1,000 members and continues to grow.', website: 'https://www.jewishcounciluae.com', founded: 2020, individuals: [{ id: slug('Ross Kriel'), name: 'Ross Kriel', role: 'President', bio: 'President of the Jewish Council of the Emirates. South African-born businessman who helped establish Jewish communal life in the UAE.' }], connections: [] });

// ===================== TURKEY =====================
console.log('Adding Turkey entries...');

ae('Turkey', { name: 'Quincentennial Foundation', id: slug('Quincentennial Foundation Turkey'), type: 'cultural organization', category: 'Heritage & Memorials', description: 'The Quincentennial Foundation was established in 1989 to mark the 500th anniversary of the arrival of Sephardic Jews in the Ottoman Empire after their expulsion from Spain in 1492. It operates a museum of Turkish Jews in Istanbul and promotes the cultural heritage of Turkey\'s Jewish community, which numbers approximately 15,000 and is concentrated in Istanbul.', website: '', founded: 1989, individuals: [], connections: [] });

// ===================== DENMARK =====================
console.log('Adding Denmark entries...');

ae('Denmark', { name: 'Danish Jewish Museum', id: slug('Danish Jewish Museum'), type: 'museum', category: 'Heritage & Memorials', description: 'The Danish Jewish Museum in Copenhagen tells the story of Jewish life in Denmark over 400 years. It is housed in a building designed by architect Daniel Libeskind (who also designed the Jewish Museum Berlin). A central focus is the 1943 rescue of Danish Jews, when Danish citizens helped nearly 7,000 Jews escape to neutral Sweden.', website: 'https://www.jewmus.dk', founded: 2004, individuals: [], connections: [{ name: 'Jewish Museum Berlin', type: 'museum peer', description: 'Both were designed by architect Daniel Libeskind.' }] });

// ===================== AUSTRIA =====================  
console.log('Adding Austria entries...');

ae('Austria', { name: 'Jewish Community of Vienna', id: slug('Jewish Community of Vienna'), type: 'communal organization', category: 'Community & Social Organizations', description: 'The Jewish Community of Vienna (Israelitische Kultusgemeinde Wien) is the organized Jewish community in Austria\'s capital. Before the Holocaust, Vienna was home to one of Europe\'s most vibrant Jewish communities with over 200,000 members. Today the community numbers approximately 8,000 and operates synagogues, schools, welfare services, and cultural institutions.', website: 'https://www.ikg-wien.at', founded: 1852, individuals: [], connections: [] });
ae('Austria', { name: 'Vienna Wiesenthal Institute', id: slug('Vienna Wiesenthal Institute'), type: 'research institute', category: 'Research & Think Tanks', description: 'The Vienna Wiesenthal Institute for Holocaust Studies (VWI) is an academic institution dedicated to researching and documenting the Holocaust, genocide, and political violence. Named after Simon Wiesenthal, the famed Nazi hunter who was based in Vienna, the institute conducts research, hosts fellows, and maintains archives.', website: 'https://www.vwi.ac.at', founded: 2009, individuals: [], connections: [{ name: 'Simon Wiesenthal Center', type: 'namesake', description: 'Both honor the legacy of Simon Wiesenthal.' }] });

// ===================== CZECH REPUBLIC =====================
console.log('Adding Czech Republic entries...');

ae('Czech Republic', { name: 'Jewish Museum in Prague', id: slug('Jewish Museum in Prague'), type: 'museum', category: 'Heritage & Memorials', description: 'The Jewish Museum in Prague is one of the oldest and most significant Jewish museums in the world, established in 1906. It manages a unique collection of Jewish artifacts and maintains several historic sites including the Old Jewish Cemetery, the Spanish Synagogue, the Pinkas Synagogue (a Holocaust memorial), and others in Prague\'s Jewish Quarter.', website: 'https://www.jewishmuseum.cz', founded: 1906, individuals: [], connections: [{ name: 'Jewish Museum Berlin', type: 'museum peer', description: 'Both are major Jewish museums in Central Europe.' }] });

// ===================== SOUTH KOREA =====================
console.log('Adding South Korea entries...');

ae('South Korea', { name: 'Chabad of South Korea', id: slug('Chabad of South Korea'), type: 'community center', category: 'Community & Social Organizations', description: 'Chabad of South Korea serves the Jewish community in Seoul and across South Korea, providing religious services, kosher food, holiday celebrations, and community support. South Korea\'s Jewish community consists primarily of businesspeople, diplomats, military personnel, and English teachers.', website: '', founded: 2008, individuals: [], connections: [{ name: 'Chabad', type: 'affiliated movement', description: 'Part of the worldwide Chabad-Lubavitch network.' }] });

// ===================== SINGAPORE =====================
console.log('Adding Singapore entries...');

ae('Singapore', { name: 'United Hebrew Congregation of Singapore', id: slug('United Hebrew Congregation Singapore'), type: 'synagogue', category: 'Religion & Synagogues', description: 'The United Hebrew Congregation (Maghain Aboth Synagogue and Chesed-El Synagogue) serves Singapore\'s Jewish community. The Maghain Aboth Synagogue, built in 1878, is the oldest synagogue in Southeast Asia. Singapore\'s Jewish community numbers approximately 2,500 and includes both long-established Sephardic families and expatriate Ashkenazi Jews.', website: '', founded: 1878, individuals: [], connections: [] });

// ===================== COLOMBIA =====================
console.log('Adding Colombia entries...');

ae('Colombia', { name: 'Confederacion de Comunidades Judias de Colombia', id: slug('Confederacion Comunidades Judias Colombia'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Confederacion de Comunidades Judias de Colombia is the umbrella organization of the Colombian Jewish community, approximately 5,000-7,000 strong, concentrated in Bogota, Medellin, Cali, and Barranquilla. The community supports schools, synagogues, cultural centers, and maintains strong ties with Israel.', website: '', founded: 1975, individuals: [], connections: [] });

// ===================== NEW COUNTRIES/SMALL COMMUNITIES =====================
console.log('Adding to smaller communities...');

ae('Peru', { name: 'Asociacion Judia del Peru', id: slug('Asociacion Judia del Peru'), type: 'communal organization', category: 'Representative & Umbrella Bodies', description: 'The Asociacion Judia del Peru represents the approximately 2,500-strong Jewish community of Peru, centered in Lima. The community includes descendants of crypto-Jews from colonial times, as well as immigrants from Eastern Europe, North Africa, and the Middle East. It operates the Leon Pinelo School, one of the premier Jewish schools in Latin America.', website: '', founded: 1942, individuals: [], connections: [] });
ae('Romania', { name: 'Federation of Jewish Communities in Romania', id: slug('Federation Jewish Communities Romania'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Federation of Jewish Communities in Romania represents the approximately 6,000-9,000 Jews remaining in Romania. Before the Holocaust, Romania had over 800,000 Jews. The Federation manages synagogues, community centers, welfare programs, and preserves the rich heritage of Romanian Jewry. It publishes the Realitatea Evreiasca newspaper.', website: 'https://www.fedrom.ro', founded: 1948, individuals: [{ id: slug('Silviu Vexler'), name: 'Silviu Vexler', role: 'President & MP', bio: 'President of the Federation of Jewish Communities in Romania and member of the Romanian Parliament representing the Jewish minority.' }], connections: [] });
ae('Greece', { name: 'Central Board of Jewish Communities in Greece', id: slug('Central Board Jewish Communities Greece'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Central Board of Jewish Communities in Greece (KIS) represents the approximately 5,000 Jews in Greece. Before the Holocaust, Greece was home to over 77,000 Jews, with the ancient community of Thessaloniki being particularly significant as a center of Sephardic culture.', website: '', founded: 1945, individuals: [], connections: [] });
ae('Ukraine', { name: 'Jewish Confederation of Ukraine', id: slug('Jewish Confederation of Ukraine'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Jewish Confederation of Ukraine represents the Jewish community of Ukraine, estimated at 50,000-200,000 people. Ukraine has deep historical significance for world Jewry as the birthplace of Hasidism and home to major Jewish centers before the Holocaust. Notable Ukrainian Jews include Sholom Aleichem, Ze\'ev Jabotinsky, and Golda Meir.', website: '', founded: 1999, individuals: [], connections: [] });
ae('Ireland', { name: 'Jewish Representative Council of Ireland', id: slug('Jewish Representative Council Ireland'), type: 'representative body', category: 'Representative & Umbrella Bodies', description: 'The Jewish Representative Council of Ireland represents the approximately 2,500 Jews in the Republic of Ireland. The Irish Jewish community, while small, has played a notable role in Irish history, including Robert Briscoe who served as Lord Mayor of Dublin, and the community\'s depiction in James Joyce\'s Ulysses through the character Leopold Bloom.', website: '', founded: 1949, individuals: [], connections: [] });

console.log(`\nAdded ${added} new entries total`);

// REBUILD AFFILIATIONS
console.log('Rebuilding affiliations...');
const affMap = {};
for (const country in data.countries) { for (const entry of data.countries[country]) { for (const ind of (entry.individuals || [])) { if (!affMap[ind.id]) affMap[ind.id] = []; affMap[ind.id].push({ organization: entry.name, role: ind.role || 'Associated', entryId: entry.id, country: country }); } } }
let affCount = 0;
for (const pid in peopleData.people) { if (!peopleData.people[pid].affiliations) peopleData.people[pid].affiliations = []; if (affMap[pid]) { for (const aff of affMap[pid]) { if (!peopleData.people[pid].affiliations.some(a => a.entryId === aff.entryId)) { peopleData.people[pid].affiliations.push(aff); affCount++; } } } }
console.log(`Updated ${affCount} affiliations`);

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2));
fs.writeFileSync(peoplePath, JSON.stringify(peopleData, null, 2));

let t = 0, tc = 0, cs = new Set();
for (const c in data.countries) { cs.add(c); t += data.countries[c].length; data.countries[c].forEach(e => { if (e.connections) tc += e.connections.length; }); }
console.log(`\nTotal: ${t} entries | ${cs.size} countries | ${Object.keys(peopleData.people).length} people | ${tc} connections`);
